
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.reservoir
import jneqsim.process.equipment.splitter
import jneqsim.process.equipment.stream
import jneqsim.process.fielddevelopment.concept
import jneqsim.process.fielddevelopment.economics
import jneqsim.process.fielddevelopment.tieback
import jneqsim.process.fielddevelopment.tieback.capacity
import jneqsim.process.processmodel
import jneqsim.thermo.system
import typing



class AreaDevelopmentEvaluator:
    def __init__(self): ...
    def evaluate(self, areaDevelopmentPortfolio: 'AreaDevelopmentPortfolio') -> 'AreaDevelopmentResult': ...

class AreaDevelopmentOption(java.io.Serializable):
    def getLifecycleConcept(self) -> 'FieldLifecycleConcept': ...
    def getName(self) -> java.lang.String: ...
    def getReceivingAssetName(self) -> java.lang.String: ...
    def getRouteType(self) -> 'AreaDevelopmentOption.RouteType': ...
    @staticmethod
    def greenfield(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], fieldLifecycleConcept: 'FieldLifecycleConcept') -> 'AreaDevelopmentOption': ...
    @staticmethod
    def tieback(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], fieldLifecycleConcept: 'FieldLifecycleConcept') -> 'AreaDevelopmentOption': ...
    class RouteType(java.lang.Enum['AreaDevelopmentOption.RouteType']):
        GREENFIELD: typing.ClassVar['AreaDevelopmentOption.RouteType'] = ...
        HOST_TIEBACK: typing.ClassVar['AreaDevelopmentOption.RouteType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'AreaDevelopmentOption.RouteType': ...
        @staticmethod
        def values() -> typing.MutableSequence['AreaDevelopmentOption.RouteType']: ...

class AreaDevelopmentPortfolio(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addOption(self, areaDevelopmentOption: AreaDevelopmentOption) -> 'AreaDevelopmentPortfolio': ...
    def getAreaName(self) -> java.lang.String: ...
    def getOptions(self) -> java.util.List[AreaDevelopmentOption]: ...

class AreaDevelopmentResult(java.io.Serializable):
    def getAreaName(self) -> java.lang.String: ...
    def getRankedOptions(self) -> java.util.List['AreaDevelopmentResult.OptionResult']: ...
    def getRecommendedOption(self) -> 'AreaDevelopmentResult.OptionResult': ...
    def toMarkdownTable(self) -> java.lang.String: ...
    class OptionResult(java.io.Serializable):
        def getLifecycleResult(self) -> 'FieldLifecycleResult': ...
        def getOption(self) -> AreaDevelopmentOption: ...
        def isEligible(self) -> bool: ...

class FacilityCapacity(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float): ...
    @staticmethod
    def fromDesignRates(facilityProductionRate: 'FacilityProductionRate', double: float, double2: float) -> 'FacilityCapacity': ...
    @staticmethod
    def fromHostFacility(hostFacility: jneqsim.process.fielddevelopment.tieback.HostFacility, double: float) -> 'FacilityCapacity': ...
    def getGasSm3PerDay(self) -> float: ...
    def getLiquidSm3PerDay(self) -> float: ...
    def getMaximumUtilization(self, facilityProductionRate: 'FacilityProductionRate') -> float: ...
    def getOilSm3PerDay(self) -> float: ...
    def getPowerKw(self) -> float: ...
    def getPrimaryConstraint(self, facilityProductionRate: 'FacilityProductionRate') -> java.lang.String: ...
    def getWaterSm3PerDay(self) -> float: ...
    def remainingAfter(self, facilityProductionRate: 'FacilityProductionRate') -> 'FacilityCapacity': ...
    def scaleToFit(self, facilityProductionRate: 'FacilityProductionRate') -> float: ...

class FacilityCapacityAllocator:
    def __init__(self): ...
    def allocate(self, facilityLifecycleStrategy: 'FacilityLifecycleStrategy', int: int, facilityProductionRate: 'FacilityProductionRate') -> 'FacilityCapacityAllocator.AllocationResult': ...
    class AllocationResult(java.io.Serializable):
        def getCapacity(self) -> FacilityCapacity: ...
        def getHostAllocated(self) -> 'FacilityProductionRate': ...
        def getHostPotential(self) -> 'FacilityProductionRate': ...
        def getHostRequested(self) -> 'FacilityProductionRate': ...
        def getMaximumUtilization(self) -> float: ...
        def getPrimaryBottleneck(self) -> java.lang.String: ...
        def getRequestedMaximumUtilization(self) -> float: ...
        def getRequestedPrimaryBottleneck(self) -> java.lang.String: ...
        def getSatelliteAllocated(self) -> 'FacilityProductionRate': ...
        def getSatellitePotential(self) -> 'FacilityProductionRate': ...
        def getSatelliteRequested(self) -> 'FacilityProductionRate': ...
        def getYear(self) -> int: ...

class FacilityDesignResult(java.io.Serializable):
    def getAutoSizedEquipmentCount(self) -> int: ...
    def getDesignBottleneck(self) -> java.lang.String: ...
    def getDesignBottleneckUtilization(self) -> float: ...
    def getDesignMargin(self) -> float: ...
    def getDesignPowerKw(self) -> float: ...
    def getDesignRates(self) -> 'FacilityProductionRate': ...
    def getDetailedCapacityMultiplier(self) -> float: ...
    def getDevelopmentMode(self) -> 'FacilityLifecycleStrategy.DevelopmentMode': ...
    def getMechanicalConstraintCount(self) -> int: ...
    def getNameplateCapacity(self) -> FacilityCapacity: ...
    def getRequiredParallelTrainCount(self) -> int: ...
    def getStrategyName(self) -> java.lang.String: ...

class FacilityLifecycleStrategy(java.io.Serializable):
    def getAllocationPolicy(self) -> jneqsim.process.fielddevelopment.tieback.capacity.CapacityAllocationPolicy: ...
    def getBaseCapacity(self) -> FacilityCapacity: ...
    def getCapacity(self, int: int) -> FacilityCapacity: ...
    def getDesignMargin(self) -> float: ...
    def getDesignRates(self) -> 'FacilityProductionRate': ...
    def getDevelopmentMode(self) -> 'FacilityLifecycleStrategy.DevelopmentMode': ...
    def getHoldbackPolicy(self) -> jneqsim.process.fielddevelopment.tieback.capacity.HoldbackPolicy: ...
    def getHostFacility(self) -> jneqsim.process.fielddevelopment.tieback.HostFacility: ...
    def getHostHoldbackFraction(self) -> float: ...
    def getHostProduction(self, int: int) -> 'FacilityProductionRate': ...
    def getMaximumDetailedProcessUtilization(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getSatelliteHoldbackFraction(self) -> float: ...
    @staticmethod
    def greenfield(string: typing.Union[java.lang.String, str], facilityProductionRate: 'FacilityProductionRate') -> 'FacilityLifecycleStrategy.Builder': ...
    def isAutoSizeDetailedProcess(self) -> bool: ...
    def isUseDetailedProcessConstraints(self) -> bool: ...
    @staticmethod
    def tieback(string: typing.Union[java.lang.String, str], hostFacility: jneqsim.process.fielddevelopment.tieback.HostFacility, productionProfileSeries: jneqsim.process.fielddevelopment.tieback.capacity.ProductionProfileSeries) -> 'FacilityLifecycleStrategy.Builder': ...
    class Builder:
        def allocationPolicy(self, capacityAllocationPolicy: jneqsim.process.fielddevelopment.tieback.capacity.CapacityAllocationPolicy) -> 'FacilityLifecycleStrategy.Builder': ...
        def autoSizeDetailedProcess(self, boolean: bool) -> 'FacilityLifecycleStrategy.Builder': ...
        def build(self) -> 'FacilityLifecycleStrategy': ...
        def capacityFromYear(self, int: int, facilityCapacity: FacilityCapacity) -> 'FacilityLifecycleStrategy.Builder': ...
        def designMargin(self, double: float) -> 'FacilityLifecycleStrategy.Builder': ...
        def designPowerKw(self, double: float) -> 'FacilityLifecycleStrategy.Builder': ...
        def holdback(self, double: float, double2: float) -> 'FacilityLifecycleStrategy.Builder': ...
        def holdbackPolicy(self, holdbackPolicy: jneqsim.process.fielddevelopment.tieback.capacity.HoldbackPolicy) -> 'FacilityLifecycleStrategy.Builder': ...
        def maximumDetailedProcessUtilization(self, double: float) -> 'FacilityLifecycleStrategy.Builder': ...
        def nameplateCapacity(self, facilityCapacity: FacilityCapacity) -> 'FacilityLifecycleStrategy.Builder': ...
        def useDetailedProcessConstraints(self, boolean: bool) -> 'FacilityLifecycleStrategy.Builder': ...
    class DevelopmentMode(java.lang.Enum['FacilityLifecycleStrategy.DevelopmentMode']):
        GREENFIELD: typing.ClassVar['FacilityLifecycleStrategy.DevelopmentMode'] = ...
        BROWNFIELD_TIEBACK: typing.ClassVar['FacilityLifecycleStrategy.DevelopmentMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FacilityLifecycleStrategy.DevelopmentMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['FacilityLifecycleStrategy.DevelopmentMode']: ...

class FacilityModificationPlan(java.io.Serializable):
    def getCandidates(self) -> java.util.List['FacilityModificationPlan.Candidate']: ...
    def getConceptName(self) -> java.lang.String: ...
    def getTargetUtilization(self) -> float: ...
    def hasCandidates(self) -> bool: ...
    def toMarkdownTable(self) -> java.lang.String: ...
    class Candidate(java.io.Serializable):
        def getAssociatedDeferredOilSm3(self) -> float: ...
        def getBottleneck(self) -> java.lang.String: ...
        def getFirstRequiredYear(self) -> int: ...
        def getModificationScope(self) -> java.lang.String: ...
        def getPeakRequestedUtilization(self) -> float: ...
        def getRequiredCapacityMultiplier(self) -> float: ...

class FacilityModificationPlanner:
    def __init__(self): ...
    def analyse(self, fieldLifecycleResult: 'FieldLifecycleResult', double: float) -> FacilityModificationPlan: ...

class FacilityProductionRate(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float): ...
    def getGasSm3PerDay(self) -> float: ...
    def getLiquidSm3PerDay(self) -> float: ...
    def getOilSm3PerDay(self) -> float: ...
    def getWaterSm3PerDay(self) -> float: ...
    def plus(self, facilityProductionRate: 'FacilityProductionRate') -> 'FacilityProductionRate': ...
    def scale(self, double: float) -> 'FacilityProductionRate': ...
    @staticmethod
    def zero() -> 'FacilityProductionRate': ...

class FieldLifecycleConcept(java.io.Serializable):
    def __init__(self, fieldConcept: jneqsim.process.fielddevelopment.concept.FieldConcept, fieldLifecycleModel: 'FieldLifecycleModel', fieldLifecycleConfiguration: 'FieldLifecycleConfiguration'): ...
    def getConfiguration(self) -> 'FieldLifecycleConfiguration': ...
    def getFieldConcept(self) -> jneqsim.process.fielddevelopment.concept.FieldConcept: ...
    def getModel(self) -> 'FieldLifecycleModel': ...
    def getName(self) -> java.lang.String: ...

class FieldLifecycleConfiguration(java.io.Serializable):
    @staticmethod
    def builder() -> 'FieldLifecycleConfiguration.Builder': ...
    def getAvailability(self) -> float: ...
    def getCapexScheduleMusd(self) -> java.util.Map[int, float]: ...
    def getDiscountRate(self) -> float: ...
    def getEconomicLimitOilRateSm3PerDay(self) -> float: ...
    def getFacilityLifecycleStrategy(self) -> FacilityLifecycleStrategy: ...
    def getFinalWaterCut(self) -> float: ...
    def getFixedOpexMusdPerYear(self) -> float: ...
    def getGasInjectionStartYear(self) -> float: ...
    def getGasPriceUsdPerSm3(self) -> float: ...
    def getGasTariffUsdPerSm3(self) -> float: ...
    def getGridEmissionFactorKgPerKWh(self) -> float: ...
    def getInitialWaterCut(self) -> float: ...
    def getMaximumGasInjectionRateSm3PerDay(self) -> float: ...
    def getMaximumGasRateSm3PerDay(self) -> float: ...
    def getMaximumLiquidRateSm3PerDay(self) -> float: ...
    def getMaximumWaterRateSm3PerDay(self) -> float: ...
    def getMinimumBottomHolePressureBara(self) -> float: ...
    def getOilDensityKgPerSm3(self) -> float: ...
    def getOilPriceUsdPerBbl(self) -> float: ...
    def getOilTariffUsdPerBbl(self) -> float: ...
    def getPlateauOilRateSm3PerDay(self) -> float: ...
    def getProducedGasRecycleFraction(self) -> float: ...
    def getProducerCount(self) -> int: ...
    def getProductSpecifications(self) -> 'FieldProductSpecifications': ...
    def getProductivityIndexSm3PerDayBarPerWell(self) -> float: ...
    def getProjectYears(self) -> float: ...
    def getStartYear(self) -> int: ...
    def getTimeStepDays(self) -> float: ...
    def getVariableOpexUsdPerBoe(self) -> float: ...
    def getWaterBreakthroughYear(self) -> float: ...
    def getWaterCut(self, double: float) -> float: ...
    def getWaterCutRampYears(self) -> float: ...
    def getWaterDensityKgPerSm3(self) -> float: ...
    class Builder:
        def availability(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def build(self) -> 'FieldLifecycleConfiguration': ...
        def capex(self, int: int, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def discountRate(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def economicLimitOilRate(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def facilityCapacities(self, double: float, double2: float, double3: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def facilityLifecycleStrategy(self, facilityLifecycleStrategy: FacilityLifecycleStrategy) -> 'FieldLifecycleConfiguration.Builder': ...
        def gasInjection(self, double: float, double2: float, double3: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def gridEmissionFactor(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def minimumBottomHolePressure(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def opex(self, double: float, double2: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def plateauOilRate(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def prices(self, double: float, double2: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def producers(self, int: int, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def productSpecifications(self, fieldProductSpecifications: 'FieldProductSpecifications') -> 'FieldLifecycleConfiguration.Builder': ...
        def projectYears(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def standardDensities(self, double: float, double2: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def startYear(self, int: int) -> 'FieldLifecycleConfiguration.Builder': ...
        def tariffs(self, double: float, double2: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def timeStepDays(self, double: float) -> 'FieldLifecycleConfiguration.Builder': ...
        def waterCut(self, double: float, double2: float, double3: float, double4: float) -> 'FieldLifecycleConfiguration.Builder': ...

class FieldLifecycleEvaluator:
    def __init__(self): ...
    def evaluate(self, fieldLifecycleConcept: FieldLifecycleConcept) -> 'FieldLifecycleResult': ...
    def evaluateAll(self, list: java.util.List[FieldLifecycleConcept]) -> java.util.List['FieldLifecycleResult']: ...
    def toMarkdownTable(self, list: java.util.List['FieldLifecycleResult']) -> java.lang.String: ...

class FieldLifecycleModel(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, streamInterface3: jneqsim.process.equipment.stream.StreamInterface, streamInterface4: jneqsim.process.equipment.stream.StreamInterface, splitter: jneqsim.process.equipment.splitter.Splitter, streamInterface5: jneqsim.process.equipment.stream.StreamInterface, streamInterface6: jneqsim.process.equipment.stream.StreamInterface, streamInterface7: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, streamInterface3: jneqsim.process.equipment.stream.StreamInterface, streamInterface4: jneqsim.process.equipment.stream.StreamInterface, splitter: jneqsim.process.equipment.splitter.Splitter, streamInterface5: jneqsim.process.equipment.stream.StreamInterface, streamInterface6: jneqsim.process.equipment.stream.StreamInterface, streamInterface7: jneqsim.process.equipment.stream.StreamInterface, streamInterface8: jneqsim.process.equipment.stream.StreamInterface, streamInterface9: jneqsim.process.equipment.stream.StreamInterface, streamInterface10: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, streamInterface3: jneqsim.process.equipment.stream.StreamInterface, streamInterface4: jneqsim.process.equipment.stream.StreamInterface, splitter: jneqsim.process.equipment.splitter.Splitter, streamInterface5: jneqsim.process.equipment.stream.StreamInterface, streamInterface6: jneqsim.process.equipment.stream.StreamInterface, streamInterface7: jneqsim.process.equipment.stream.StreamInterface, streamInterface8: jneqsim.process.equipment.stream.StreamInterface, streamInterface9: jneqsim.process.equipment.stream.StreamInterface, streamInterface10: jneqsim.process.equipment.stream.StreamInterface, streamInterface11: jneqsim.process.equipment.stream.StreamInterface): ...
    @typing.overload
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processModel: jneqsim.process.processmodel.ProcessModel, string2: typing.Union[java.lang.String, str]) -> 'FieldLifecycleModel.Builder': ...
    @typing.overload
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'FieldLifecycleModel.Builder': ...
    @typing.overload
    @staticmethod
    def existingFacility(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processModel: jneqsim.process.processmodel.ProcessModel, string2: typing.Union[java.lang.String, str]) -> 'FieldLifecycleModel.Builder': ...
    @typing.overload
    @staticmethod
    def existingFacility(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'FieldLifecycleModel.Builder': ...
    @typing.overload
    @staticmethod
    def existingSurfAndFacility(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processModel: jneqsim.process.processmodel.ProcessModel, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'FieldLifecycleModel.Builder': ...
    @typing.overload
    @staticmethod
    def existingSurfAndFacility(string: typing.Union[java.lang.String, str], simpleReservoir: jneqsim.process.equipment.reservoir.SimpleReservoir, processSystem: jneqsim.process.processmodel.ProcessSystem, processSystem2: jneqsim.process.processmodel.ProcessSystem) -> 'FieldLifecycleModel.Builder': ...
    def getCompressedInjectionGas(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getExistingSurfSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getFacilityAreaName(self) -> java.lang.String: ...
    def getGasAllocationSplitter(self) -> jneqsim.process.equipment.splitter.Splitter: ...
    def getGasExport(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getHostGasFeed(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getHostOilFeed(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getHostWaterFeed(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getName(self) -> java.lang.String: ...
    def getProcessModel(self) -> jneqsim.process.processmodel.ProcessModel: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProductQualityProvider(self) -> 'FieldProductQualityProvider': ...
    def getProductionPotentialProvider(self) -> 'FieldProductionPotentialProvider': ...
    def getRecoveredGas(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getReservoir(self) -> jneqsim.process.equipment.reservoir.SimpleReservoir: ...
    def getReservoirGasInjector(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getReservoirOilProducer(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getReservoirWaterProducer(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getStabilizedOilExport(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getSurfAreaName(self) -> java.lang.String: ...
    def getTreatedWaterDischarge(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def hasExistingSurfSystem(self) -> bool: ...
    def hasHostProductionFeeds(self) -> bool: ...
    def hasProcessModel(self) -> bool: ...
    def setProductQualityProvider(self, fieldProductQualityProvider: typing.Union['FieldProductQualityProvider', typing.Callable]) -> 'FieldLifecycleModel': ...
    def setProductionPotentialProvider(self, fieldProductionPotentialProvider: typing.Union['FieldProductionPotentialProvider', typing.Callable]) -> 'FieldLifecycleModel': ...
    class Builder:
        def build(self) -> 'FieldLifecycleModel': ...
        def exportStreams(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface) -> 'FieldLifecycleModel.Builder': ...
        def gasHandling(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, splitter: jneqsim.process.equipment.splitter.Splitter, streamInterface2: jneqsim.process.equipment.stream.StreamInterface) -> 'FieldLifecycleModel.Builder': ...
        def hostFeeds(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, streamInterface3: jneqsim.process.equipment.stream.StreamInterface) -> 'FieldLifecycleModel.Builder': ...
        def productQualityProvider(self, fieldProductQualityProvider: typing.Union['FieldProductQualityProvider', typing.Callable]) -> 'FieldLifecycleModel.Builder': ...
        def productionPotentialProvider(self, fieldProductionPotentialProvider: typing.Union['FieldProductionPotentialProvider', typing.Callable]) -> 'FieldLifecycleModel.Builder': ...
        def reservoirStreams(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface, streamInterface2: jneqsim.process.equipment.stream.StreamInterface, streamInterface3: jneqsim.process.equipment.stream.StreamInterface) -> 'FieldLifecycleModel.Builder': ...
        def treatedWaterDischarge(self, streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> 'FieldLifecycleModel.Builder': ...

class FieldLifecycleResult(java.io.Serializable):
    def areAllProductSpecificationsMet(self) -> bool: ...
    def getAnnualResults(self) -> java.util.List['FieldLifecycleResult.AnnualResult']: ...
    def getBreakevenGasPriceUsdPerSm3(self) -> float: ...
    def getBreakevenOilPriceUsdPerBbl(self) -> float: ...
    def getCashFlowResult(self) -> jneqsim.process.fielddevelopment.economics.CashFlowEngine.CashFlowResult: ...
    def getConceptName(self) -> java.lang.String: ...
    def getCumulativeDeferredOilSm3(self) -> float: ...
    def getCumulativeGasExportSm3(self) -> float: ...
    def getCumulativeGasInjectedSm3(self) -> float: ...
    def getCumulativeOilSm3(self) -> float: ...
    def getCumulativeWaterProducedSm3(self) -> float: ...
    def getFacilityDesignResult(self) -> FacilityDesignResult: ...
    def getFinalReservoirPressureBara(self) -> float: ...
    def getInitialReservoirPressureBara(self) -> float: ...
    def getIrr(self) -> float: ...
    def getLifecycleCo2Tonnes(self) -> float: ...
    def getLifecycleEnergyMWh(self) -> float: ...
    def getNpvMusd(self) -> float: ...
    def getOffSpecificationYears(self) -> int: ...
    def getPaybackYears(self) -> float: ...
    def getPeakFacilityUtilization(self) -> float: ...
    def getPeakUnconstrainedFacilityUtilization(self) -> float: ...
    def getProductSpecificationSummary(self) -> java.lang.String: ...
    def getStopReason(self) -> java.lang.String: ...
    def toMarkdownRow(self) -> java.lang.String: ...
    class AnnualResult(java.io.Serializable):
        def getAverageOilRateSm3PerDay(self) -> float: ...
        def getAverageReservoirPressureBara(self) -> float: ...
        def getAverageWaterCut(self) -> float: ...
        def getCapacityDeferredOilSm3(self) -> float: ...
        def getCo2EmissionsTonnes(self) -> float: ...
        def getEnergyMWh(self) -> float: ...
        def getGasExportSm3(self) -> float: ...
        def getGasInjectedSm3(self) -> float: ...
        def getHoldbackOilSm3(self) -> float: ...
        def getHostGasRateSm3PerDay(self) -> float: ...
        def getHostOilRateSm3PerDay(self) -> float: ...
        def getHostWaterRateSm3PerDay(self) -> float: ...
        def getMaximumFacilityUtilization(self) -> float: ...
        def getOilSm3(self) -> float: ...
        def getPotentialOilRateSm3PerDay(self) -> float: ...
        def getPrimaryBottleneck(self) -> java.lang.String: ...
        def getProductSpecificationResult(self) -> 'ProductSpecificationResult': ...
        def getRequestedOilRateSm3PerDay(self) -> float: ...
        def getUnconstrainedBottleneck(self) -> java.lang.String: ...
        def getUnconstrainedFacilityUtilization(self) -> float: ...
        def getWaterProducedSm3(self) -> float: ...
        def getYear(self) -> int: ...

class FieldLifecycleSimulator:
    def __init__(self): ...
    @typing.overload
    def run(self, fieldLifecycleConcept: FieldLifecycleConcept) -> FieldLifecycleResult: ...
    @typing.overload
    def run(self, fieldLifecycleModel: FieldLifecycleModel, fieldLifecycleConfiguration: FieldLifecycleConfiguration) -> FieldLifecycleResult: ...

class FieldProductQualityProvider(java.io.Serializable):
    def evaluate(self, fieldLifecycleModel: FieldLifecycleModel, fieldProductSpecifications: 'FieldProductSpecifications') -> 'ProductSpecificationResult': ...

class FieldProductSpecifications(java.io.Serializable):
    @staticmethod
    def builder() -> 'FieldProductSpecifications.Builder': ...
    def getGasDewPointReferencePressureBara(self) -> float: ...
    def getMaximumGasCo2MolePercent(self) -> float: ...
    def getMaximumGasGrossCalorificValueMjPerSm3(self) -> float: ...
    def getMaximumGasH2sPpm(self) -> float: ...
    def getMaximumGasHydrocarbonDewPointC(self) -> float: ...
    def getMaximumGasOxygenMolePercent(self) -> float: ...
    def getMaximumGasRelativeDensity(self) -> float: ...
    def getMaximumGasWaterDewPointC(self) -> float: ...
    def getMaximumGasWobbeIndexMjPerSm3(self) -> float: ...
    def getMaximumOilBswVolumePercent(self) -> float: ...
    def getMaximumOilInWaterMgPerL(self) -> float: ...
    def getMaximumOilRvpBara(self) -> float: ...
    def getMinimumGasGrossCalorificValueMjPerSm3(self) -> float: ...
    def getMinimumGasWobbeIndexMjPerSm3(self) -> float: ...
    def getViolationAction(self) -> 'FieldProductSpecifications.ViolationAction': ...
    def hasActiveLimits(self) -> bool: ...
    class Builder:
        def build(self) -> 'FieldProductSpecifications': ...
        def gasComposition(self, double: float, double2: float) -> 'FieldProductSpecifications.Builder': ...
        def gasDewPoints(self, double: float, double2: float, double3: float) -> 'FieldProductSpecifications.Builder': ...
        def gasEnergyContent(self, double: float, double2: float, double3: float, double4: float, double5: float) -> 'FieldProductSpecifications.Builder': ...
        def gasOxygen(self, double: float) -> 'FieldProductSpecifications.Builder': ...
        def oilExport(self, double: float, double2: float) -> 'FieldProductSpecifications.Builder': ...
        def producedWater(self, double: float) -> 'FieldProductSpecifications.Builder': ...
        def violationAction(self, violationAction: 'FieldProductSpecifications.ViolationAction') -> 'FieldProductSpecifications.Builder': ...
    class ViolationAction(java.lang.Enum['FieldProductSpecifications.ViolationAction']):
        REPORT_ONLY: typing.ClassVar['FieldProductSpecifications.ViolationAction'] = ...
        REJECT_OPTION: typing.ClassVar['FieldProductSpecifications.ViolationAction'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FieldProductSpecifications.ViolationAction': ...
        @staticmethod
        def values() -> typing.MutableSequence['FieldProductSpecifications.ViolationAction']: ...

class FieldProductionPotentialProvider(java.io.Serializable):
    def getPotential(self, fieldLifecycleModel: FieldLifecycleModel, fieldLifecycleConfiguration: FieldLifecycleConfiguration, double: float, double2: float) -> FacilityProductionRate: ...

class NorwegianOilFieldCase:
    @staticmethod
    def createAreaDevelopmentPortfolio() -> AreaDevelopmentPortfolio: ...
    @staticmethod
    def createCase(string: typing.Union[java.lang.String, str], double: float, double2: float) -> FieldLifecycleConcept: ...
    @staticmethod
    def createDevelopmentPortfolio() -> java.util.List[FieldLifecycleConcept]: ...
    @staticmethod
    def createGasInjectionCase() -> FieldLifecycleConcept: ...
    @staticmethod
    def createHostPriorityTiebackCase() -> FieldLifecycleConcept: ...
    @staticmethod
    def createManagedTiebackCase() -> FieldLifecycleConcept: ...
    @staticmethod
    def createNaturalDepletionCase() -> FieldLifecycleConcept: ...
    @staticmethod
    def createRemoteHostTiebackCase() -> FieldLifecycleConcept: ...
    @staticmethod
    def createReservoirFluid() -> jneqsim.thermo.system.SystemInterface: ...

class ProductSpecificationEvaluator:
    def __init__(self): ...
    @typing.overload
    def evaluate(self, fieldLifecycleModel: FieldLifecycleModel, fieldProductSpecifications: FieldProductSpecifications) -> 'ProductSpecificationResult': ...
    @typing.overload
    def evaluate(self, fieldLifecycleModel: FieldLifecycleModel, fieldProductSpecifications: FieldProductSpecifications, double: float) -> 'ProductSpecificationResult': ...

class ProductSpecificationResult(java.io.Serializable):
    def combine(self, productSpecificationResult: 'ProductSpecificationResult') -> 'ProductSpecificationResult': ...
    def getGasCo2MolePercent(self) -> float: ...
    def getGasGrossCalorificValueMjPerSm3(self) -> float: ...
    def getGasH2sPpm(self) -> float: ...
    def getGasHydrocarbonDewPointC(self) -> float: ...
    def getGasOxygenMolePercent(self) -> float: ...
    def getGasRelativeDensity(self) -> float: ...
    def getGasWaterDewPointC(self) -> float: ...
    def getGasWobbeIndexMjPerSm3(self) -> float: ...
    def getOilBswVolumePercent(self) -> float: ...
    def getOilInWaterMgPerL(self) -> float: ...
    def getOilRvpBara(self) -> float: ...
    def getSummary(self) -> java.lang.String: ...
    def getViolations(self) -> java.util.List[java.lang.String]: ...
    def isCompliant(self) -> bool: ...
    def isEvaluated(self) -> bool: ...
    @staticmethod
    def notEvaluated() -> 'ProductSpecificationResult': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.fielddevelopment.lifecycle")``.

    AreaDevelopmentEvaluator: typing.Type[AreaDevelopmentEvaluator]
    AreaDevelopmentOption: typing.Type[AreaDevelopmentOption]
    AreaDevelopmentPortfolio: typing.Type[AreaDevelopmentPortfolio]
    AreaDevelopmentResult: typing.Type[AreaDevelopmentResult]
    FacilityCapacity: typing.Type[FacilityCapacity]
    FacilityCapacityAllocator: typing.Type[FacilityCapacityAllocator]
    FacilityDesignResult: typing.Type[FacilityDesignResult]
    FacilityLifecycleStrategy: typing.Type[FacilityLifecycleStrategy]
    FacilityModificationPlan: typing.Type[FacilityModificationPlan]
    FacilityModificationPlanner: typing.Type[FacilityModificationPlanner]
    FacilityProductionRate: typing.Type[FacilityProductionRate]
    FieldLifecycleConcept: typing.Type[FieldLifecycleConcept]
    FieldLifecycleConfiguration: typing.Type[FieldLifecycleConfiguration]
    FieldLifecycleEvaluator: typing.Type[FieldLifecycleEvaluator]
    FieldLifecycleModel: typing.Type[FieldLifecycleModel]
    FieldLifecycleResult: typing.Type[FieldLifecycleResult]
    FieldLifecycleSimulator: typing.Type[FieldLifecycleSimulator]
    FieldProductQualityProvider: typing.Type[FieldProductQualityProvider]
    FieldProductSpecifications: typing.Type[FieldProductSpecifications]
    FieldProductionPotentialProvider: typing.Type[FieldProductionPotentialProvider]
    NorwegianOilFieldCase: typing.Type[NorwegianOilFieldCase]
    ProductSpecificationEvaluator: typing.Type[ProductSpecificationEvaluator]
    ProductSpecificationResult: typing.Type[ProductSpecificationResult]
