
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.calculation
import typing



class CompressorProtectionQualificationCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['CompressorProtectionQualificationCalculation.Input', 'CompressorProtectionQualificationCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'CompressorProtectionQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'CompressorProtectionQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['CompressorProtectionQualificationCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
        class Builder:
            def addOperatingCase(self, operatingCase: 'CompressorProtectionQualificationCalculation.OperatingCase') -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def antiSurgeResponse(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def build(self) -> 'CompressorProtectionQualificationCalculation.Input': ...
            def driverAndStartup(self, double: float, double2: float, double3: float) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def mapLimits(self, double: float, double2: float, double3: float, double4: float) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def rotorDynamics(self, double: float, double2: float, boolean: bool) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def rundown(self, double: float, double2: float) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def settleOut(self, double: float, double2: float) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
            def vendorGuaranteeAccepted(self, boolean: bool) -> 'CompressorProtectionQualificationCalculation.Input.Builder': ...
    class OperatingCase(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
    class Result(jneqsim.process.engineering.calculation.EngineeringConstraintResult, java.io.Serializable):
        def allConstraintsSatisfied(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.rotating")``.

    CompressorProtectionQualificationCalculation: typing.Type[CompressorProtectionQualificationCalculation]
