
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.pump
import jneqsim.process.mechanicaldesign
import typing



class PumpApi610DesignCalculator(java.io.Serializable):
    def __init__(self): ...
    def calculate(self) -> None: ...
    @staticmethod
    def calculateBearingL10LifeHours(double: float, double2: float, double3: float, bearingType: 'PumpApi610DesignCalculator.BearingType') -> float: ...
    def copyConfiguration(self) -> 'PumpApi610DesignCalculator': ...
    def getAbsorbedPowerKw(self) -> float: ...
    def getAssessmentBasis(self) -> java.lang.String: ...
    def getAssessmentStatus(self) -> 'PumpApi610DesignCalculator.AssessmentStatus': ...
    def getBearingL10LifeHours(self) -> float: ...
    def getBepFlowM3h(self) -> float: ...
    def getBepHeadM(self) -> float: ...
    def getBepSource(self) -> 'PumpApi610DesignCalculator.DataSource': ...
    def getCheck(self, string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.Check': ...
    def getChecks(self) -> java.util.List['PumpApi610DesignCalculator.Check']: ...
    def getCriticalSpeedRatio(self) -> float: ...
    def getDutyPointSource(self) -> 'PumpApi610DesignCalculator.DataSource': ...
    def getFluidDensityKgM3(self) -> float: ...
    def getFurnishedMawpBara(self) -> float: ...
    def getGoverningShutoffHeadM(self) -> float: ...
    def getHeadRiseToShutoffFraction(self) -> float: ...
    def getHydrostaticTestPressureBara(self) -> float: ...
    def getNpshAvailableM(self) -> float: ...
    def getNpshMarginM(self) -> float: ...
    def getNpshMarginRatio(self) -> float: ...
    def getNpshRequiredM(self) -> float: ...
    def getNpshrSource(self) -> 'PumpApi610DesignCalculator.DataSource': ...
    def getOperatingFlowM3h(self) -> float: ...
    def getOperatingFlowRatio(self) -> float: ...
    def getOperatingRegion(self) -> java.lang.String: ...
    def getPreliminaryHydrostaticTestPressureBara(self) -> float: ...
    def getPumpType(self) -> 'PumpApi610DesignCalculator.Api610PumpType': ...
    def getPumpTypeSource(self) -> 'PumpApi610DesignCalculator.DataSource': ...
    def getRatedHeadM(self) -> float: ...
    def getRatedSpeedRpm(self) -> float: ...
    def getRequiredCasingPressureBara(self) -> float: ...
    def getRequiredDriverPowerKw(self) -> float: ...
    def getSelectedDriverPowerKw(self) -> float: ...
    def getShutoffHeadSource(self) -> 'PumpApi610DesignCalculator.DataSource': ...
    def getStandardEdition(self) -> java.lang.String: ...
    @staticmethod
    def selectDriverRating(double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> float: ...
    def setBearingData(self, bearingType: 'PumpApi610DesignCalculator.BearingType', double: float, double2: float) -> None: ...
    def setBepPoint(self, double: float, double2: float, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setBepSource(self, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setDriverCriteria(self, double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setDutyPoint(self, double: float, double2: float, double3: float, double4: float, double5: float) -> None: ...
    def setDutyPointSource(self, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setHydrostaticTestPressureBara(self, double: float) -> None: ...
    def setMechanicalCriteria(self, double: float, double2: float, double3: float, double4: float, double5: float) -> None: ...
    def setMechanicalEvidence(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setMinimumHeadRiseToShutoffFraction(self, double: float) -> None: ...
    def setNpsh(self, double: float, double2: float, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setNpshCriteria(self, double: float, double2: float) -> None: ...
    def setNpshrSource(self, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setOperatingRegions(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setPressureBasis(self, double: float, double2: float, double3: float, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setPressureCriteria(self, double: float, double2: float) -> None: ...
    @typing.overload
    def setPumpType(self, api610PumpType: 'PumpApi610DesignCalculator.Api610PumpType') -> None: ...
    @typing.overload
    def setPumpType(self, api610PumpType: 'PumpApi610DesignCalculator.Api610PumpType', dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setRatedPointRegion(self, double: float, double2: float) -> None: ...
    def setSeallessPump(self, boolean: bool) -> None: ...
    def setShutoffHeadSource(self, dataSource: 'PumpApi610DesignCalculator.DataSource') -> None: ...
    def setStandardEdition(self, string: typing.Union[java.lang.String, str]) -> None: ...
    class Api610PumpType(java.lang.Enum['PumpApi610DesignCalculator.Api610PumpType']):
        UNSPECIFIED: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH1: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH2: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH3: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH4: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH5: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        OH6: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        BB1: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        BB2: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        BB3: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        BB4: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        BB5: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS1: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS2: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS3: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS4: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS5: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS6: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        VS7: typing.ClassVar['PumpApi610DesignCalculator.Api610PumpType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.Api610PumpType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpApi610DesignCalculator.Api610PumpType']: ...
    class AssessmentStatus(java.lang.Enum['PumpApi610DesignCalculator.AssessmentStatus']):
        PASS: typing.ClassVar['PumpApi610DesignCalculator.AssessmentStatus'] = ...
        PASS_WITH_WARNINGS: typing.ClassVar['PumpApi610DesignCalculator.AssessmentStatus'] = ...
        FAIL: typing.ClassVar['PumpApi610DesignCalculator.AssessmentStatus'] = ...
        NOT_EVALUATED: typing.ClassVar['PumpApi610DesignCalculator.AssessmentStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.AssessmentStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpApi610DesignCalculator.AssessmentStatus']: ...
    class BearingType(java.lang.Enum['PumpApi610DesignCalculator.BearingType']):
        BALL: typing.ClassVar['PumpApi610DesignCalculator.BearingType'] = ...
        ROLLER: typing.ClassVar['PumpApi610DesignCalculator.BearingType'] = ...
        SLEEVE: typing.ClassVar['PumpApi610DesignCalculator.BearingType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.BearingType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpApi610DesignCalculator.BearingType']: ...
    class Check(java.io.Serializable):
        def getActualValue(self) -> float: ...
        def getId(self) -> java.lang.String: ...
        def getLimitValue(self) -> float: ...
        def getMessage(self) -> java.lang.String: ...
        def getRequirement(self) -> java.lang.String: ...
        def getStatus(self) -> 'PumpApi610DesignCalculator.CheckStatus': ...
        def getUnit(self) -> java.lang.String: ...
    class CheckStatus(java.lang.Enum['PumpApi610DesignCalculator.CheckStatus']):
        PASS: typing.ClassVar['PumpApi610DesignCalculator.CheckStatus'] = ...
        WARNING: typing.ClassVar['PumpApi610DesignCalculator.CheckStatus'] = ...
        FAIL: typing.ClassVar['PumpApi610DesignCalculator.CheckStatus'] = ...
        NOT_EVALUATED: typing.ClassVar['PumpApi610DesignCalculator.CheckStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.CheckStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpApi610DesignCalculator.CheckStatus']: ...
    class DataSource(java.lang.Enum['PumpApi610DesignCalculator.DataSource']):
        PROCESS_MODEL: typing.ClassVar['PumpApi610DesignCalculator.DataSource'] = ...
        PURCHASER_INPUT: typing.ClassVar['PumpApi610DesignCalculator.DataSource'] = ...
        VENDOR_CURVE: typing.ClassVar['PumpApi610DesignCalculator.DataSource'] = ...
        SCREENING_ESTIMATE: typing.ClassVar['PumpApi610DesignCalculator.DataSource'] = ...
        NOT_AVAILABLE: typing.ClassVar['PumpApi610DesignCalculator.DataSource'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpApi610DesignCalculator.DataSource': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpApi610DesignCalculator.DataSource']: ...

class PumpHydraulicsNpshCalculator(java.io.Serializable):
    def __init__(self): ...
    def calcHydraulics(self) -> None: ...
    def fromPump(self, pump: jneqsim.process.equipment.pump.Pump) -> None: ...
    def getBrakePower(self) -> float: ...
    def getHydraulicPower(self) -> float: ...
    def getNpshAvailable(self) -> float: ...
    def getNpshMargin(self) -> float: ...
    def isCavitationRisk(self) -> bool: ...
    def setDutyPoint(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setSuctionConditions(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> None: ...
    def toJson(self) -> java.lang.String: ...

class PumpMechanicalDesign(jneqsim.process.mechanicaldesign.MechanicalDesign):
    def __init__(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface): ...
    def calcDesign(self) -> None: ...
    def displayResults(self) -> None: ...
    def getAbsorbedPower(self) -> float: ...
    def getAorHighFraction(self) -> float: ...
    def getAorLowFraction(self) -> float: ...
    def getApi610Assessment(self) -> PumpApi610DesignCalculator: ...
    def getApi610PumpType(self) -> PumpApi610DesignCalculator.Api610PumpType: ...
    def getBaseplateWeight(self) -> float: ...
    def getBepFlow(self) -> float: ...
    def getBepHead(self) -> float: ...
    def getCasingWallThickness(self) -> float: ...
    def getCasingWeight(self) -> float: ...
    def getDesignPressure(self) -> float: ...
    def getDesignTemperature(self) -> float: ...
    def getDischargeNozzleSize(self) -> float: ...
    def getDriverMargin(self) -> float: ...
    def getDriverPower(self) -> float: ...
    def getHeadMarginFactor(self) -> float: ...
    def getHydraulicPower(self) -> float: ...
    def getHydraulicPowerMargin(self) -> float: ...
    def getImpellerDiameter(self) -> float: ...
    def getImpellerWidth(self) -> float: ...
    def getMaxAllowableWorkingPressure(self) -> float: ...
    def getMaxSuctionSpecificSpeed(self) -> float: ...
    def getMaximumFlow(self) -> float: ...
    def getMinimumFlow(self) -> float: ...
    def getMinimumNpshMarginM(self) -> float: ...
    def getMotorWeight(self) -> float: ...
    def getNpshAvailable(self) -> float: ...
    def getNpshMargin(self) -> float: ...
    def getNpshMarginFactor(self) -> float: ...
    def getNpshMarginRatio(self) -> float: ...
    def getNpshRequired(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getPorHighFraction(self) -> float: ...
    def getPorLowFraction(self) -> float: ...
    def getPumpEfficiency(self) -> float: ...
    def getPumpType(self) -> 'PumpMechanicalDesign.PumpType': ...
    def getRatedFlow(self) -> float: ...
    def getRatedHead(self) -> float: ...
    def getRatedSpeed(self) -> float: ...
    def getResponse(self) -> 'PumpMechanicalDesignResponse': ...
    def getSealType(self) -> 'PumpMechanicalDesign.SealType': ...
    def getShaftDiameter(self) -> float: ...
    def getSpecificSpeed(self) -> float: ...
    def getSuctionNozzleSize(self) -> float: ...
    def getSuctionSpecificSpeed(self) -> float: ...
    def loadProcessDesignParameters(self) -> None: ...
    def readDesignSpecifications(self) -> None: ...
    def setAorHighFraction(self, double: float) -> None: ...
    def setAorLowFraction(self, double: float) -> None: ...
    def setApi610PumpType(self, api610PumpType: PumpApi610DesignCalculator.Api610PumpType) -> None: ...
    def setFurnishedCasingMawp(self, double: float) -> None: ...
    def setHeadMarginFactor(self, double: float) -> None: ...
    def setHydraulicPowerMargin(self, double: float) -> None: ...
    def setMaxSuctionSpecificSpeed(self, double: float) -> None: ...
    def setMaximumSuctionPressure(self, double: float) -> None: ...
    def setMinimumNpshMarginM(self, double: float) -> None: ...
    def setNpshMarginFactor(self, double: float) -> None: ...
    def setPorHighFraction(self, double: float) -> None: ...
    def setPorLowFraction(self, double: float) -> None: ...
    def setPumpType(self, pumpType: 'PumpMechanicalDesign.PumpType') -> None: ...
    def setSealType(self, sealType: 'PumpMechanicalDesign.SealType') -> None: ...
    def setShutoffHead(self, double: float) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def validateDesign(self) -> 'PumpMechanicalDesign.PumpValidationResult': ...
    def validateNpshMargin(self, double: float, double2: float) -> bool: ...
    def validateOperatingInAOR(self, double: float, double2: float) -> bool: ...
    def validateOperatingInPOR(self, double: float, double2: float) -> bool: ...
    def validateSuctionSpecificSpeed(self, double: float) -> bool: ...
    class PumpType(java.lang.Enum['PumpMechanicalDesign.PumpType']):
        OVERHUNG: typing.ClassVar['PumpMechanicalDesign.PumpType'] = ...
        BETWEEN_BEARINGS: typing.ClassVar['PumpMechanicalDesign.PumpType'] = ...
        VERTICALLY_SUSPENDED: typing.ClassVar['PumpMechanicalDesign.PumpType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpMechanicalDesign.PumpType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpMechanicalDesign.PumpType']: ...
    class PumpValidationResult:
        def __init__(self): ...
        def addIssue(self, string: typing.Union[java.lang.String, str]) -> None: ...
        def getIssues(self) -> java.util.List[java.lang.String]: ...
        def isValid(self) -> bool: ...
        def setValid(self, boolean: bool) -> None: ...
    class SealType(java.lang.Enum['PumpMechanicalDesign.SealType']):
        PACKED: typing.ClassVar['PumpMechanicalDesign.SealType'] = ...
        SINGLE_MECHANICAL: typing.ClassVar['PumpMechanicalDesign.SealType'] = ...
        DOUBLE_MECHANICAL: typing.ClassVar['PumpMechanicalDesign.SealType'] = ...
        MAGNETIC_DRIVE: typing.ClassVar['PumpMechanicalDesign.SealType'] = ...
        CANNED_MOTOR: typing.ClassVar['PumpMechanicalDesign.SealType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PumpMechanicalDesign.SealType': ...
        @staticmethod
        def values() -> typing.MutableSequence['PumpMechanicalDesign.SealType']: ...

class PumpMechanicalDesignResponse(jneqsim.process.mechanicaldesign.MechanicalDesignResponse):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pumpMechanicalDesign: PumpMechanicalDesign): ...
    def getAbsorbedPower(self) -> float: ...
    def getAorHighFraction(self) -> float: ...
    def getAorLowFraction(self) -> float: ...
    def getApi610Screening(self) -> PumpApi610DesignCalculator: ...
    def getApi610TypeCode(self) -> java.lang.String: ...
    def getBepFlow(self) -> float: ...
    def getBepHead(self) -> float: ...
    def getCasingWallThickness(self) -> float: ...
    def getDifferentialPressure(self) -> float: ...
    def getDischargeNozzleSize(self) -> float: ...
    def getDischargePressure(self) -> float: ...
    def getDriverMargin(self) -> float: ...
    def getDriverPower(self) -> float: ...
    def getEfficiency(self) -> float: ...
    def getFluidDensity(self) -> float: ...
    def getFluidTemperature(self) -> float: ...
    def getFluidViscosity(self) -> float: ...
    def getHeadMarginFactor(self) -> float: ...
    def getHydraulicPower(self) -> float: ...
    def getHydraulicPowerMargin(self) -> float: ...
    def getImpellerDiameter(self) -> float: ...
    def getImpellerWidth(self) -> float: ...
    def getMaxSuctionSpecificSpeed(self) -> float: ...
    def getMinimumContinuousFlow(self) -> float: ...
    def getNpshMargin(self) -> float: ...
    def getNpshMarginFactor(self) -> float: ...
    def getNpshMarginRatio(self) -> float: ...
    def getNpsha(self) -> float: ...
    def getNpshr(self) -> float: ...
    def getNumberOfStages(self) -> int: ...
    def getPorHighFraction(self) -> float: ...
    def getPorLowFraction(self) -> float: ...
    def getPumpType(self) -> java.lang.String: ...
    def getRatedFlow(self) -> float: ...
    def getRatedHead(self) -> float: ...
    def getRatedSpeed(self) -> float: ...
    def getSealType(self) -> java.lang.String: ...
    def getShaftDiameter(self) -> float: ...
    def getSpecificSpeed(self) -> float: ...
    def getSuctionNozzleSize(self) -> float: ...
    def getSuctionPressure(self) -> float: ...
    def getSuctionSpecificSpeed(self) -> float: ...
    def populateFromPumpDesign(self, pumpMechanicalDesign: PumpMechanicalDesign) -> None: ...
    def setAbsorbedPower(self, double: float) -> None: ...
    def setAorHighFraction(self, double: float) -> None: ...
    def setAorLowFraction(self, double: float) -> None: ...
    def setApi610Screening(self, pumpApi610DesignCalculator: PumpApi610DesignCalculator) -> None: ...
    def setApi610TypeCode(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setBepFlow(self, double: float) -> None: ...
    def setBepHead(self, double: float) -> None: ...
    def setCasingWallThickness(self, double: float) -> None: ...
    def setDifferentialPressure(self, double: float) -> None: ...
    def setDischargeNozzleSize(self, double: float) -> None: ...
    def setDischargePressure(self, double: float) -> None: ...
    def setDriverMargin(self, double: float) -> None: ...
    def setDriverPower(self, double: float) -> None: ...
    def setEfficiency(self, double: float) -> None: ...
    def setFluidDensity(self, double: float) -> None: ...
    def setFluidTemperature(self, double: float) -> None: ...
    def setFluidViscosity(self, double: float) -> None: ...
    def setHeadMarginFactor(self, double: float) -> None: ...
    def setHydraulicPower(self, double: float) -> None: ...
    def setHydraulicPowerMargin(self, double: float) -> None: ...
    def setImpellerDiameter(self, double: float) -> None: ...
    def setImpellerWidth(self, double: float) -> None: ...
    def setMaxSuctionSpecificSpeed(self, double: float) -> None: ...
    def setMinimumContinuousFlow(self, double: float) -> None: ...
    def setNpshMargin(self, double: float) -> None: ...
    def setNpshMarginFactor(self, double: float) -> None: ...
    def setNpshMarginRatio(self, double: float) -> None: ...
    def setNpsha(self, double: float) -> None: ...
    def setNpshr(self, double: float) -> None: ...
    def setNumberOfStages(self, int: int) -> None: ...
    def setPorHighFraction(self, double: float) -> None: ...
    def setPorLowFraction(self, double: float) -> None: ...
    def setPumpType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setRatedFlow(self, double: float) -> None: ...
    def setRatedHead(self, double: float) -> None: ...
    def setRatedSpeed(self, double: float) -> None: ...
    def setSealType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setShaftDiameter(self, double: float) -> None: ...
    def setSpecificSpeed(self, double: float) -> None: ...
    def setSuctionNozzleSize(self, double: float) -> None: ...
    def setSuctionPressure(self, double: float) -> None: ...
    def setSuctionSpecificSpeed(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.pump")``.

    PumpApi610DesignCalculator: typing.Type[PumpApi610DesignCalculator]
    PumpHydraulicsNpshCalculator: typing.Type[PumpHydraulicsNpshCalculator]
    PumpMechanicalDesign: typing.Type[PumpMechanicalDesign]
    PumpMechanicalDesignResponse: typing.Type[PumpMechanicalDesignResponse]
