
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering
import jneqsim.process.engineering.deliverables
import jneqsim.process.engineering.designcase
import jneqsim.process.engineering.model
import jneqsim.process.engineering.production
import jneqsim.process.safety.scenario
import typing



class InletCompressionExportReferenceFacility:
    FEED: typing.ClassVar[java.lang.String] = ...
    SEPARATOR: typing.ClassVar[java.lang.String] = ...
    SUCTION_ESD: typing.ClassVar[java.lang.String] = ...
    COMPRESSOR: typing.ClassVar[java.lang.String] = ...
    COOLER: typing.ClassVar[java.lang.String] = ...
    DISCHARGE_ESD: typing.ClassVar[java.lang.String] = ...
    PCV: typing.ClassVar[java.lang.String] = ...
    EXPORT_LINE: typing.ClassVar[java.lang.String] = ...
    ASV: typing.ClassVar[java.lang.String] = ...
    ASV_RECYCLE: typing.ClassVar[java.lang.String] = ...
    LCV: typing.ClassVar[java.lang.String] = ...
    PSV: typing.ClassVar[java.lang.String] = ...
    BDV: typing.ClassVar[java.lang.String] = ...
    FLARE_CONNECTION: typing.ClassVar[java.lang.String] = ...
    DYNAMIC_SCENARIO: typing.ClassVar[java.lang.String] = ...
    DESIGN_BASIS_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    HAZOP_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    MAP_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    SRS_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    RELIEF_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    MATERIALS_EVIDENCE: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def build() -> 'InletCompressionExportReferenceFacility.Definition': ...
    class Definition(java.io.Serializable):
        def getAutoConfigurationPolicy(self) -> jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy: ...
        def getProject(self) -> jneqsim.process.engineering.EngineeringProject: ...
        def getQualificationPolicy(self) -> 'InletCompressionExportSlicePolicy': ...

class InletCompressionExportSlicePolicy(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...
    def getBlowdownValveTag(self) -> java.lang.String: ...
    def getCompressorTag(self) -> java.lang.String: ...
    def getCoolerTag(self) -> java.lang.String: ...
    def getDischargeEsdValveTag(self) -> java.lang.String: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getExportLineTag(self) -> java.lang.String: ...
    def getFlareConnectionTag(self) -> java.lang.String: ...
    def getLevelControlValveTag(self) -> java.lang.String: ...
    def getPolicyId(self) -> java.lang.String: ...
    def getPressureControlValveTag(self) -> java.lang.String: ...
    def getRecycleUnitTag(self) -> java.lang.String: ...
    def getRecycleValveTag(self) -> java.lang.String: ...
    def getReliefValveTag(self) -> java.lang.String: ...
    def getRequiredCaseTypes(self) -> java.util.Set[jneqsim.process.engineering.designcase.EngineeringDesignCase.Type]: ...
    def getRequiredDynamicScenarioIds(self) -> java.util.Set[java.lang.String]: ...
    def getRequiredStandards(self) -> java.util.Set[java.lang.String]: ...
    def getRevision(self) -> java.lang.String: ...
    def getSeparatorTag(self) -> java.lang.String: ...
    def getSuctionEsdValveTag(self) -> java.lang.String: ...
    def isCoupledReliefBlowdownFlareRequired(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...
        def addRequiredDynamicScenario(self, string: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...
        def build(self) -> 'InletCompressionExportSlicePolicy': ...
        def controlTags(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...
        def coupledReliefBlowdownFlareRequired(self, boolean: bool) -> 'InletCompressionExportSlicePolicy.Builder': ...
        def processTags(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...
        def safetyTags(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]) -> 'InletCompressionExportSlicePolicy.Builder': ...

class InletCompressionExportSliceQualification:
    @staticmethod
    def qualify(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringSimulationResult: jneqsim.process.engineering.EngineeringSimulationResult, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy) -> 'InletCompressionExportSliceQualification.Result': ...
    class Result(java.io.Serializable):
        def getFailedGates(self) -> java.util.List[java.lang.String]: ...
        def isQualifiedForControlledPilot(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ProductionVerticalSliceExecutionManifest(java.io.Serializable):
    @staticmethod
    def build(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, result: 'ProductionVerticalSlicePreflight.Result') -> 'ProductionVerticalSliceExecutionManifest': ...
    def getInputFingerprint(self) -> java.lang.String: ...
    def isPreflightReady(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ProductionVerticalSlicePreflight:
    @staticmethod
    def assess(engineeringProject: jneqsim.process.engineering.EngineeringProject, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy) -> 'ProductionVerticalSlicePreflight.Result': ...
    class Check(java.io.Serializable):
        def getBlockers(self) -> java.util.List[java.lang.String]: ...
        def getWarnings(self) -> java.util.List[java.lang.String]: ...
        def isPassed(self) -> bool: ...
    class Result(java.io.Serializable):
        def getBlockers(self) -> java.util.List[java.lang.String]: ...
        def getFailedChecks(self) -> java.util.List[java.lang.String]: ...
        def isReadyForSimulation(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ProductionVerticalSliceSimulator:
    @staticmethod
    def run(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, int: int) -> 'ProductionVerticalSliceSimulator.Result': ...
    @staticmethod
    def runAndCompile(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, int: int, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph) -> 'ProductionVerticalSliceSimulator.Result': ...
    @staticmethod
    def runStrict(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, int: int) -> 'ProductionVerticalSliceSimulator.Result': ...
    @staticmethod
    def runStrictAndCompile(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, int: int, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph) -> 'ProductionVerticalSliceSimulator.Result': ...
    class Result:
        def getCompilation(self) -> jneqsim.process.engineering.deliverables.EngineeringDeliverableCompiler.CompilationResult: ...
        def getManifest(self) -> ProductionVerticalSliceExecutionManifest: ...
        def getPreflight(self) -> ProductionVerticalSlicePreflight.Result: ...
        def getQualification(self) -> InletCompressionExportSliceQualification.Result: ...
        def getSimulation(self) -> jneqsim.process.engineering.EngineeringSimulationResult: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class VerticalSliceCaseMatrixFactory:
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'VerticalSliceCaseMatrixFactory.Builder': ...
    class Builder:
        def addCase(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], type: jneqsim.process.engineering.designcase.EngineeringDesignCase.Type, double: float, double2: float, double3: float, double4: float, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'VerticalSliceCaseMatrixFactory.Builder': ...
        def applyTo(self, engineeringProject: jneqsim.process.engineering.EngineeringProject, inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy) -> jneqsim.process.engineering.EngineeringProject: ...

class VerticalSliceDynamicScenarioFactory:
    @staticmethod
    def emergencyShutdown(string: typing.Union[java.lang.String, str], inletCompressionExportSlicePolicy: InletCompressionExportSlicePolicy, double: float, double2: float, double3: float, double4: float, double5: float, string2: typing.Union[java.lang.String, str]) -> jneqsim.process.safety.scenario.DynamicSafetyScenario: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.verticalslice")``.

    InletCompressionExportReferenceFacility: typing.Type[InletCompressionExportReferenceFacility]
    InletCompressionExportSlicePolicy: typing.Type[InletCompressionExportSlicePolicy]
    InletCompressionExportSliceQualification: typing.Type[InletCompressionExportSliceQualification]
    ProductionVerticalSliceExecutionManifest: typing.Type[ProductionVerticalSliceExecutionManifest]
    ProductionVerticalSlicePreflight: typing.Type[ProductionVerticalSlicePreflight]
    ProductionVerticalSliceSimulator: typing.Type[ProductionVerticalSliceSimulator]
    VerticalSliceCaseMatrixFactory: typing.Type[VerticalSliceCaseMatrixFactory]
    VerticalSliceDynamicScenarioFactory: typing.Type[VerticalSliceDynamicScenarioFactory]
