
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering.model
import typing



class EngineeringPackageValidationException(java.io.IOException):
    def __init__(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], engineeringPackageValidationReport: 'EngineeringPackageValidationReport'): ...
    def getValidationReport(self) -> 'EngineeringPackageValidationReport': ...
    def getValidationReportFile(self) -> java.nio.file.Path: ...

class EngineeringPackageValidationReport(java.io.Serializable):
    def __init__(self): ...
    def addAll(self, engineeringPackageValidationReport: 'EngineeringPackageValidationReport') -> None: ...
    def addError(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    def addWarning(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> None: ...
    def getErrorCount(self) -> int: ...
    def getFindings(self) -> java.util.List['EngineeringPackageValidationReport.Finding']: ...
    def getWarningCount(self) -> int: ...
    def isValid(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Finding(java.io.Serializable):
        def getArtifact(self) -> java.lang.String: ...
        def getCode(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getPath(self) -> java.lang.String: ...
        def getSeverity(self) -> 'EngineeringPackageValidationReport.Severity': ...
    class Severity(java.lang.Enum['EngineeringPackageValidationReport.Severity']):
        ERROR: typing.ClassVar['EngineeringPackageValidationReport.Severity'] = ...
        WARNING: typing.ClassVar['EngineeringPackageValidationReport.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringPackageValidationReport.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringPackageValidationReport.Severity']: ...

class EngineeringPackageValidator:
    @staticmethod
    def validateArtifact(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> EngineeringPackageValidationReport: ...
    @staticmethod
    def validateGraph(engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph) -> EngineeringPackageValidationReport: ...
    @staticmethod
    def validatePackage(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> EngineeringPackageValidationReport: ...

class EngineeringSchemaCatalog:
    CATALOG_VERSION: typing.ClassVar[java.lang.String] = ...
    GRAPH: typing.ClassVar[java.lang.String] = ...
    CONNECTIVITY: typing.ClassVar[java.lang.String] = ...
    CALCULATION_DAG: typing.ClassVar[java.lang.String] = ...
    DESIGN_CASE_MATRIX: typing.ClassVar[java.lang.String] = ...
    DISCIPLINE_PACKAGE: typing.ClassVar[java.lang.String] = ...
    APPROVAL_LEDGER: typing.ClassVar[java.lang.String] = ...
    DEXPI_ROUNDTRIP_REPORT: typing.ClassVar[java.lang.String] = ...
    AUTOMATION_PLAN: typing.ClassVar[java.lang.String] = ...
    DESIGN_CASE_ENVELOPE: typing.ClassVar[java.lang.String] = ...
    EQUIPMENT_REGISTER: typing.ClassVar[java.lang.String] = ...
    LINE_REGISTER: typing.ClassVar[java.lang.String] = ...
    INSTRUMENT_REGISTER: typing.ClassVar[java.lang.String] = ...
    COMPILER_MANIFEST: typing.ClassVar[java.lang.String] = ...
    REVISION_DIFF: typing.ClassVar[java.lang.String] = ...
    VALIDATION_REPORT: typing.ClassVar[java.lang.String] = ...
    PRODUCTION_READINESS: typing.ClassVar[java.lang.String] = ...
    NUMERICAL_HEALTH: typing.ClassVar[java.lang.String] = ...
    QUALIFICATION_PLAN: typing.ClassVar[java.lang.String] = ...
    EXTERNAL_EVIDENCE_REGISTER: typing.ClassVar[java.lang.String] = ...
    DISCIPLINE_ORCHESTRATION: typing.ClassVar[java.lang.String] = ...
    VERTICAL_SLICE_QUALIFICATION: typing.ClassVar[java.lang.String] = ...
    VERTICAL_SLICE_EXECUTION_MANIFEST: typing.ClassVar[java.lang.String] = ...
    MODEL_PACKAGE: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def forArtifact(string: typing.Union[java.lang.String, str]) -> 'EngineeringSchemaCatalog.Definition': ...
    @staticmethod
    def forVersion(string: typing.Union[java.lang.String, str]) -> 'EngineeringSchemaCatalog.Definition': ...
    @staticmethod
    def getDefinitions() -> java.util.List['EngineeringSchemaCatalog.Definition']: ...
    @staticmethod
    def manifestEntries() -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    @staticmethod
    def schemaUri(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    @staticmethod
    def writeSchemas(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> java.util.List[java.lang.String]: ...
    class Definition:
        def getArtifactName(self) -> java.lang.String: ...
        def getSchemaFile(self) -> java.lang.String: ...
        def getSchemaUri(self) -> java.lang.String: ...
        def getSchemaVersion(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringTopologyValidator:
    @staticmethod
    def validate(engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph) -> EngineeringPackageValidationReport: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.validation")``.

    EngineeringPackageValidationException: typing.Type[EngineeringPackageValidationException]
    EngineeringPackageValidationReport: typing.Type[EngineeringPackageValidationReport]
    EngineeringPackageValidator: typing.Type[EngineeringPackageValidator]
    EngineeringSchemaCatalog: typing.Type[EngineeringSchemaCatalog]
    EngineeringTopologyValidator: typing.Type[EngineeringTopologyValidator]
