
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import com.google.gson
import java.io
import java.lang
import java.util
import jneqsim.process.engineering.automation
import jneqsim.process.engineering.calculation
import jneqsim.process.engineering.deliverables
import jneqsim.process.engineering.design
import jneqsim.process.engineering.design.modules
import jneqsim.process.engineering.designcase
import jneqsim.process.engineering.dexpi
import jneqsim.process.engineering.handover
import jneqsim.process.engineering.impact
import jneqsim.process.engineering.instrumentation
import jneqsim.process.engineering.mechanical
import jneqsim.process.engineering.model
import jneqsim.process.engineering.numerics
import jneqsim.process.engineering.pid
import jneqsim.process.engineering.piping
import jneqsim.process.engineering.production
import jneqsim.process.engineering.rotating
import jneqsim.process.engineering.safety
import jneqsim.process.engineering.validation
import jneqsim.process.engineering.verticalslice
import jneqsim.process.equipment
import jneqsim.process.materials
import jneqsim.process.processmodel
import jneqsim.process.safety.depressurization
import jneqsim.process.safety.esd
import jneqsim.process.safety.overpressure
import jneqsim.process.safety.scenario
import typing



class EngineeringApprovalRecord(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], status: 'EngineeringApprovalRecord.Status', string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str]): ...
    def getDiscipline(self) -> java.lang.String: ...
    def getEffectiveDate(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getReviewReference(self) -> java.lang.String: ...
    def getReviewer(self) -> java.lang.String: ...
    def getStatus(self) -> 'EngineeringApprovalRecord.Status': ...
    def getSubjectNodeId(self) -> java.lang.String: ...
    def getSupersedesRecordId(self) -> java.lang.String: ...
    def supersedes(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringApprovalRecord': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Status(java.lang.Enum['EngineeringApprovalRecord.Status']):
        REVIEW_REQUIRED: typing.ClassVar['EngineeringApprovalRecord.Status'] = ...
        APPROVED: typing.ClassVar['EngineeringApprovalRecord.Status'] = ...
        REJECTED: typing.ClassVar['EngineeringApprovalRecord.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringApprovalRecord.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringApprovalRecord.Status']: ...

class EngineeringApprovalStatus(java.lang.Enum['EngineeringApprovalStatus']):
    PROPOSED: typing.ClassVar['EngineeringApprovalStatus'] = ...
    REVIEW_REQUIRED: typing.ClassVar['EngineeringApprovalStatus'] = ...
    APPROVED: typing.ClassVar['EngineeringApprovalStatus'] = ...
    REJECTED: typing.ClassVar['EngineeringApprovalStatus'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringApprovalStatus': ...
    @staticmethod
    def values() -> typing.MutableSequence['EngineeringApprovalStatus']: ...

class EngineeringBoundary(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], type: 'EngineeringBoundary.Type'): ...
    def getConnectedDocumentReference(self) -> java.lang.String: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getEvidenceReference(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getType(self) -> 'EngineeringBoundary.Type': ...
    def isResolved(self) -> bool: ...
    def resolve(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringBoundary': ...
    class Type(java.lang.Enum['EngineeringBoundary.Type']):
        PROCESS_INLET: typing.ClassVar['EngineeringBoundary.Type'] = ...
        PROCESS_OUTLET: typing.ClassVar['EngineeringBoundary.Type'] = ...
        FLARE_HEADER: typing.ClassVar['EngineeringBoundary.Type'] = ...
        VENT_HEADER: typing.ClassVar['EngineeringBoundary.Type'] = ...
        CLOSED_DRAIN: typing.ClassVar['EngineeringBoundary.Type'] = ...
        UTILITY_INLET: typing.ClassVar['EngineeringBoundary.Type'] = ...
        UTILITY_OUTLET: typing.ClassVar['EngineeringBoundary.Type'] = ...
        RECYCLE_TIE_IN: typing.ClassVar['EngineeringBoundary.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringBoundary.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringBoundary.Type']: ...

class EngineeringCoverageMatrix:
    @staticmethod
    def evaluate(engineeringProject: 'EngineeringProject') -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignBasis(java.io.Serializable):
    def __init__(self): ...
    def addDesignCase(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignBasis': ...
    def addStandard(self, engineeringStandard: 'EngineeringStandard') -> 'EngineeringDesignBasis': ...
    def getDesignCases(self) -> java.util.List[java.lang.String]: ...
    def getFacilityType(self) -> java.lang.String: ...
    def getJurisdiction(self) -> java.lang.String: ...
    def getProjectPhase(self) -> java.lang.String: ...
    def getStandards(self) -> java.util.List['EngineeringStandard']: ...
    def setFacilityType(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignBasis': ...
    def setJurisdiction(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignBasis': ...
    def setProjectPhase(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignBasis': ...

class EngineeringEvidenceRecord(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def approve(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def getApprovalStatus(self) -> EngineeringApprovalStatus: ...
    def getDocumentId(self) -> java.lang.String: ...
    def getDocumentType(self) -> java.lang.String: ...
    def getEquipmentTags(self) -> java.util.List[java.lang.String]: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getRequirementIds(self) -> java.util.List[java.lang.String]: ...
    def getRevision(self) -> java.lang.String: ...
    def linkEquipment(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def linkRequirement(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def setChecksum(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def setSourceOrganization(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def setTitle(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringEvidenceRecord': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringOrigin(java.lang.Enum['EngineeringOrigin']):
    USER_SPECIFIED: typing.ClassVar['EngineeringOrigin'] = ...
    SIMULATION_CALCULATED: typing.ClassVar['EngineeringOrigin'] = ...
    RULE_INFERRED: typing.ClassVar['EngineeringOrigin'] = ...
    DATABASE_SELECTED: typing.ClassVar['EngineeringOrigin'] = ...
    VENDOR_SUPPLIED: typing.ClassVar['EngineeringOrigin'] = ...
    ENGINEER_APPROVED: typing.ClassVar['EngineeringOrigin'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringOrigin': ...
    @staticmethod
    def values() -> typing.MutableSequence['EngineeringOrigin']: ...

class EngineeringProject(java.io.Serializable):
    def addApprovalRecord(self, engineeringApprovalRecord: EngineeringApprovalRecord) -> 'EngineeringProject': ...
    def addAutomationStudy(self, engineeringAutomationStudy: jneqsim.process.engineering.automation.EngineeringAutomationStudy) -> 'EngineeringProject': ...
    def addBlowdownFlareStudy(self, dynamicBlowdownFlareStudyDataSource: jneqsim.process.safety.depressurization.DynamicBlowdownFlareStudyDataSource) -> 'EngineeringProject': ...
    def addBoundary(self, engineeringBoundary: EngineeringBoundary) -> 'EngineeringProject': ...
    def addCalculation(self, engineeringCalculation: jneqsim.process.engineering.model.EngineeringCalculation) -> 'EngineeringProject': ...
    def addCoupledReliefBlowdownFlareStudy(self, coupledReliefBlowdownFlareInput: jneqsim.process.safety.depressurization.CoupledReliefBlowdownFlareInput) -> 'EngineeringProject': ...
    def addDesignCase(self, engineeringDesignCase: jneqsim.process.engineering.designcase.EngineeringDesignCase) -> 'EngineeringProject': ...
    def addDynamicSafetyScenario(self, dynamicSafetyScenario: jneqsim.process.safety.scenario.DynamicSafetyScenario) -> 'EngineeringProject': ...
    def addEngineeringDesignModule(self, engineeringDesignModule: jneqsim.process.engineering.design.EngineeringDesignModule) -> 'EngineeringProject': ...
    def addEngineeringMetric(self, engineeringMetric: jneqsim.process.engineering.designcase.EngineeringMetric) -> 'EngineeringProject': ...
    def addEvidenceRecord(self, engineeringEvidenceRecord: EngineeringEvidenceRecord) -> 'EngineeringProject': ...
    def addLineDesignInput(self, lineDesignInput: 'LineDesignInput') -> 'EngineeringProject': ...
    def addOverpressureStudy(self, overpressureProtectionStudy: jneqsim.process.safety.overpressure.OverpressureProtectionStudy) -> 'EngineeringProject': ...
    def addReliefDeviceDesignInput(self, reliefDeviceDesignInput: 'ReliefDeviceDesignInput') -> 'EngineeringProject': ...
    def addReliefScenarioBasis(self, reliefScenarioBasis: 'ReliefScenarioBasis') -> 'EngineeringProject': ...
    def addRequirement(self, engineeringRequirement: 'EngineeringRequirement') -> None: ...
    def addSafetyFunctionDesign(self, safetyFunctionDesign: 'SafetyFunctionDesign') -> 'EngineeringProject': ...
    def addShutdownSequence(self, shutdownSequence: 'ShutdownSequence') -> 'EngineeringProject': ...
    def addShutdownVerificationResult(self, string: typing.Union[java.lang.String, str], emergencyShutdownTestResult: jneqsim.process.safety.esd.EmergencyShutdownTestResult) -> 'EngineeringProject': ...
    def getApprovalRecords(self) -> java.util.List[EngineeringApprovalRecord]: ...
    def getAutomationStudies(self) -> java.util.List[jneqsim.process.engineering.automation.EngineeringAutomationStudy]: ...
    def getBlowdownFlareStudies(self) -> java.util.List[jneqsim.process.safety.depressurization.DynamicBlowdownFlareStudyDataSource]: ...
    def getBoundaries(self) -> java.util.List[EngineeringBoundary]: ...
    def getCalculations(self) -> java.util.List[jneqsim.process.engineering.model.EngineeringCalculation]: ...
    def getCoupledReliefBlowdownFlareStudies(self) -> java.util.List[jneqsim.process.safety.depressurization.CoupledReliefBlowdownFlareInput]: ...
    def getDesignBasis(self) -> EngineeringDesignBasis: ...
    def getDynamicSafetyScenarios(self) -> java.util.List[jneqsim.process.safety.scenario.DynamicSafetyScenario]: ...
    def getEngineeringDesignModules(self) -> java.util.List[jneqsim.process.engineering.design.EngineeringDesignModule]: ...
    def getEngineeringMetrics(self) -> java.util.List[jneqsim.process.engineering.designcase.EngineeringMetric]: ...
    def getEngineeringProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getEvidenceRecords(self) -> java.util.List[EngineeringEvidenceRecord]: ...
    def getExecutableDesignCases(self) -> java.util.List[jneqsim.process.engineering.designcase.EngineeringDesignCase]: ...
    def getLatestEngineeringDesignLoopResult(self) -> jneqsim.process.engineering.design.EngineeringDesignLoopResult: ...
    def getLatestVerticalSliceExecutionManifest(self) -> jneqsim.process.engineering.verticalslice.ProductionVerticalSliceExecutionManifest: ...
    def getLatestVerticalSliceQualification(self) -> jneqsim.process.engineering.verticalslice.InletCompressionExportSliceQualification.Result: ...
    def getLineDesignInputs(self) -> java.util.List['LineDesignInput']: ...
    def getMaterialsReviewInput(self) -> jneqsim.process.materials.MaterialsReviewInput: ...
    def getName(self) -> java.lang.String: ...
    def getOverpressureStudies(self) -> java.util.List[jneqsim.process.safety.overpressure.OverpressureProtectionStudy]: ...
    def getProcessSystem(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProductionReadinessBasis(self) -> jneqsim.process.engineering.production.EngineeringProductionReadinessBasis: ...
    def getProjectId(self) -> java.lang.String: ...
    def getReliefDeviceDesignInputs(self) -> java.util.List['ReliefDeviceDesignInput']: ...
    def getReliefScenarioBases(self) -> java.util.List['ReliefScenarioBasis']: ...
    def getRequirements(self) -> java.util.List['EngineeringRequirement']: ...
    def getRequirementsForEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List['EngineeringRequirement']: ...
    def getRevision(self) -> java.lang.String: ...
    def getSafetyFunctionDesigns(self) -> java.util.List['SafetyFunctionDesign']: ...
    def getShutdownSequences(self) -> java.util.List['ShutdownSequence']: ...
    def getShutdownVerificationResults(self) -> java.util.Map[java.lang.String, jneqsim.process.safety.esd.EmergencyShutdownTestResult]: ...
    def recordVerticalSliceExecutionManifest(self, productionVerticalSliceExecutionManifest: jneqsim.process.engineering.verticalslice.ProductionVerticalSliceExecutionManifest) -> None: ...
    def recordVerticalSliceQualification(self, result: jneqsim.process.engineering.verticalslice.InletCompressionExportSliceQualification.Result) -> None: ...
    def setMaterialsReviewInput(self, materialsReviewInput: jneqsim.process.materials.MaterialsReviewInput) -> 'EngineeringProject': ...
    def setProductionReadinessBasis(self, engineeringProductionReadinessBasis: jneqsim.process.engineering.production.EngineeringProductionReadinessBasis) -> 'EngineeringProject': ...
    def setRevision(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringProject': ...
    def toJson(self) -> java.lang.String: ...
    def validate(self) -> 'EngineeringValidationReport': ...

class EngineeringRequirement(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], type: 'EngineeringRequirement.Type', string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def addStandardReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringRequirement': ...
    def approve(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringRequirement': ...
    def getApprovalStatus(self) -> EngineeringApprovalStatus: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getOrigin(self) -> EngineeringOrigin: ...
    def getRationale(self) -> java.lang.String: ...
    def getReviewRecord(self) -> java.lang.String: ...
    def getSilTarget(self) -> java.lang.String: ...
    def getStandardReferences(self) -> java.util.List[java.lang.String]: ...
    def getTitle(self) -> java.lang.String: ...
    def getType(self) -> 'EngineeringRequirement.Type': ...
    def setSilTarget(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringRequirement': ...
    class Type(java.lang.Enum['EngineeringRequirement.Type']):
        CONTROL: typing.ClassVar['EngineeringRequirement.Type'] = ...
        INSTRUMENT: typing.ClassVar['EngineeringRequirement.Type'] = ...
        ALARM: typing.ClassVar['EngineeringRequirement.Type'] = ...
        TRIP: typing.ClassVar['EngineeringRequirement.Type'] = ...
        RELIEF: typing.ClassVar['EngineeringRequirement.Type'] = ...
        MECHANICAL_PROTECTION: typing.ClassVar['EngineeringRequirement.Type'] = ...
        FIRE_AND_GAS: typing.ClassVar['EngineeringRequirement.Type'] = ...
        ENGINEERING_ASSESSMENT: typing.ClassVar['EngineeringRequirement.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringRequirement.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringRequirement.Type']: ...

class EngineeringRule:
    def apply(self, engineeringProject: EngineeringProject, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class EngineeringSimulationResult(java.io.Serializable):
    def getCaseRunReport(self) -> jneqsim.process.engineering.designcase.EngineeringCaseRunReport: ...
    def getCoupledSafetyResults(self) -> java.util.List[jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.safety.depressurization.CoupledReliefBlowdownFlareResult]]: ...
    def getDynamicScenarioResults(self) -> java.util.List[jneqsim.process.safety.scenario.DynamicSafetyScenarioResult]: ...
    def getEngineeringDesignLoopResult(self) -> jneqsim.process.engineering.design.EngineeringDesignLoopResult: ...
    def hasFailedDynamicScenario(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringSimulationRunner:
    @staticmethod
    def buildCaseSet(engineeringProject: EngineeringProject) -> jneqsim.process.engineering.designcase.EngineeringCaseSet: ...
    @staticmethod
    def run(engineeringProject: EngineeringProject, engineeringCaseRunOptions: jneqsim.process.engineering.designcase.EngineeringCaseRunOptions) -> EngineeringSimulationResult: ...

class EngineeringStandard(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getApplication(self) -> java.lang.String: ...
    def getCode(self) -> java.lang.String: ...
    def getEdition(self) -> java.lang.String: ...
    def getReference(self) -> java.lang.String: ...
    def getTitle(self) -> java.lang.String: ...

class EngineeringValidationReport(java.io.Serializable):
    def __init__(self): ...
    def add(self, severity: 'EngineeringValidationReport.Severity', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> None: ...
    def count(self, severity: 'EngineeringValidationReport.Severity') -> int: ...
    def getFindings(self) -> java.util.List['EngineeringValidationReport.Finding']: ...
    def hasErrors(self) -> bool: ...
    class Finding(java.io.Serializable):
        def getCode(self) -> java.lang.String: ...
        def getEquipmentTag(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getSeverity(self) -> 'EngineeringValidationReport.Severity': ...
    class Severity(java.lang.Enum['EngineeringValidationReport.Severity']):
        ERROR: typing.ClassVar['EngineeringValidationReport.Severity'] = ...
        WARNING: typing.ClassVar['EngineeringValidationReport.Severity'] = ...
        REVIEW: typing.ClassVar['EngineeringValidationReport.Severity'] = ...
        INFORMATION: typing.ClassVar['EngineeringValidationReport.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringValidationReport.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringValidationReport.Severity']: ...

class LineDesignInput(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def getCorrosionAllowanceM(self) -> float: ...
    def getDesignPressureBara(self) -> float: ...
    def getDesignTemperatureC(self) -> float: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getEquivalentFittingsLengthM(self) -> float: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getInstallationTemperatureC(self) -> float: ...
    def getInsulationType(self) -> java.lang.String: ...
    def getLineTag(self) -> java.lang.String: ...
    def getMaterialGrade(self) -> java.lang.String: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getNominalPipeSize(self) -> java.lang.String: ...
    def getNominalWallThicknessM(self) -> float: ...
    def getOuterDiameterM(self) -> float: ...
    def getPipingClass(self) -> java.lang.String: ...
    def getProposedSupportSpacingM(self) -> float: ...
    def getSchedule(self) -> java.lang.String: ...
    def setCorrosionAllowance(self, double: float, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setDesignPressureBara(self, double: float) -> 'LineDesignInput': ...
    def setDesignTemperatureC(self, double: float) -> 'LineDesignInput': ...
    def setEquivalentFittingsLengthM(self, double: float) -> 'LineDesignInput': ...
    def setInstallationTemperatureC(self, double: float) -> 'LineDesignInput': ...
    def setInsulationType(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setMaterialGrade(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setNominalPipeSize(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setNominalWallThickness(self, double: float, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setOuterDiameter(self, double: float, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setPipingClass(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def setProposedSupportSpacingM(self, double: float) -> 'LineDesignInput': ...
    def setSchedule(self, string: typing.Union[java.lang.String, str]) -> 'LineDesignInput': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class NorsokOffshoreEngineeringBuilder:
    def addRule(self, engineeringRule: EngineeringRule) -> 'NorsokOffshoreEngineeringBuilder': ...
    def build(self) -> EngineeringProject: ...
    @staticmethod
    def fromProcessModel(string: typing.Union[java.lang.String, str], processModel: jneqsim.process.processmodel.ProcessModel, boolean: bool) -> java.util.List[EngineeringProject]: ...
    @staticmethod
    def from_(string: typing.Union[java.lang.String, str], processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'NorsokOffshoreEngineeringBuilder': ...
    def getDesignBasis(self) -> EngineeringDesignBasis: ...
    def projectId(self, string: typing.Union[java.lang.String, str]) -> 'NorsokOffshoreEngineeringBuilder': ...
    def registerProposedInstruments(self, boolean: bool) -> 'NorsokOffshoreEngineeringBuilder': ...

class ProcessToEngineeringDesignBuilder:
    def addCompressorOperatingEnvelopeDesign(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addControlValveDesign(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addHeatExchangerDesign(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, *double4: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addInletCompressionExportSlice(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]) -> EngineeringProject: ...
    def addInventoryDesign(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addPipingNetworkDesign(self, string: typing.Union[java.lang.String, str], pipingRulePack: jneqsim.process.engineering.piping.PipingRulePack, *segmentDefinition: jneqsim.process.engineering.design.modules.PipingNetworkDesignModule.SegmentDefinition) -> 'ProcessToEngineeringDesignBuilder': ...
    def addPumpDesign(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addRatedCapacity(self, string: typing.Union[java.lang.String, str], engineeringMetric: jneqsim.process.engineering.designcase.EngineeringMetric, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, *double2: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def addReliefDeviceDesign(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], engineeringMetric: jneqsim.process.engineering.designcase.EngineeringMetric, *double: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def compressorDrivers(self, double: float, *double2: float) -> 'ProcessToEngineeringDesignBuilder': ...
    def exportLineLimits(self, double: float, double2: float) -> 'ProcessToEngineeringDesignBuilder': ...
    @staticmethod
    def fromProcessModel(string: typing.Union[java.lang.String, str], processModel: jneqsim.process.processmodel.ProcessModel, boolean: bool) -> java.util.List[EngineeringProject]: ...
    @staticmethod
    def on(engineeringProject: EngineeringProject) -> 'ProcessToEngineeringDesignBuilder': ...
    def separatorBasis(self, double: float, double2: float, double3: float) -> 'ProcessToEngineeringDesignBuilder': ...

class ProcessToEngineeringSimulator:
    @typing.overload
    @staticmethod
    def run(engineeringProject: EngineeringProject) -> EngineeringSimulationResult: ...
    @typing.overload
    @staticmethod
    def run(engineeringProject: EngineeringProject, int: int) -> EngineeringSimulationResult: ...
    @typing.overload
    @staticmethod
    def run(engineeringProject: EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy) -> EngineeringSimulationResult: ...
    @typing.overload
    @staticmethod
    def run(engineeringProject: EngineeringProject, engineeringAutoConfigurationPolicy: jneqsim.process.engineering.production.EngineeringAutoConfigurationPolicy, int: int) -> EngineeringSimulationResult: ...

class ReliefDeviceDesignInput(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getAllowableBuiltUpBackPressurePercent(self) -> float: ...
    def getAllowableInletLossPercent(self) -> float: ...
    def getConcurrencyGroup(self) -> java.lang.String: ...
    def getDeviceTag(self) -> java.lang.String: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getEvidenceReference(self) -> java.lang.String: ...
    def getFireZone(self) -> java.lang.String: ...
    def getInletDiameterM(self) -> float: ...
    def getInletLengthM(self) -> float: ...
    def getInletResistanceCoefficient(self) -> float: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getOutletDiameterM(self) -> float: ...
    def getOutletLengthM(self) -> float: ...
    def getOutletResistanceCoefficient(self) -> float: ...
    def getSelectedOrificeAreaIn2(self) -> float: ...
    def getTwoPhaseMethod(self) -> java.lang.String: ...
    def setAllowableBuiltUpBackPressurePercent(self, double: float) -> 'ReliefDeviceDesignInput': ...
    def setAllowableInletLossPercent(self, double: float) -> 'ReliefDeviceDesignInput': ...
    def setConcurrencyGroup(self, string: typing.Union[java.lang.String, str]) -> 'ReliefDeviceDesignInput': ...
    def setEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'ReliefDeviceDesignInput': ...
    def setFireZone(self, string: typing.Union[java.lang.String, str]) -> 'ReliefDeviceDesignInput': ...
    def setInletPiping(self, double: float, double2: float, double3: float) -> 'ReliefDeviceDesignInput': ...
    def setOutletPiping(self, double: float, double2: float, double3: float) -> 'ReliefDeviceDesignInput': ...
    def setSelectedOrificeAreaIn2(self, double: float) -> 'ReliefDeviceDesignInput': ...
    def setTwoPhaseMethod(self, string: typing.Union[java.lang.String, str]) -> 'ReliefDeviceDesignInput': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ReliefScenarioBasis(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'ReliefScenarioBasis': ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getHazardReviewReference(self) -> java.lang.String: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getRequiredCauses(self) -> java.util.Set[jneqsim.process.safety.overpressure.ReliefCause]: ...
    def require(self, reliefCause: jneqsim.process.safety.overpressure.ReliefCause) -> 'ReliefScenarioBasis': ...
    def setHazardReviewReference(self, string: typing.Union[java.lang.String, str]) -> 'ReliefScenarioBasis': ...

class SafetyFunctionDesign(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], int: int): ...
    def addSubsystem(self, subsystem: 'SafetyFunctionDesign.Subsystem') -> 'SafetyFunctionDesign': ...
    def approve(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign': ...
    def areArchitecturalConstraintsMet(self) -> bool: ...
    def calculatePfdAverage(self) -> float: ...
    def calculatePfh(self) -> float: ...
    def getAchievedSil(self) -> int: ...
    def getApprovalStatus(self) -> EngineeringApprovalStatus: ...
    def getDemandMode(self) -> 'SafetyFunctionDesign.DemandMode': ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getRequirementId(self) -> java.lang.String: ...
    def getSifTag(self) -> java.lang.String: ...
    def getSubsystems(self) -> java.util.List['SafetyFunctionDesign.Subsystem']: ...
    def getTargetSil(self) -> int: ...
    def setDemandMode(self, demandMode: 'SafetyFunctionDesign.DemandMode') -> 'SafetyFunctionDesign': ...
    def setLopaReference(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign': ...
    def setSafeState(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign': ...
    def setSrsReference(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class DemandMode(java.lang.Enum['SafetyFunctionDesign.DemandMode']):
        LOW_DEMAND: typing.ClassVar['SafetyFunctionDesign.DemandMode'] = ...
        HIGH_OR_CONTINUOUS_DEMAND: typing.ClassVar['SafetyFunctionDesign.DemandMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign.DemandMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionDesign.DemandMode']: ...
    class Subsystem(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], subsystemType: 'SafetyFunctionDesign.SubsystemType', int: int, int2: int, double: float, double2: float, double3: float, double4: float, double5: float): ...
        def calculatePfdAverage(self) -> float: ...
        def calculatePfh(self) -> float: ...
        def copyWithReliabilityInputs(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'SafetyFunctionDesign.Subsystem': ...
        def getBetaFactor(self) -> float: ...
        def getBypassProbability(self) -> float: ...
        def getChannelCount(self) -> int: ...
        def getDangerousFailureRatePerHour(self) -> float: ...
        def getDiagnosticCoverage(self) -> float: ...
        def getMeanRepairTimeHours(self) -> float: ...
        def getMissingFields(self) -> java.util.List[java.lang.String]: ...
        def getName(self) -> java.lang.String: ...
        def getProofTestIntervalHours(self) -> float: ...
        def getType(self) -> 'SafetyFunctionDesign.SubsystemType': ...
        def getVotesRequired(self) -> int: ...
        def getVotingArchitecture(self) -> java.lang.String: ...
        def setArchitecturalConstraints(self, int: int, int2: int) -> 'SafetyFunctionDesign.Subsystem': ...
        def setBypassProbability(self, double: float) -> 'SafetyFunctionDesign.Subsystem': ...
        def setCertifiedDataReference(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign.Subsystem': ...
        def setCommonCauseGroup(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign.Subsystem': ...
        def setMissionTimeHours(self, double: float) -> 'SafetyFunctionDesign.Subsystem': ...
        def setPartialStrokeTesting(self, double: float, double2: float) -> 'SafetyFunctionDesign.Subsystem': ...
        def setProofTestCoverage(self, double: float) -> 'SafetyFunctionDesign.Subsystem': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SubsystemType(java.lang.Enum['SafetyFunctionDesign.SubsystemType']):
        SENSOR: typing.ClassVar['SafetyFunctionDesign.SubsystemType'] = ...
        LOGIC_SOLVER: typing.ClassVar['SafetyFunctionDesign.SubsystemType'] = ...
        FINAL_ELEMENT: typing.ClassVar['SafetyFunctionDesign.SubsystemType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionDesign.SubsystemType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionDesign.SubsystemType']: ...

class ShutdownSequence(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addAction(self, action: 'ShutdownSequence.Action') -> 'ShutdownSequence': ...
    def addRequirementId(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def approve(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def getActions(self) -> java.util.List['ShutdownSequence.Action']: ...
    def getApprovalStatus(self) -> EngineeringApprovalStatus: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getProtectedEquipmentTag(self) -> java.lang.String: ...
    def getRequirementIds(self) -> java.util.List[java.lang.String]: ...
    def getSequenceId(self) -> java.lang.String: ...
    def getTotalResponseTimeSeconds(self) -> float: ...
    def isWithinResponseTimeBudget(self) -> bool: ...
    def setHazopReference(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def setProtectedEquipmentTag(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def setResetAndRestartDefined(self, boolean: bool) -> 'ShutdownSequence': ...
    def setResponseTimeBudgetSeconds(self, double: float) -> 'ShutdownSequence': ...
    def setSafeState(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def setSrsReference(self, string: typing.Union[java.lang.String, str]) -> 'ShutdownSequence': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Action(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float): ...
        def getCompletionTimeSeconds(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SimulationEngineeringDesignReport:
    def getBlowdownFlareStudyCount(self) -> int: ...
    def getCalculatedEquipmentCount(self) -> int: ...
    def getReliefStudyCount(self) -> int: ...
    def toJson(self) -> java.lang.String: ...
    def toJsonObject(self) -> com.google.gson.JsonObject: ...

class SimulationEngineeringDesignRunner:
    @staticmethod
    def run(engineeringProject: EngineeringProject) -> SimulationEngineeringDesignReport: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering")``.

    EngineeringApprovalRecord: typing.Type[EngineeringApprovalRecord]
    EngineeringApprovalStatus: typing.Type[EngineeringApprovalStatus]
    EngineeringBoundary: typing.Type[EngineeringBoundary]
    EngineeringCoverageMatrix: typing.Type[EngineeringCoverageMatrix]
    EngineeringDesignBasis: typing.Type[EngineeringDesignBasis]
    EngineeringEvidenceRecord: typing.Type[EngineeringEvidenceRecord]
    EngineeringOrigin: typing.Type[EngineeringOrigin]
    EngineeringProject: typing.Type[EngineeringProject]
    EngineeringRequirement: typing.Type[EngineeringRequirement]
    EngineeringRule: typing.Type[EngineeringRule]
    EngineeringSimulationResult: typing.Type[EngineeringSimulationResult]
    EngineeringSimulationRunner: typing.Type[EngineeringSimulationRunner]
    EngineeringStandard: typing.Type[EngineeringStandard]
    EngineeringValidationReport: typing.Type[EngineeringValidationReport]
    LineDesignInput: typing.Type[LineDesignInput]
    NorsokOffshoreEngineeringBuilder: typing.Type[NorsokOffshoreEngineeringBuilder]
    ProcessToEngineeringDesignBuilder: typing.Type[ProcessToEngineeringDesignBuilder]
    ProcessToEngineeringSimulator: typing.Type[ProcessToEngineeringSimulator]
    ReliefDeviceDesignInput: typing.Type[ReliefDeviceDesignInput]
    ReliefScenarioBasis: typing.Type[ReliefScenarioBasis]
    SafetyFunctionDesign: typing.Type[SafetyFunctionDesign]
    ShutdownSequence: typing.Type[ShutdownSequence]
    SimulationEngineeringDesignReport: typing.Type[SimulationEngineeringDesignReport]
    SimulationEngineeringDesignRunner: typing.Type[SimulationEngineeringDesignRunner]
    automation: jneqsim.process.engineering.automation.__module_protocol__
    calculation: jneqsim.process.engineering.calculation.__module_protocol__
    deliverables: jneqsim.process.engineering.deliverables.__module_protocol__
    design: jneqsim.process.engineering.design.__module_protocol__
    designcase: jneqsim.process.engineering.designcase.__module_protocol__
    dexpi: jneqsim.process.engineering.dexpi.__module_protocol__
    handover: jneqsim.process.engineering.handover.__module_protocol__
    impact: jneqsim.process.engineering.impact.__module_protocol__
    instrumentation: jneqsim.process.engineering.instrumentation.__module_protocol__
    mechanical: jneqsim.process.engineering.mechanical.__module_protocol__
    model: jneqsim.process.engineering.model.__module_protocol__
    numerics: jneqsim.process.engineering.numerics.__module_protocol__
    pid: jneqsim.process.engineering.pid.__module_protocol__
    piping: jneqsim.process.engineering.piping.__module_protocol__
    production: jneqsim.process.engineering.production.__module_protocol__
    rotating: jneqsim.process.engineering.rotating.__module_protocol__
    safety: jneqsim.process.engineering.safety.__module_protocol__
    validation: jneqsim.process.engineering.validation.__module_protocol__
    verticalslice: jneqsim.process.engineering.verticalslice.__module_protocol__
