
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.engineering
import jneqsim.process.engineering.calculation
import jneqsim.process.engineering.production
import jneqsim.process.engineering.safety.lifecycle
import jneqsim.process.equipment.compressor
import jneqsim.process.safety.depressurization
import jneqsim.process.safety.risk.sis
import jneqsim.process.safety.scenario
import typing



class CompressorTripResponse(java.io.Serializable):
    @staticmethod
    def capture(string: typing.Union[java.lang.String, str], antiSurge: jneqsim.process.equipment.compressor.AntiSurge, boolean: bool, double: float, double2: float, string2: typing.Union[java.lang.String, str]) -> 'CompressorTripResponse': ...
    def getCompressorTag(self) -> java.lang.String: ...
    def isEvidenceComplete(self) -> bool: ...
    def isPassed(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class FacilitySafetyResponseStudy(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str]) -> 'FacilitySafetyResponseStudy.Builder': ...
    def getFindings(self) -> java.util.List[java.lang.String]: ...
    def isEvidenceComplete(self) -> bool: ...
    def isReadyForEngineeringReview(self) -> bool: ...
    def isTechnicallyAcceptable(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def addCompressorTripResponse(self, compressorTripResponse: CompressorTripResponse) -> 'FacilitySafetyResponseStudy.Builder': ...
        def addConstraint(self, processSafetyConstraint: 'ProcessSafetyConstraint') -> 'FacilitySafetyResponseStudy.Builder': ...
        def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'FacilitySafetyResponseStudy.Builder': ...
        def addProtectionResult(self, string: typing.Union[java.lang.String, str], dynamicSafetyScenarioResult: jneqsim.process.safety.scenario.DynamicSafetyScenarioResult) -> 'FacilitySafetyResponseStudy.Builder': ...
        def build(self) -> 'FacilitySafetyResponseStudy': ...
        def disposalResult(self, coupledReliefBlowdownFlareResult: jneqsim.process.safety.depressurization.CoupledReliefBlowdownFlareResult) -> 'FacilitySafetyResponseStudy.Builder': ...
        def scenarioSelectionReviewed(self, boolean: bool) -> 'FacilitySafetyResponseStudy.Builder': ...

class FlareConsequenceCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['FlareConsequenceCalculation.Input', 'FlareConsequenceCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'FlareConsequenceCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'FlareConsequenceCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['FlareConsequenceCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str]) -> 'FlareConsequenceCalculation.Input.Builder': ...
        class Builder:
            def build(self) -> 'FlareConsequenceCalculation.Input': ...
            def dispersion(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'FlareConsequenceCalculation.Input.Builder': ...
            def flareTip(self, double: float, double2: float, double3: float) -> 'FlareConsequenceCalculation.Input.Builder': ...
            def noise(self, double: float, double2: float, double3: float) -> 'FlareConsequenceCalculation.Input.Builder': ...
            def radiation(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'FlareConsequenceCalculation.Input.Builder': ...
    class Result(jneqsim.process.engineering.calculation.EngineeringConstraintResult, java.io.Serializable):
        def allConstraintsSatisfied(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class NcsSafetyFunctionStudy(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def add(self, safetyInstrumentedFunction: jneqsim.process.safety.risk.sis.SafetyInstrumentedFunction, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]) -> 'NcsSafetyFunctionStudy': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ProcessSafetyConstraint(java.io.Serializable):
    def getId(self) -> java.lang.String: ...
    def isEvidenceComplete(self) -> bool: ...
    def isMet(self) -> bool: ...
    def isRequired(self) -> bool: ...
    @staticmethod
    def maximum(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, string4: typing.Union[java.lang.String, str]) -> 'ProcessSafetyConstraint': ...
    @staticmethod
    def minimum(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, string4: typing.Union[java.lang.String, str]) -> 'ProcessSafetyConstraint': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class LimitType(java.lang.Enum['ProcessSafetyConstraint.LimitType']):
        MAXIMUM: typing.ClassVar['ProcessSafetyConstraint.LimitType'] = ...
        MINIMUM: typing.ClassVar['ProcessSafetyConstraint.LimitType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ProcessSafetyConstraint.LimitType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ProcessSafetyConstraint.LimitType']: ...

class ReliefSizingCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['ReliefSizingCalculation.Input', 'ReliefSizingCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'ReliefSizingCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'ReliefSizingCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['ReliefSizingCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], phase: 'ReliefSizingCalculation.Phase') -> 'ReliefSizingCalculation.Input.Builder': ...
        class Builder:
            def build(self) -> 'ReliefSizingCalculation.Input': ...
            def correctionFactors(self, double: float, double2: float, double3: float) -> 'ReliefSizingCalculation.Input.Builder': ...
            def flowAndPressure(self, double: float, double2: float, double3: float) -> 'ReliefSizingCalculation.Input.Builder': ...
            def gasProperties(self, double: float, double2: float, double3: float, double4: float) -> 'ReliefSizingCalculation.Input.Builder': ...
            def liquidDensityKgM3(self, double: float) -> 'ReliefSizingCalculation.Input.Builder': ...
            def orificeCandidatesIn2(self, *double: float) -> 'ReliefSizingCalculation.Input.Builder': ...
            def twoPhaseMethod(self, double: float, string: typing.Union[java.lang.String, str]) -> 'ReliefSizingCalculation.Input.Builder': ...
    class Phase(java.lang.Enum['ReliefSizingCalculation.Phase']):
        GAS: typing.ClassVar['ReliefSizingCalculation.Phase'] = ...
        LIQUID: typing.ClassVar['ReliefSizingCalculation.Phase'] = ...
        STEAM: typing.ClassVar['ReliefSizingCalculation.Phase'] = ...
        TWO_PHASE: typing.ClassVar['ReliefSizingCalculation.Phase'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ReliefSizingCalculation.Phase': ...
        @staticmethod
        def values() -> typing.MutableSequence['ReliefSizingCalculation.Phase']: ...
    class Result(java.io.Serializable):
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class SafetyFunctionDegradedModeAssessment:
    @staticmethod
    def assess(safetyFunctionDesign: jneqsim.process.engineering.SafetyFunctionDesign, safetyFunctionOperatingMode: 'SafetyFunctionOperatingMode') -> 'SafetyFunctionDegradedModeAssessment.Result': ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def getSubsystemResults(self) -> java.util.List['SafetyFunctionDegradedModeAssessment.SubsystemResult']: ...
        def getVerdict(self) -> java.lang.String: ...
        def isDemandCapable(self) -> bool: ...
        def isTargetSilClaimPreserved(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SubsystemResult(java.io.Serializable):
        def getEffectiveArchitecture(self) -> java.lang.String: ...
        def isDemandCapable(self) -> bool: ...
        def isProofTestOverdue(self) -> bool: ...

class SafetyFunctionOperatingMode(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], modeType: 'SafetyFunctionOperatingMode.ModeType') -> 'SafetyFunctionOperatingMode.Builder': ...
    def getAuthorizationReference(self) -> java.lang.String: ...
    def getCompensatingMeasure(self) -> java.lang.String: ...
    def getElapsedDurationHours(self) -> float: ...
    def getMaximumDurationHours(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getType(self) -> 'SafetyFunctionOperatingMode.ModeType': ...
    class Builder:
        def authorizationReference(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionOperatingMode.Builder': ...
        def build(self) -> 'SafetyFunctionOperatingMode': ...
        def channelState(self, string: typing.Union[java.lang.String, str], int: int, channelState: 'SafetyFunctionOperatingMode.ChannelState') -> 'SafetyFunctionOperatingMode.Builder': ...
        def compensatingMeasure(self, string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionOperatingMode.Builder': ...
        def duration(self, double: float, double2: float) -> 'SafetyFunctionOperatingMode.Builder': ...
        def hoursSinceProofTest(self, string: typing.Union[java.lang.String, str], double: float) -> 'SafetyFunctionOperatingMode.Builder': ...
    class ChannelState(java.lang.Enum['SafetyFunctionOperatingMode.ChannelState']):
        AVAILABLE: typing.ClassVar['SafetyFunctionOperatingMode.ChannelState'] = ...
        BYPASSED: typing.ClassVar['SafetyFunctionOperatingMode.ChannelState'] = ...
        DANGEROUS_FAILED: typing.ClassVar['SafetyFunctionOperatingMode.ChannelState'] = ...
        FORCED_TRIP: typing.ClassVar['SafetyFunctionOperatingMode.ChannelState'] = ...
        UNDER_REPAIR: typing.ClassVar['SafetyFunctionOperatingMode.ChannelState'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionOperatingMode.ChannelState': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionOperatingMode.ChannelState']: ...
    class ModeType(java.lang.Enum['SafetyFunctionOperatingMode.ModeType']):
        NORMAL: typing.ClassVar['SafetyFunctionOperatingMode.ModeType'] = ...
        DEGRADED: typing.ClassVar['SafetyFunctionOperatingMode.ModeType'] = ...
        MAINTENANCE: typing.ClassVar['SafetyFunctionOperatingMode.ModeType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionOperatingMode.ModeType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionOperatingMode.ModeType']: ...

class SafetyFunctionReliabilityStudy:
    @staticmethod
    def run(safetyFunctionDesign: jneqsim.process.engineering.SafetyFunctionDesign, list: java.util.List['SafetyFunctionReliabilityStudy.SubsystemUncertainty'], int: int, long: int) -> 'SafetyFunctionReliabilityStudy.Result': ...
    class Result(java.io.Serializable):
        def getDeterministicPfdAverage(self) -> float: ...
        def getDeterministicPfh(self) -> float: ...
        def getIterations(self) -> int: ...
        def getP10PfdAverage(self) -> float: ...
        def getP10Pfh(self) -> float: ...
        def getP50PfdAverage(self) -> float: ...
        def getP50Pfh(self) -> float: ...
        def getP90PfdAverage(self) -> float: ...
        def getP90Pfh(self) -> float: ...
        def getSeed(self) -> int: ...
        def getTargetMetProbability(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SubsystemUncertainty(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def setBetaFactor(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
        def setBypassProbability(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
        def setDiagnosticCoverage(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
        def setFailureRateFactor(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
        def setProofTestIntervalFactor(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
        def setRepairTimeFactor(self, triangularDistribution: 'SafetyFunctionReliabilityStudy.TriangularDistribution') -> 'SafetyFunctionReliabilityStudy.SubsystemUncertainty': ...
    class TriangularDistribution(java.io.Serializable):
        @staticmethod
        def constant(double: float) -> 'SafetyFunctionReliabilityStudy.TriangularDistribution': ...
        @staticmethod
        def of(double: float, double2: float, double3: float) -> 'SafetyFunctionReliabilityStudy.TriangularDistribution': ...

class SafetyFunctionTransientVerification(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float): ...
    def verify(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> java.util.Map[java.lang.String, typing.Any]: ...

class SafetyScenarioEngineCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['SafetyScenarioEngineCalculation.Input', 'SafetyScenarioEngineCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'SafetyScenarioEngineCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'SafetyScenarioEngineCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['SafetyScenarioEngineCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Credibility(java.lang.Enum['SafetyScenarioEngineCalculation.Credibility']):
        CREDIBLE: typing.ClassVar['SafetyScenarioEngineCalculation.Credibility'] = ...
        NOT_CREDIBLE: typing.ClassVar['SafetyScenarioEngineCalculation.Credibility'] = ...
        HAZOP_DECISION_REQUIRED: typing.ClassVar['SafetyScenarioEngineCalculation.Credibility'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyScenarioEngineCalculation.Credibility': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyScenarioEngineCalculation.Credibility']: ...
    class FluidModel(java.lang.Enum['SafetyScenarioEngineCalculation.FluidModel']):
        GAS: typing.ClassVar['SafetyScenarioEngineCalculation.FluidModel'] = ...
        LIQUID: typing.ClassVar['SafetyScenarioEngineCalculation.FluidModel'] = ...
        STEAM: typing.ClassVar['SafetyScenarioEngineCalculation.FluidModel'] = ...
        TWO_PHASE: typing.ClassVar['SafetyScenarioEngineCalculation.FluidModel'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyScenarioEngineCalculation.FluidModel': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyScenarioEngineCalculation.FluidModel']: ...
    class Input(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], list: java.util.List['SafetyScenarioEngineCalculation.Scenario'], doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float, double3: float, double4: float, double5: float): ...
    class Result(java.io.Serializable):
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Scenario(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], type: 'SafetyScenarioEngineCalculation.Type', credibility: 'SafetyScenarioEngineCalculation.Credibility', fluidModel: 'SafetyScenarioEngineCalculation.FluidModel', string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float): ...
    class Type(java.lang.Enum['SafetyScenarioEngineCalculation.Type']):
        BLOCKED_OUTLET: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        CONTROL_VALVE_FAILURE: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        UTILITY_OR_COOLING_FAILURE: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        COMPRESSOR_TRIP_SETTLE_OUT: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        FIRE_EXPOSURE: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        TUBE_RUPTURE: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        THERMAL_EXPANSION: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        GAS_BLOW_BY: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        ABNORMAL_HEAT_INPUT: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        CHECK_VALVE_FAILURE: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        SIMULTANEOUS_BLOWDOWN: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        LOSS_OF_CONTAINMENT: typing.ClassVar['SafetyScenarioEngineCalculation.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyScenarioEngineCalculation.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyScenarioEngineCalculation.Type']: ...

class SafetyVerificationBenchmarkSuite:
    SIF_PFD_METHOD: typing.ClassVar[java.lang.String] = ...
    LOPA_FREQUENCY_METHOD: typing.ClassVar[java.lang.String] = ...
    DYNAMIC_RESPONSE_METHOD: typing.ClassVar[java.lang.String] = ...
    METHOD_VERSION: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], sourceClass: jneqsim.process.engineering.production.EngineeringValidationBenchmark.SourceClass, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]): ...
    def addDynamicResponse(self, string: typing.Union[java.lang.String, str], dynamicSafetyScenarioResult: jneqsim.process.safety.scenario.DynamicSafetyScenarioResult, string2: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> 'SafetyVerificationBenchmarkSuite': ...
    def addLopaFrequency(self, string: typing.Union[java.lang.String, str], lOPAResult: jneqsim.process.safety.risk.sis.LOPAResult, double: float, double2: float, double3: float) -> 'SafetyVerificationBenchmarkSuite': ...
    def addSifPfd(self, string: typing.Union[java.lang.String, str], safetyFunctionDesign: jneqsim.process.engineering.SafetyFunctionDesign, double: float, double2: float, double3: float) -> 'SafetyVerificationBenchmarkSuite': ...
    def evaluate(self) -> jneqsim.process.engineering.production.EngineeringBenchmarkSuite.Report: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.safety")``.

    CompressorTripResponse: typing.Type[CompressorTripResponse]
    FacilitySafetyResponseStudy: typing.Type[FacilitySafetyResponseStudy]
    FlareConsequenceCalculation: typing.Type[FlareConsequenceCalculation]
    NcsSafetyFunctionStudy: typing.Type[NcsSafetyFunctionStudy]
    ProcessSafetyConstraint: typing.Type[ProcessSafetyConstraint]
    ReliefSizingCalculation: typing.Type[ReliefSizingCalculation]
    SafetyFunctionDegradedModeAssessment: typing.Type[SafetyFunctionDegradedModeAssessment]
    SafetyFunctionOperatingMode: typing.Type[SafetyFunctionOperatingMode]
    SafetyFunctionReliabilityStudy: typing.Type[SafetyFunctionReliabilityStudy]
    SafetyFunctionTransientVerification: typing.Type[SafetyFunctionTransientVerification]
    SafetyScenarioEngineCalculation: typing.Type[SafetyScenarioEngineCalculation]
    SafetyVerificationBenchmarkSuite: typing.Type[SafetyVerificationBenchmarkSuite]
    lifecycle: jneqsim.process.engineering.safety.lifecycle.__module_protocol__
