
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.controllerdevice
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.measurementdevice
import jneqsim.process.processmodel
import jneqsim.thermo.system
import org.w3c.dom
import typing



class Dexpi20ConformanceAssessment:
    SPECIFICATION_VERSION: typing.ClassVar[java.lang.String] = ...
    SPECIFICATION_RELEASE_DATE: typing.ClassVar[java.lang.String] = ...
    OFFICIAL_SCHEMA_SHA256: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def assess(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], profile: 'Dexpi20ConformanceAssessment.Profile') -> 'Dexpi20ConformanceAssessment.Report': ...
    class Profile(java.lang.Enum['Dexpi20ConformanceAssessment.Profile']):
        PLANT_P_ID: typing.ClassVar['Dexpi20ConformanceAssessment.Profile'] = ...
        PROCESS_PFD_BFD: typing.ClassVar['Dexpi20ConformanceAssessment.Profile'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Dexpi20ConformanceAssessment.Profile': ...
        @staticmethod
        def values() -> typing.MutableSequence['Dexpi20ConformanceAssessment.Profile']: ...
    class Report(java.io.Serializable):
        def getErrors(self) -> java.util.List[java.lang.String]: ...
        def getWarnings(self) -> java.util.List[java.lang.String]: ...
        def isSchemaAndProfileConformant(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class Dexpi20ModelInspector:
    @staticmethod
    def inspect(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'Dexpi20ModelInspector.ModelSummary': ...
    class ModelSummary:
        def getEquipmentTags(self) -> java.util.List[java.lang.String]: ...
        def getEquipmentTypes(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
        def getInstrumentationFunctionCount(self) -> int: ...
        def getOffPageConnectorCount(self) -> int: ...
        def getPipingConnectionCount(self) -> int: ...
        def getRepresentationGroupCount(self) -> int: ...

class Dexpi20PlantExportMetadata:
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'Dexpi20PlantExportMetadata.Builder': ...
    def getExportDateTime(self) -> java.lang.String: ...
    def getOriginatingSystemName(self) -> java.lang.String: ...
    def getOriginatingSystemVendorName(self) -> java.lang.String: ...
    def getOriginatingSystemVersion(self) -> java.lang.String: ...
    def getPlantProperties(self) -> java.util.Map['Dexpi20PlantExportMetadata.PlantProperty', java.lang.String]: ...
    class Builder:
        def build(self) -> 'Dexpi20PlantExportMetadata': ...
        def plantProperty(self, plantProperty: 'Dexpi20PlantExportMetadata.PlantProperty', string: typing.Union[java.lang.String, str]) -> 'Dexpi20PlantExportMetadata.Builder': ...
    class PlantProperty(java.lang.Enum['Dexpi20PlantExportMetadata.PlantProperty']):
        ENTERPRISE_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        ENTERPRISE_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        INDUSTRIAL_COMPLEX_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        INDUSTRIAL_COMPLEX_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_AREA_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_AREA_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_SECTION_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_SECTION_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_SYSTEM_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_SYSTEM_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_TRAIN_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PLANT_TRAIN_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PROCESS_PLANT_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        PROCESS_PLANT_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        SITE_IDENTIFICATION_CODE: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        SITE_NAME: typing.ClassVar['Dexpi20PlantExportMetadata.PlantProperty'] = ...
        def getDexpiProperty(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Dexpi20PlantExportMetadata.PlantProperty': ...
        @staticmethod
        def values() -> typing.MutableSequence['Dexpi20PlantExportMetadata.PlantProperty']: ...

class Dexpi20PlantExportOptions:
    @staticmethod
    def builder(dexpi20PlantExportMetadata: Dexpi20PlantExportMetadata) -> 'Dexpi20PlantExportOptions.Builder': ...
    def getBoundaryConnectionMode(self) -> 'Dexpi20PlantExportOptions.BoundaryConnectionMode': ...
    def getMetadata(self) -> Dexpi20PlantExportMetadata: ...
    class BoundaryConnectionMode(java.lang.Enum['Dexpi20PlantExportOptions.BoundaryConnectionMode']):
        NONE: typing.ClassVar['Dexpi20PlantExportOptions.BoundaryConnectionMode'] = ...
        EXPLICIT_OFF_PAGE_CONNECTORS: typing.ClassVar['Dexpi20PlantExportOptions.BoundaryConnectionMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Dexpi20PlantExportOptions.BoundaryConnectionMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['Dexpi20PlantExportOptions.BoundaryConnectionMode']: ...
    class Builder:
        def boundaryConnectionMode(self, boundaryConnectionMode: 'Dexpi20PlantExportOptions.BoundaryConnectionMode') -> 'Dexpi20PlantExportOptions.Builder': ...
        def build(self) -> 'Dexpi20PlantExportOptions': ...

class Dexpi20ProcessModelWriter:
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...
    @staticmethod
    def writeAndAssess(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> Dexpi20ConformanceAssessment.Report: ...
    @typing.overload
    @staticmethod
    def writeAndAssessTopology(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'Dexpi20ProcessTopologyAssessment.Report': ...
    @typing.overload
    @staticmethod
    def writeAndAssessTopology(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'Dexpi20ProcessTopologyAssessment.Report': ...

class Dexpi20ProcessTopologyAssessment:
    class Diagnostic(java.io.Serializable):
        def getCode(self) -> java.lang.String: ...
        def getMessage(self) -> java.lang.String: ...
        def getSeverity(self) -> 'Dexpi20ProcessTopologyAssessment.Severity': ...
        def getSubject(self) -> java.lang.String: ...
        def toString(self) -> java.lang.String: ...
    class ExportedConnection(java.io.Serializable):
        def getSourcePortId(self) -> java.lang.String: ...
        def getSourceStep(self) -> java.lang.String: ...
        def getStreamId(self) -> java.lang.String: ...
        def getStreamLabel(self) -> java.lang.String: ...
        def getTargetPortId(self) -> java.lang.String: ...
        def getTargetStep(self) -> java.lang.String: ...
        def isBoundaryTarget(self) -> bool: ...
    class Report(java.io.Serializable):
        def getCanonicalConnectionIds(self) -> java.util.List[java.lang.String]: ...
        def getCanonicalFingerprint(self) -> java.lang.String: ...
        def getCanonicalMaterialConnections(self) -> java.util.List[java.lang.String]: ...
        def getConformanceReport(self) -> Dexpi20ConformanceAssessment.Report: ...
        def getDiagnostics(self) -> java.util.List['Dexpi20ProcessTopologyAssessment.Diagnostic']: ...
        def getExportOperatingValueSource(self) -> java.lang.String: ...
        def getExportTopologySource(self) -> java.lang.String: ...
        def getExportedConnections(self) -> java.util.List['Dexpi20ProcessTopologyAssessment.ExportedConnection']: ...
        def getExportedMaterialConnections(self) -> java.util.List[java.lang.String]: ...
        def isSchemaProfileAndSupportedTopologyValid(self) -> bool: ...
        def isSupportedMaterialTopologyEquivalent(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Severity(java.lang.Enum['Dexpi20ProcessTopologyAssessment.Severity']):
        INFO: typing.ClassVar['Dexpi20ProcessTopologyAssessment.Severity'] = ...
        WARNING: typing.ClassVar['Dexpi20ProcessTopologyAssessment.Severity'] = ...
        ERROR: typing.ClassVar['Dexpi20ProcessTopologyAssessment.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Dexpi20ProcessTopologyAssessment.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['Dexpi20ProcessTopologyAssessment.Severity']: ...

class Dexpi20SemanticValidator:
    @typing.overload
    @staticmethod
    def validate(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'Dexpi20SemanticValidator.ValidationReport': ...
    @typing.overload
    @staticmethod
    def validate(document: org.w3c.dom.Document) -> 'Dexpi20SemanticValidator.ValidationReport': ...
    @staticmethod
    def validateOrThrow(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...
    class ValidationReport:
        def getErrors(self) -> java.util.List[java.lang.String]: ...
        def getWarnings(self) -> java.util.List[java.lang.String]: ...
        def isValid(self) -> bool: ...

class Dexpi20XmlValidator:
    @staticmethod
    def isValid(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> bool: ...
    @staticmethod
    def validate(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...

class Dexpi20XmlWriter:
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], dexpi20PlantExportMetadata: Dexpi20PlantExportMetadata) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], dexpi20PlantExportOptions: Dexpi20PlantExportOptions) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream, dexpi20PlantExportMetadata: Dexpi20PlantExportMetadata) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream, dexpi20PlantExportOptions: Dexpi20PlantExportOptions) -> None: ...
    @typing.overload
    @staticmethod
    def writeAndAssess(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> Dexpi20ConformanceAssessment.Report: ...
    @typing.overload
    @staticmethod
    def writeAndAssess(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], dexpi20PlantExportMetadata: Dexpi20PlantExportMetadata) -> Dexpi20ConformanceAssessment.Report: ...
    @typing.overload
    @staticmethod
    def writeAndAssess(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], dexpi20PlantExportOptions: Dexpi20PlantExportOptions) -> Dexpi20ConformanceAssessment.Report: ...

class DexpiEquipmentFactory:
    @staticmethod
    def create(dexpiProcessUnit: 'DexpiProcessUnit', streamInterface: jneqsim.process.equipment.stream.StreamInterface) -> jneqsim.process.equipment.ProcessEquipmentInterface: ...

class DexpiInstrumentInfo(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str], string8: typing.Union[java.lang.String, str]): ...
    def getActuatingTag(self) -> java.lang.String: ...
    def getCategory(self) -> java.lang.String: ...
    def getFunctions(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getInstrumentNumber(self) -> java.lang.String: ...
    def getLoopNumber(self) -> java.lang.String: ...
    def getMeasurementUnit(self) -> java.lang.String: ...
    def getTagName(self) -> java.lang.String: ...
    def hasControlFunction(self) -> bool: ...
    def isInLoop(self) -> bool: ...
    def toString(self) -> java.lang.String: ...

class DexpiLayoutConfig:
    def __init__(self): ...
    def getBatteryLimitPadding(self) -> float: ...
    def getBorderMargin(self) -> float: ...
    def getDefaultScale(self) -> float: ...
    def getFontName(self) -> java.lang.String: ...
    def getInstrumentOffsetY(self) -> float: ...
    def getInstrumentXSpacing(self) -> float: ...
    def getLineColorB(self) -> java.lang.String: ...
    def getLineColorG(self) -> java.lang.String: ...
    def getLineColorR(self) -> java.lang.String: ...
    def getProcessLineWeight(self) -> float: ...
    def getSignalLineWeight(self) -> float: ...
    def getTagFontHeight(self) -> float: ...
    def getXSpacing(self) -> float: ...
    def getXStart(self) -> float: ...
    def getYBase(self) -> float: ...
    def getYBranchOffset(self) -> float: ...
    def isShowBatteryLimit(self) -> bool: ...
    def isShowEquipmentBars(self) -> bool: ...
    def isShowFailPositionMarkers(self) -> bool: ...
    def isShowFlowArrows(self) -> bool: ...
    def isShowInsulationMarks(self) -> bool: ...
    def isShowOrientationMarkers(self) -> bool: ...
    def isShowRevisionHistory(self) -> bool: ...
    def isShowSilMarkers(self) -> bool: ...
    def isShowStreamLabels(self) -> bool: ...
    def isShowStreamTable(self) -> bool: ...
    def isShowSymbolLegend(self) -> bool: ...
    def setBatteryLimitPadding(self, double: float) -> 'DexpiLayoutConfig': ...
    def setBorderMargin(self, double: float) -> 'DexpiLayoutConfig': ...
    def setDefaultScale(self, double: float) -> 'DexpiLayoutConfig': ...
    def setFontName(self, string: typing.Union[java.lang.String, str]) -> 'DexpiLayoutConfig': ...
    def setInstrumentOffsetY(self, double: float) -> 'DexpiLayoutConfig': ...
    def setInstrumentXSpacing(self, double: float) -> 'DexpiLayoutConfig': ...
    def setLineColor(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'DexpiLayoutConfig': ...
    def setProcessLineWeight(self, double: float) -> 'DexpiLayoutConfig': ...
    def setShowBatteryLimit(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowEquipmentBars(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowFailPositionMarkers(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowFlowArrows(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowInsulationMarks(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowOrientationMarkers(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowRevisionHistory(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowSilMarkers(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowStreamLabels(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowStreamTable(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setShowSymbolLegend(self, boolean: bool) -> 'DexpiLayoutConfig': ...
    def setSignalLineWeight(self, double: float) -> 'DexpiLayoutConfig': ...
    def setTagFontHeight(self, double: float) -> 'DexpiLayoutConfig': ...
    def setXSpacing(self, double: float) -> 'DexpiLayoutConfig': ...
    def setXStart(self, double: float) -> 'DexpiLayoutConfig': ...
    def setYBase(self, double: float) -> 'DexpiLayoutConfig': ...
    def setYBranchOffset(self, double: float) -> 'DexpiLayoutConfig': ...

class DexpiMappingLoader:
    @staticmethod
    def clearCache() -> None: ...
    @staticmethod
    def loadEquipmentMapping() -> java.util.Map[java.lang.String, jneqsim.process.equipment.EquipmentEnum]: ...
    @staticmethod
    def loadPipingComponentMapping() -> java.util.Map[java.lang.String, jneqsim.process.equipment.EquipmentEnum]: ...

class DexpiMetadata:
    TAG_NAME: typing.ClassVar[java.lang.String] = ...
    LINE_NUMBER: typing.ClassVar[java.lang.String] = ...
    FLUID_CODE: typing.ClassVar[java.lang.String] = ...
    SEGMENT_NUMBER: typing.ClassVar[java.lang.String] = ...
    OPERATING_PRESSURE_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_PRESSURE_UNIT: typing.ClassVar[java.lang.String] = ...
    OPERATING_TEMPERATURE_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_TEMPERATURE_UNIT: typing.ClassVar[java.lang.String] = ...
    OPERATING_FLOW_VALUE: typing.ClassVar[java.lang.String] = ...
    OPERATING_FLOW_UNIT: typing.ClassVar[java.lang.String] = ...
    INSTRUMENTATION_CATEGORY: typing.ClassVar[java.lang.String] = ...
    INSTRUMENTATION_FUNCTIONS: typing.ClassVar[java.lang.String] = ...
    INSTRUMENTATION_NUMBER: typing.ClassVar[java.lang.String] = ...
    LOOP_NUMBER: typing.ClassVar[java.lang.String] = ...
    SIGNAL_GENERATING_NUMBER: typing.ClassVar[java.lang.String] = ...
    ACTUATING_FUNCTION_NUMBER: typing.ClassVar[java.lang.String] = ...
    INSIDE_DIAMETER: typing.ClassVar[java.lang.String] = ...
    NOMINAL_DIAMETER: typing.ClassVar[java.lang.String] = ...
    TANGENT_TO_TANGENT_LENGTH: typing.ClassVar[java.lang.String] = ...
    DESIGN_PRESSURE: typing.ClassVar[java.lang.String] = ...
    DESIGN_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
    MINIMUM_DESIGN_TEMPERATURE: typing.ClassVar[java.lang.String] = ...
    RELIEF_SET_PRESSURE: typing.ClassVar[java.lang.String] = ...
    CORROSION_ALLOWANCE: typing.ClassVar[java.lang.String] = ...
    CONSTRUCTION_MATERIAL: typing.ClassVar[java.lang.String] = ...
    FAILURE_ACTION: typing.ClassVar[java.lang.String] = ...
    ORIENTATION: typing.ClassVar[java.lang.String] = ...
    VALVE_CV: typing.ClassVar[java.lang.String] = ...
    WALL_THICKNESS: typing.ClassVar[java.lang.String] = ...
    WEIGHT: typing.ClassVar[java.lang.String] = ...
    PIPING_CLASS_CODE: typing.ClassVar[java.lang.String] = ...
    FAIL_POSITION: typing.ClassVar[java.lang.String] = ...
    SIL_LEVEL: typing.ClassVar[java.lang.String] = ...
    INSULATION_CODE: typing.ClassVar[java.lang.String] = ...
    LINE_SIZE: typing.ClassVar[java.lang.String] = ...
    NUMBER_OF_TRAYS: typing.ClassVar[java.lang.String] = ...
    FEED_TRAY: typing.ClassVar[java.lang.String] = ...
    DEXPI_RDL_PREFIX: typing.ClassVar[java.lang.String] = ...
    DEFAULT_PRESSURE_UNIT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_TEMPERATURE_UNIT: typing.ClassVar[java.lang.String] = ...
    DEFAULT_FLOW_UNIT: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def recommendedEquipmentAttributes() -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def recommendedStreamAttributes() -> java.util.Set[java.lang.String]: ...
    @staticmethod
    def sizingAttributes() -> java.util.Set[java.lang.String]: ...

class DexpiProcessUnit(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], equipmentEnum: jneqsim.process.equipment.EquipmentEnum, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getDexpiClass(self) -> java.lang.String: ...
    def getDexpiId(self) -> java.lang.String: ...
    def getFluidCode(self) -> java.lang.String: ...
    def getLineNumber(self) -> java.lang.String: ...
    def getMappedEquipment(self) -> jneqsim.process.equipment.EquipmentEnum: ...
    def getSizingAttribute(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getSizingAttributeAsDouble(self, string: typing.Union[java.lang.String, str], double: float) -> float: ...
    def getSizingAttributes(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDexpiId(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSizingAttribute(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> None: ...

class DexpiRoundTripProfile:
    @staticmethod
    def minimalRunnableProfile() -> 'DexpiRoundTripProfile': ...
    def validate(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'DexpiRoundTripProfile.ValidationResult': ...
    class ValidationResult:
        def getViolations(self) -> java.util.List[java.lang.String]: ...
        def isSuccessful(self) -> bool: ...

class DexpiSimulationBuilder:
    def __init__(self, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]): ...
    def build(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def setAutoInstrument(self, boolean: bool) -> 'DexpiSimulationBuilder': ...
    def setFeedFlowRate(self, double: float, string: typing.Union[java.lang.String, str]) -> 'DexpiSimulationBuilder': ...
    def setFeedPressure(self, double: float, string: typing.Union[java.lang.String, str]) -> 'DexpiSimulationBuilder': ...
    def setFeedTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'DexpiSimulationBuilder': ...
    def setFluidTemplate(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> 'DexpiSimulationBuilder': ...
    def setNamespaceAware(self, boolean: bool) -> 'DexpiSimulationBuilder': ...

class DexpiStream(jneqsim.process.equipment.stream.Stream):
    def __init__(self, string: typing.Union[java.lang.String, str], systemInterface: jneqsim.thermo.system.SystemInterface, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getDexpiClass(self) -> java.lang.String: ...
    def getFluidCode(self) -> java.lang.String: ...
    def getLineNumber(self) -> java.lang.String: ...

class DexpiStreamUtils:
    @staticmethod
    def getGasOutletStream(processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @staticmethod
    def getLiquidOutletStream(processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @staticmethod
    def getWaterOutletStream(processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @staticmethod
    def isMultiOutlet(processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class DexpiTopologyResolver:
    @staticmethod
    def resolve(document: org.w3c.dom.Document) -> 'DexpiTopologyResolver.ResolvedTopology': ...
    class ResolvedTopology(java.io.Serializable):
        def __init__(self, list: java.util.List[typing.Union[java.lang.String, str]], list2: java.util.List['DexpiTopologyResolver.TopologyEdge'], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], org.w3c.dom.Element], typing.Mapping[typing.Union[java.lang.String, str], org.w3c.dom.Element]]): ...
        def getEdges(self) -> java.util.List['DexpiTopologyResolver.TopologyEdge']: ...
        def getEquipmentElements(self) -> java.util.Map[java.lang.String, org.w3c.dom.Element]: ...
        def getIncomingEdges(self, string: typing.Union[java.lang.String, str]) -> java.util.List['DexpiTopologyResolver.TopologyEdge']: ...
        def getNozzleToEquipment(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
        def getOrderedEquipmentIds(self) -> java.util.List[java.lang.String]: ...
        def getOutgoingEdges(self, string: typing.Union[java.lang.String, str]) -> java.util.List['DexpiTopologyResolver.TopologyEdge']: ...
        def hasCycle(self) -> bool: ...
    class TopologyEdge(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]): ...
        def getPipingSegmentId(self) -> java.lang.String: ...
        def getSourceEquipmentId(self) -> java.lang.String: ...
        def getSourceNozzleId(self) -> java.lang.String: ...
        def getTargetEquipmentId(self) -> java.lang.String: ...
        def getTargetNozzleId(self) -> java.lang.String: ...
        def toString(self) -> java.lang.String: ...

class DexpiXmlReader:
    @typing.overload
    @staticmethod
    def load(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    @typing.overload
    @staticmethod
    def load(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], processSystem: jneqsim.process.processmodel.ProcessSystem, stream: jneqsim.process.equipment.stream.Stream) -> None: ...
    @typing.overload
    @staticmethod
    def load(inputStream: java.io.InputStream, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    @typing.overload
    @staticmethod
    def load(inputStream: java.io.InputStream, processSystem: jneqsim.process.processmodel.ProcessSystem, stream: jneqsim.process.equipment.stream.Stream) -> None: ...
    @typing.overload
    @staticmethod
    def load(inputStream: java.io.InputStream, processSystem: jneqsim.process.processmodel.ProcessSystem, stream: jneqsim.process.equipment.stream.Stream, boolean: bool) -> None: ...
    @typing.overload
    @staticmethod
    def read(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], stream: jneqsim.process.equipment.stream.Stream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(inputStream: java.io.InputStream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def read(inputStream: java.io.InputStream, stream: jneqsim.process.equipment.stream.Stream) -> jneqsim.process.processmodel.ProcessSystem: ...
    @typing.overload
    @staticmethod
    def readInstruments(file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> java.util.List[DexpiInstrumentInfo]: ...
    @typing.overload
    @staticmethod
    def readInstruments(inputStream: java.io.InputStream) -> java.util.List[DexpiInstrumentInfo]: ...

class DexpiXmlReaderException(java.lang.Exception):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], throwable: java.lang.Throwable): ...

class DexpiXmlWriter:
    @staticmethod
    def getSchemaVersion() -> 'DexpiXmlWriter.DexpiSchemaVersion': ...
    @staticmethod
    def roundTrip(file: typing.Union[java.io.File, jpype.protocol.SupportsPath], file2: typing.Union[java.io.File, jpype.protocol.SupportsPath], stream: jneqsim.process.equipment.stream.Stream) -> None: ...
    @staticmethod
    def setAutoSynthesizeInstrumentation(boolean: bool) -> None: ...
    @staticmethod
    def setSchemaVersion(dexpiSchemaVersion: 'DexpiXmlWriter.DexpiSchemaVersion') -> None: ...
    @typing.overload
    @staticmethod
    def write(processModel: jneqsim.process.processmodel.ProcessModel, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processModel: jneqsim.process.processmodel.ProcessModel, outputStream: java.io.OutputStream) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], jneqsim.process.measurementdevice.MeasurementDeviceInterface], typing.Mapping[typing.Union[java.lang.String, str], jneqsim.process.measurementdevice.MeasurementDeviceInterface]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], jneqsim.process.controllerdevice.ControllerDeviceInterface], typing.Mapping[typing.Union[java.lang.String, str], jneqsim.process.controllerdevice.ControllerDeviceInterface]]) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...
    @typing.overload
    @staticmethod
    def write(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], jneqsim.process.measurementdevice.MeasurementDeviceInterface], typing.Mapping[typing.Union[java.lang.String, str], jneqsim.process.measurementdevice.MeasurementDeviceInterface]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], jneqsim.process.controllerdevice.ControllerDeviceInterface], typing.Mapping[typing.Union[java.lang.String, str], jneqsim.process.controllerdevice.ControllerDeviceInterface]]) -> None: ...
    @typing.overload
    @staticmethod
    def writeDexpi20(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def writeDexpi20(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...
    @typing.overload
    @staticmethod
    def writeForPyDexpi(processSystem: jneqsim.process.processmodel.ProcessSystem, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> None: ...
    @typing.overload
    @staticmethod
    def writeForPyDexpi(processSystem: jneqsim.process.processmodel.ProcessSystem, outputStream: java.io.OutputStream) -> None: ...
    @staticmethod
    def writeSheets(processModel: jneqsim.process.processmodel.ProcessModel, file: typing.Union[java.io.File, jpype.protocol.SupportsPath]) -> java.util.List[java.io.File]: ...
    class DexpiSchemaVersion(java.lang.Enum['DexpiXmlWriter.DexpiSchemaVersion']):
        PROTEUS_4_1_1: typing.ClassVar['DexpiXmlWriter.DexpiSchemaVersion'] = ...
        DEXPI_2_0: typing.ClassVar['DexpiXmlWriter.DexpiSchemaVersion'] = ...
        def getNamespaceUri(self) -> java.lang.String: ...
        def getSchemaLocation(self) -> java.lang.String: ...
        def getSchemaVersionAttribute(self) -> java.lang.String: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'DexpiXmlWriter.DexpiSchemaVersion': ...
        @staticmethod
        def values() -> typing.MutableSequence['DexpiXmlWriter.DexpiSchemaVersion']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.processmodel.dexpi")``.

    Dexpi20ConformanceAssessment: typing.Type[Dexpi20ConformanceAssessment]
    Dexpi20ModelInspector: typing.Type[Dexpi20ModelInspector]
    Dexpi20PlantExportMetadata: typing.Type[Dexpi20PlantExportMetadata]
    Dexpi20PlantExportOptions: typing.Type[Dexpi20PlantExportOptions]
    Dexpi20ProcessModelWriter: typing.Type[Dexpi20ProcessModelWriter]
    Dexpi20ProcessTopologyAssessment: typing.Type[Dexpi20ProcessTopologyAssessment]
    Dexpi20SemanticValidator: typing.Type[Dexpi20SemanticValidator]
    Dexpi20XmlValidator: typing.Type[Dexpi20XmlValidator]
    Dexpi20XmlWriter: typing.Type[Dexpi20XmlWriter]
    DexpiEquipmentFactory: typing.Type[DexpiEquipmentFactory]
    DexpiInstrumentInfo: typing.Type[DexpiInstrumentInfo]
    DexpiLayoutConfig: typing.Type[DexpiLayoutConfig]
    DexpiMappingLoader: typing.Type[DexpiMappingLoader]
    DexpiMetadata: typing.Type[DexpiMetadata]
    DexpiProcessUnit: typing.Type[DexpiProcessUnit]
    DexpiRoundTripProfile: typing.Type[DexpiRoundTripProfile]
    DexpiSimulationBuilder: typing.Type[DexpiSimulationBuilder]
    DexpiStream: typing.Type[DexpiStream]
    DexpiStreamUtils: typing.Type[DexpiStreamUtils]
    DexpiTopologyResolver: typing.Type[DexpiTopologyResolver]
    DexpiXmlReader: typing.Type[DexpiXmlReader]
    DexpiXmlReaderException: typing.Type[DexpiXmlReaderException]
    DexpiXmlWriter: typing.Type[DexpiXmlWriter]
