
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment.pipeline
import jneqsim.process.equipment.reservoir
import typing



class ChokeAndGasLiftAllocationOptimizer(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def addWell(self, chokeableGasLiftWell: 'ChokeableGasLiftWell') -> 'ChokeAndGasLiftAllocationOptimizer': ...
    def optimize(self) -> 'ChokeAndGasLiftAllocationOptimizer.AllocationResult': ...
    def setGasHandlingLimit(self, double: float) -> 'ChokeAndGasLiftAllocationOptimizer': ...
    def setLiftGasBudget(self, double: float) -> 'ChokeAndGasLiftAllocationOptimizer': ...
    def setObjective(self, objective: 'ChokeAndGasLiftAllocationOptimizer.Objective') -> 'ChokeAndGasLiftAllocationOptimizer': ...
    def setOilPrice(self, double: float) -> 'ChokeAndGasLiftAllocationOptimizer': ...
    def setWaterHandlingLimit(self, double: float) -> 'ChokeAndGasLiftAllocationOptimizer': ...
    class AllocationResult(java.io.Serializable):
        def __init__(self): ...
        def getObjectiveValue(self) -> float: ...
        def getTotalGas(self) -> float: ...
        def getTotalLift(self) -> float: ...
        def getTotalOil(self) -> float: ...
        def getTotalWater(self) -> float: ...
        def getWells(self) -> java.util.Map[java.lang.String, 'ChokeAndGasLiftAllocationOptimizer.WellAllocation']: ...
        def isFeasible(self) -> bool: ...
        def isGasFeasible(self) -> bool: ...
        def isLiftFeasible(self) -> bool: ...
        def isWaterFeasible(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
    class Objective(java.lang.Enum['ChokeAndGasLiftAllocationOptimizer.Objective']):
        OIL: typing.ClassVar['ChokeAndGasLiftAllocationOptimizer.Objective'] = ...
        REVENUE: typing.ClassVar['ChokeAndGasLiftAllocationOptimizer.Objective'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ChokeAndGasLiftAllocationOptimizer.Objective': ...
        @staticmethod
        def values() -> typing.MutableSequence['ChokeAndGasLiftAllocationOptimizer.Objective']: ...
    class WellAllocation(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, string2: typing.Union[java.lang.String, str]): ...
        def getBindingConstraint(self) -> java.lang.String: ...
        def getChokeFraction(self) -> float: ...
        def getGasRate(self) -> float: ...
        def getLiftRate(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getOilRate(self) -> float: ...
        def getWaterRate(self) -> float: ...

class ChokeableGasLiftWell(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], gasLiftPerformanceCurve: 'GasLiftPerformanceCurve'): ...
    def getCurrentChokeFraction(self) -> float: ...
    def getCurrentLiftRate(self) -> float: ...
    def getCurve(self) -> 'GasLiftPerformanceCurve': ...
    def getGasHandlingLimit(self) -> float: ...
    def getGor(self) -> float: ...
    def getMaxChokeFraction(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getShutReason(self) -> java.lang.String: ...
    def getWaterCut(self) -> float: ...
    def isForcedShut(self) -> bool: ...
    def oilRate(self, double: float, double2: float) -> float: ...
    def producedGasRate(self, double: float, double2: float) -> float: ...
    def producedWaterRate(self, double: float) -> float: ...
    def setCurrentChokeFraction(self, double: float) -> 'ChokeableGasLiftWell': ...
    def setCurrentLiftRate(self, double: float) -> 'ChokeableGasLiftWell': ...
    def setForcedShut(self, boolean: bool, string: typing.Union[java.lang.String, str]) -> 'ChokeableGasLiftWell': ...
    def setGasHandlingLimit(self, double: float) -> 'ChokeableGasLiftWell': ...
    def setGor(self, double: float) -> 'ChokeableGasLiftWell': ...
    def setMaxChokeFraction(self, double: float) -> 'ChokeableGasLiftWell': ...
    def setWaterCut(self, double: float) -> 'ChokeableGasLiftWell': ...

class GasLiftNetworkOptimizer(java.io.Serializable):
    def __init__(self): ...
    def addWell(self, string: typing.Union[java.lang.String, str], gasLiftPerformanceCurve: 'GasLiftPerformanceCurve') -> 'GasLiftNetworkOptimizer': ...
    def allocate(self, double: float) -> 'GasLiftNetworkOptimizer.AllocationResult': ...
    class AllocationResult(java.io.Serializable):
        def __init__(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], double: float, double2: float): ...
        def getLiftRates(self) -> java.util.Map[java.lang.String, float]: ...
        def getOilRates(self) -> java.util.Map[java.lang.String, float]: ...
        def getTotalLift(self) -> float: ...
        def getTotalOil(self) -> float: ...

class GasLiftPerformanceCurve(java.io.Serializable):
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    @staticmethod
    def fromWellSystem(wellSystem: jneqsim.process.equipment.reservoir.WellSystem, double: float, double2: float, double3: float) -> 'GasLiftPerformanceCurve': ...
    @staticmethod
    def fromWellSystemUplift(wellSystem: jneqsim.process.equipment.reservoir.WellSystem, double: float, double2: float, double3: float) -> 'GasLiftPerformanceCurve': ...
    def getBaseOilRate(self) -> float: ...
    def getMaxLiftRate(self) -> float: ...
    def incrementalSlope(self, double: float) -> float: ...
    def oilRateAt(self, double: float) -> float: ...
    def optimalLiftRate(self) -> float: ...

class IntegratedProductionModel(java.io.Serializable):
    EXPORT_NODE: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def addWell(self, string: typing.Union[java.lang.String, str], reservoirDrive: 'ReservoirDrive', wellDeliverabilityCurve: 'WellDeliverabilityCurve') -> 'IntegratedProductionModel.WellUnit': ...
    @typing.overload
    def addWell(self, string: typing.Union[java.lang.String, str], reservoirDrive: 'ReservoirDrive', wellDeliverabilityCurve: 'WellDeliverabilityCurve', flowlineBranch: 'FlowlineBranch') -> 'IntegratedProductionModel.WellUnit': ...
    def getName(self) -> java.lang.String: ...
    def getWells(self) -> java.util.List['IntegratedProductionModel.WellUnit']: ...
    def runProfile(self, double: float, double2: float) -> 'ProductionProfile': ...
    def setEmissionIntensity(self, double: float) -> 'IntegratedProductionModel': ...
    def setEnergyIntensity(self, double: float) -> 'IntegratedProductionModel': ...
    def setExportPressure(self, double: float) -> 'IntegratedProductionModel': ...
    def setHydrocarbonPrice(self, double: float) -> 'IntegratedProductionModel': ...
    def solve(self) -> 'IntegratedSolveResult': ...
    def toJson(self) -> java.lang.String: ...
    class WellUnit(java.io.Serializable):
        def getDrive(self) -> 'ReservoirDrive': ...
        def getFlowlineBranch(self) -> 'FlowlineBranch': ...
        def getLastRate(self) -> float: ...
        def getName(self) -> java.lang.String: ...
        def getWellBranch(self) -> 'WellBranch': ...

class IntegratedSolveResult(java.io.Serializable):
    def __init__(self, boolean: bool, int: int, double: float, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], double2: float, double3: float, double4: float, string: typing.Union[java.lang.String, str]): ...
    def getEmissionsKgPerDay(self) -> float: ...
    def getEnergyKWhPerDay(self) -> float: ...
    def getFieldRate(self) -> float: ...
    def getIterations(self) -> int: ...
    def getMethod(self) -> java.lang.String: ...
    def getNodePressures(self) -> java.util.Map[java.lang.String, float]: ...
    def getRevenue(self) -> float: ...
    def getWellRates(self) -> java.util.Map[java.lang.String, float]: ...
    def isConverged(self) -> bool: ...

class NetworkBranch(java.io.Serializable):
    def flow(self, double: float, double2: float) -> float: ...
    def getFromNode(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getToNode(self) -> java.lang.String: ...

class NetworkNewtonSolver(java.io.Serializable):
    def __init__(self): ...
    def addBranch(self, networkBranch: NetworkBranch) -> 'NetworkNewtonSolver': ...
    def addNode(self, networkNode: 'NetworkNode') -> 'NetworkNewtonSolver': ...
    def getBranches(self) -> java.util.List[NetworkBranch]: ...
    def getNode(self, string: typing.Union[java.lang.String, str]) -> 'NetworkNode': ...
    def setMaxIterations(self, int: int) -> None: ...
    def setMinPressure(self, double: float) -> None: ...
    def setTolerance(self, double: float) -> None: ...
    def solve(self) -> 'NetworkNewtonSolver.NetworkSolutionResult': ...
    class NetworkSolutionResult(java.io.Serializable):
        def __init__(self, boolean: bool, int: int, double: float, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], string: typing.Union[java.lang.String, str]): ...
        def getBranchFlows(self) -> java.util.Map[java.lang.String, float]: ...
        def getIterations(self) -> int: ...
        def getMaxResidual(self) -> float: ...
        def getMethod(self) -> java.lang.String: ...
        def getNodePressures(self) -> java.util.Map[java.lang.String, float]: ...
        def isConverged(self) -> bool: ...

class NetworkNode(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], nodeType: 'NetworkNode.NodeType', double: float, boolean: bool): ...
    def getExternalRate(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getPressure(self) -> float: ...
    def getType(self) -> 'NetworkNode.NodeType': ...
    def isPressureFixed(self) -> bool: ...
    @staticmethod
    def manifold(string: typing.Union[java.lang.String, str], double: float) -> 'NetworkNode': ...
    @staticmethod
    def reservoir(string: typing.Union[java.lang.String, str], double: float) -> 'NetworkNode': ...
    def setExternalRate(self, double: float) -> None: ...
    def setPressure(self, double: float) -> None: ...
    def setPressureFixed(self, boolean: bool) -> None: ...
    @staticmethod
    def sink(string: typing.Union[java.lang.String, str], double: float) -> 'NetworkNode': ...
    class NodeType(java.lang.Enum['NetworkNode.NodeType']):
        RESERVOIR: typing.ClassVar['NetworkNode.NodeType'] = ...
        JUNCTION: typing.ClassVar['NetworkNode.NodeType'] = ...
        MANIFOLD: typing.ClassVar['NetworkNode.NodeType'] = ...
        SINK: typing.ClassVar['NetworkNode.NodeType'] = ...
        SOURCE: typing.ClassVar['NetworkNode.NodeType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'NetworkNode.NodeType': ...
        @staticmethod
        def values() -> typing.MutableSequence['NetworkNode.NodeType']: ...

class ProductionProfile(java.io.Serializable):
    def __init__(self): ...
    def add(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> None: ...
    def getCumulativeProduction(self) -> float: ...
    def getCumulativeRevenue(self) -> float: ...
    def getPeakRate(self) -> float: ...
    def getPoints(self) -> java.util.List['ProductionProfile.Point']: ...
    def setCumulativeProduction(self, double: float) -> None: ...
    def setCumulativeRevenue(self, double: float) -> None: ...
    class Point(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float): ...
        def getEmissionsKgPerDay(self) -> float: ...
        def getEnergyKWhPerDay(self) -> float: ...
        def getRateSm3PerDay(self) -> float: ...
        def getReservoirPressureBara(self) -> float: ...
        def getRevenuePerDay(self) -> float: ...
        def getTimeYears(self) -> float: ...

class ReservoirDrive(java.io.Serializable):
    def getCumulativeProduction(self) -> float: ...
    def getInPlaceVolume(self) -> float: ...
    def getReservoirPressure(self) -> float: ...
    def produce(self, double: float, double2: float) -> None: ...

class ReservoirToMarketOptimizer(java.io.Serializable):
    def __init__(self, integratedProductionModel: IntegratedProductionModel): ...
    def optimize(self) -> 'ReservoirToMarketOptimizer.OptimizationResult': ...
    def setFacilityCapacity(self, double: float) -> 'ReservoirToMarketOptimizer': ...
    def setMaxIterations(self, int: int) -> 'ReservoirToMarketOptimizer': ...
    def setObjective(self, objective: 'ReservoirToMarketOptimizer.Objective') -> 'ReservoirToMarketOptimizer': ...
    class Objective(java.lang.Enum['ReservoirToMarketOptimizer.Objective']):
        REVENUE: typing.ClassVar['ReservoirToMarketOptimizer.Objective'] = ...
        RATE: typing.ClassVar['ReservoirToMarketOptimizer.Objective'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ReservoirToMarketOptimizer.Objective': ...
        @staticmethod
        def values() -> typing.MutableSequence['ReservoirToMarketOptimizer.Objective']: ...
    class OptimizationResult(java.io.Serializable):
        def __init__(self, boolean: bool, double: float, double2: float, double3: float, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], map2: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], int: int): ...
        def getChokeSettings(self) -> java.util.Map[java.lang.String, float]: ...
        def getEvaluations(self) -> int: ...
        def getFieldRate(self) -> float: ...
        def getObjectiveValue(self) -> float: ...
        def getRevenue(self) -> float: ...
        def getWellRates(self) -> java.util.Map[java.lang.String, float]: ...
        def isFeasible(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...

class StrupeOkeReport(java.io.Serializable):
    def __init__(self): ...
    @staticmethod
    def build(list: java.util.List[ChokeableGasLiftWell], allocationResult: ChokeAndGasLiftAllocationOptimizer.AllocationResult) -> 'StrupeOkeReport': ...
    def getActionSummary(self) -> java.util.Map[java.lang.String, int]: ...
    def getRecommendations(self) -> java.util.List['StrupeOkeReport.Recommendation']: ...
    def getTotalExpectedUplift(self) -> float: ...
    def setChokeTolerance(self, double: float) -> 'StrupeOkeReport': ...
    def toJson(self) -> java.lang.String: ...
    def toTable(self) -> java.lang.String: ...
    class Action(java.lang.Enum['StrupeOkeReport.Action']):
        OPEN: typing.ClassVar['StrupeOkeReport.Action'] = ...
        CHOKE_BACK: typing.ClassVar['StrupeOkeReport.Action'] = ...
        SHUT: typing.ClassVar['StrupeOkeReport.Action'] = ...
        NO_CHANGE: typing.ClassVar['StrupeOkeReport.Action'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'StrupeOkeReport.Action': ...
        @staticmethod
        def values() -> typing.MutableSequence['StrupeOkeReport.Action']: ...
    class Recommendation(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], action: 'StrupeOkeReport.Action', double: float, double2: float, double3: float, double4: float, double5: float, double6: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def getAction(self) -> 'StrupeOkeReport.Action': ...
        def getBindingConstraint(self) -> java.lang.String: ...
        def getCurrentChokeFraction(self) -> float: ...
        def getCurrentOil(self) -> float: ...
        def getExpectedUplift(self) -> float: ...
        def getLockReason(self) -> java.lang.String: ...
        def getOptimizedOil(self) -> float: ...
        def getRecommendedChokeFraction(self) -> float: ...
        def getRecommendedLiftRate(self) -> float: ...
        def getWellName(self) -> java.lang.String: ...

class WellDeliverabilityCurve(java.io.Serializable):
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    @staticmethod
    def fromArrays(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> 'WellDeliverabilityCurve': ...
    @staticmethod
    def fromVogel(double: float, double2: float) -> 'WellDeliverabilityCurve': ...
    @staticmethod
    def fromWellSystem(wellSystem: jneqsim.process.equipment.reservoir.WellSystem, double: float, double2: float, int: int) -> 'WellDeliverabilityCurve': ...
    def getAbsoluteOpenFlowPotential(self) -> float: ...
    def getShutInPressure(self) -> float: ...
    def rateAt(self, double: float) -> float: ...
    def slopeAt(self, double: float) -> float: ...

class WellTestMatcher(java.io.Serializable):
    def __init__(self): ...
    def addTestPoint(self, double: float, double2: float) -> 'WellTestMatcher': ...
    def fitProductivityIndex(self) -> 'WellTestMatcher.MatchResult': ...
    def fitVogel(self) -> 'WellTestMatcher.MatchResult': ...
    class MatchResult(java.io.Serializable):
        def __init__(self, wellDeliverabilityCurve: WellDeliverabilityCurve, double: float, double2: float, double3: float, string: typing.Union[java.lang.String, str]): ...
        def getCurve(self) -> WellDeliverabilityCurve: ...
        def getDeliverabilityParameter(self) -> float: ...
        def getModel(self) -> java.lang.String: ...
        def getReservoirPressure(self) -> float: ...
        def getRmsError(self) -> float: ...

class AquiferDrive(ReservoirDrive):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float): ...
    def getCumulativeInflux(self) -> float: ...
    def getCumulativeProduction(self) -> float: ...
    def getInPlaceVolume(self) -> float: ...
    def getReservoirPressure(self) -> float: ...
    def produce(self, double: float, double2: float) -> None: ...

class FlowlineBranch(NetworkBranch):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float): ...
    def flow(self, double: float, double2: float) -> float: ...
    @staticmethod
    def fromBeggsBrillSample(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], pipeBeggsAndBrills: jneqsim.process.equipment.pipeline.PipeBeggsAndBrills) -> 'FlowlineBranch': ...
    @staticmethod
    def fromReferencePoint(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float) -> 'FlowlineBranch': ...
    def getFromNode(self) -> java.lang.String: ...
    def getLastRate(self) -> float: ...
    def getLinearCoeff(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getQuadraticCoeff(self) -> float: ...
    def getStaticHead(self) -> float: ...
    def getToNode(self) -> java.lang.String: ...

class MaterialBalanceGasDrive(ReservoirDrive):
    def __init__(self, double: float, double2: float, double3: float): ...
    def getCumulativeProduction(self) -> float: ...
    def getInPlaceVolume(self) -> float: ...
    def getReservoirPressure(self) -> float: ...
    def produce(self, double: float, double2: float) -> None: ...

class OilTankDrive(ReservoirDrive):
    def __init__(self, double: float, double2: float, double3: float, double4: float): ...
    def getCumulativeProduction(self) -> float: ...
    def getInPlaceVolume(self) -> float: ...
    def getReservoirPressure(self) -> float: ...
    def produce(self, double: float, double2: float) -> None: ...

class WellBranch(NetworkBranch):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], wellDeliverabilityCurve: WellDeliverabilityCurve, double: float): ...
    def flow(self, double: float, double2: float) -> float: ...
    def getChokeFactor(self) -> float: ...
    def getCurve(self) -> WellDeliverabilityCurve: ...
    def getFromNode(self) -> java.lang.String: ...
    def getLastRate(self) -> float: ...
    def getLiftFactor(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getToNode(self) -> java.lang.String: ...
    def setChokeFactor(self, double: float) -> None: ...
    def setLiftFactor(self, double: float) -> None: ...
    def setReferenceReservoirPressure(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.fielddevelopment.integrated")``.

    AquiferDrive: typing.Type[AquiferDrive]
    ChokeAndGasLiftAllocationOptimizer: typing.Type[ChokeAndGasLiftAllocationOptimizer]
    ChokeableGasLiftWell: typing.Type[ChokeableGasLiftWell]
    FlowlineBranch: typing.Type[FlowlineBranch]
    GasLiftNetworkOptimizer: typing.Type[GasLiftNetworkOptimizer]
    GasLiftPerformanceCurve: typing.Type[GasLiftPerformanceCurve]
    IntegratedProductionModel: typing.Type[IntegratedProductionModel]
    IntegratedSolveResult: typing.Type[IntegratedSolveResult]
    MaterialBalanceGasDrive: typing.Type[MaterialBalanceGasDrive]
    NetworkBranch: typing.Type[NetworkBranch]
    NetworkNewtonSolver: typing.Type[NetworkNewtonSolver]
    NetworkNode: typing.Type[NetworkNode]
    OilTankDrive: typing.Type[OilTankDrive]
    ProductionProfile: typing.Type[ProductionProfile]
    ReservoirDrive: typing.Type[ReservoirDrive]
    ReservoirToMarketOptimizer: typing.Type[ReservoirToMarketOptimizer]
    StrupeOkeReport: typing.Type[StrupeOkeReport]
    WellBranch: typing.Type[WellBranch]
    WellDeliverabilityCurve: typing.Type[WellDeliverabilityCurve]
    WellTestMatcher: typing.Type[WellTestMatcher]
