
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import datetime
import java.io
import java.lang
import java.nio.file
import java.time
import java.util
import jpype.protocol
import jneqsim.process.engineering.model
import typing



class ModelChangeEvent(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    SCHEMA_URI: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], eventType: 'ModelChangeEvent.EventType', instant: typing.Union[java.time.Instant, datetime.datetime], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str], string8: typing.Union[java.lang.String, str], string9: typing.Union[java.lang.String, str], string10: typing.Union[java.lang.String, str], list: java.util.List['ModelChangeSubject'], list2: java.util.List[typing.Union[java.lang.String, str]], list3: java.util.List[typing.Union[java.lang.String, str]]): ...
    @staticmethod
    def fromEngineeringGraphDiff(engineeringGraphDiff: jneqsim.process.engineering.model.EngineeringGraphDiff, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], instant: typing.Union[java.time.Instant, datetime.datetime], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str]) -> 'ModelChangeEvent': ...
    @staticmethod
    def fromJson(string: typing.Union[java.lang.String, str]) -> 'ModelChangeEvent': ...
    def getActor(self) -> java.lang.String: ...
    def getAssetId(self) -> java.lang.String: ...
    def getBaseRevision(self) -> java.lang.String: ...
    def getCorrelationId(self) -> java.lang.String: ...
    def getEventId(self) -> java.lang.String: ...
    def getEventType(self) -> 'ModelChangeEvent.EventType': ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getIdempotencyKey(self) -> java.lang.String: ...
    def getImpactHintNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getModelId(self) -> java.lang.String: ...
    def getOccurredAt(self) -> java.time.Instant: ...
    def getPayloadFingerprint(self) -> java.lang.String: ...
    def getReason(self) -> java.lang.String: ...
    def getSourceSystem(self) -> java.lang.String: ...
    def getSubjects(self) -> java.util.List['ModelChangeSubject']: ...
    def getTargetRevision(self) -> java.lang.String: ...
    def toCompactJson(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class EventType(java.lang.Enum['ModelChangeEvent.EventType']):
        MODEL_CREATED: typing.ClassVar['ModelChangeEvent.EventType'] = ...
        MODEL_REVISED: typing.ClassVar['ModelChangeEvent.EventType'] = ...
        DEPENDENCY_CHANGED: typing.ClassVar['ModelChangeEvent.EventType'] = ...
        QUALIFICATION_CHANGED: typing.ClassVar['ModelChangeEvent.EventType'] = ...
        MODEL_ARCHIVED: typing.ClassVar['ModelChangeEvent.EventType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ModelChangeEvent.EventType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ModelChangeEvent.EventType']: ...

class ModelChangeEventPublisher:
    def publish(self, modelChangeEvent: ModelChangeEvent) -> 'ModelChangePublishResult': ...

class ModelChangeEventSubscriber:
    def onModelChange(self, modelChangeEvent: ModelChangeEvent) -> None: ...

class ModelChangePublishResult(java.io.Serializable):
    def getDeliveryCount(self) -> int: ...
    def getDeliveryFailures(self) -> java.util.List[java.lang.String]: ...
    def getEventId(self) -> java.lang.String: ...
    def getStatus(self) -> 'ModelChangePublishResult.Status': ...
    class Status(java.lang.Enum['ModelChangePublishResult.Status']):
        PUBLISHED: typing.ClassVar['ModelChangePublishResult.Status'] = ...
        DUPLICATE: typing.ClassVar['ModelChangePublishResult.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ModelChangePublishResult.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['ModelChangePublishResult.Status']: ...

class ModelChangeSubject(java.io.Serializable, java.lang.Comparable['ModelChangeSubject']):
    def __init__(self, string: typing.Union[java.lang.String, str], subjectType: 'ModelChangeSubject.SubjectType', string2: typing.Union[java.lang.String, str], changeKind: 'ModelChangeSubject.ChangeKind', list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def compareTo(self, modelChangeSubject: 'ModelChangeSubject') -> int: ...
    def getChangeKind(self) -> 'ModelChangeSubject.ChangeKind': ...
    def getChangedProperties(self) -> java.util.List[java.lang.String]: ...
    def getObjectKind(self) -> java.lang.String: ...
    def getSubjectId(self) -> java.lang.String: ...
    def getSubjectType(self) -> 'ModelChangeSubject.SubjectType': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class ChangeKind(java.lang.Enum['ModelChangeSubject.ChangeKind']):
        ADDED: typing.ClassVar['ModelChangeSubject.ChangeKind'] = ...
        MODIFIED: typing.ClassVar['ModelChangeSubject.ChangeKind'] = ...
        REMOVED: typing.ClassVar['ModelChangeSubject.ChangeKind'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ModelChangeSubject.ChangeKind': ...
        @staticmethod
        def values() -> typing.MutableSequence['ModelChangeSubject.ChangeKind']: ...
    class SubjectType(java.lang.Enum['ModelChangeSubject.SubjectType']):
        ENGINEERING_NODE: typing.ClassVar['ModelChangeSubject.SubjectType'] = ...
        ENGINEERING_EDGE: typing.ClassVar['ModelChangeSubject.SubjectType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ModelChangeSubject.SubjectType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ModelChangeSubject.SubjectType']: ...

class InMemoryModelChangeEventBus(ModelChangeEventPublisher):
    def __init__(self): ...
    def getHistory(self) -> java.util.List[ModelChangeEvent]: ...
    def publish(self, modelChangeEvent: ModelChangeEvent) -> ModelChangePublishResult: ...
    def replayAfter(self, string: typing.Union[java.lang.String, str], modelChangeEventSubscriber: typing.Union[ModelChangeEventSubscriber, typing.Callable]) -> int: ...
    def subscribe(self, modelChangeEventSubscriber: typing.Union[ModelChangeEventSubscriber, typing.Callable]) -> None: ...
    def unsubscribe(self, modelChangeEventSubscriber: typing.Union[ModelChangeEventSubscriber, typing.Callable]) -> None: ...

class ModelChangeEventJournal(ModelChangeEventPublisher):
    def __init__(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]): ...
    def getHistory(self) -> java.util.List[ModelChangeEvent]: ...
    def publish(self, modelChangeEvent: ModelChangeEvent) -> ModelChangePublishResult: ...
    def replay(self, modelChangeEventSubscriber: typing.Union[ModelChangeEventSubscriber, typing.Callable]) -> int: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.processmodel.lifecycle.event")``.

    InMemoryModelChangeEventBus: typing.Type[InMemoryModelChangeEventBus]
    ModelChangeEvent: typing.Type[ModelChangeEvent]
    ModelChangeEventJournal: typing.Type[ModelChangeEventJournal]
    ModelChangeEventPublisher: typing.Type[ModelChangeEventPublisher]
    ModelChangeEventSubscriber: typing.Type[ModelChangeEventSubscriber]
    ModelChangePublishResult: typing.Type[ModelChangePublishResult]
    ModelChangeSubject: typing.Type[ModelChangeSubject]
