
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.characterization
import typing



class AnaerobicDigestionInput(java.io.Serializable):
    def __init__(self, bioFeedstock: jneqsim.thermo.characterization.BioFeedstock, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float): ...
    def getFeedstock(self) -> jneqsim.thermo.characterization.BioFeedstock: ...
    def getHydraulicRetentionTimeDays(self) -> float: ...
    def getMethaneFractionOverride(self) -> float: ...
    def getMethaneYieldOverride(self) -> float: ...
    def getSulfurToGasFraction(self) -> float: ...
    def getTemperatureK(self) -> float: ...
    def getVsDestructionOverride(self) -> float: ...
    def getWetFeedRateKgPerHr(self) -> float: ...

class AnaerobicDigestionModel(java.io.Serializable):
    def calculate(self, anaerobicDigestionInput: AnaerobicDigestionInput) -> 'AnaerobicDigestionResult': ...
    def getEvidenceReference(self) -> java.lang.String: ...
    def getFidelity(self) -> 'ModelFidelity': ...
    def getModelIdentifier(self) -> java.lang.String: ...

class AnaerobicDigestionResult(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], modelFidelity: 'ModelFidelity', double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, list: java.util.List[typing.Union[java.lang.String, str]]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], modelFidelity: 'ModelFidelity', string2: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getCarbonClosureFraction(self) -> float: ...
    def getCarbonDioxideNm3PerDay(self) -> float: ...
    def getDestroyedVsKgPerDay(self) -> float: ...
    def getDigestateKgPerDay(self) -> float: ...
    def getDigestateSolidsKgPerDay(self) -> float: ...
    def getDryBiogasNm3PerDay(self) -> float: ...
    def getFidelity(self) -> 'ModelFidelity': ...
    def getHydrogenSulfideNm3PerDay(self) -> float: ...
    def getMassClosureFraction(self) -> float: ...
    def getMethaneFraction(self) -> float: ...
    def getMethaneNm3PerDay(self) -> float: ...
    def getModelEvidenceReference(self) -> java.lang.String: ...
    def getModelIdentifier(self) -> java.lang.String: ...
    def getTotalSolidsKgPerDay(self) -> float: ...
    def getVolatileSolidsKgPerDay(self) -> float: ...
    def getVsDestruction(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def getWetFeedKgPerDay(self) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class FirstOrderHydrolysisModelCalibrator(java.io.Serializable):
    def __init__(self): ...
    def addObservation(self, double: float, double2: float, double3: float) -> 'FirstOrderHydrolysisModelCalibrator': ...
    def calibrate(self, string: typing.Union[java.lang.String, str]) -> 'FirstOrderHydrolysisModelCalibrator.CalibrationResult': ...
    def getObservations(self) -> java.util.List['FirstOrderHydrolysisModelCalibrator.CalibrationObservation']: ...
    def setHydrolysisRateBounds(self, double: float, double2: float) -> None: ...
    def setTemperatureCorrection(self, double: float, double2: float) -> None: ...
    class CalibrationObservation(java.io.Serializable):
        def getHydraulicRetentionTimeDays(self) -> float: ...
        def getMeasuredVsDestruction(self) -> float: ...
        def getTemperatureK(self) -> float: ...
    class CalibrationResult(java.io.Serializable):
        def getModel(self) -> 'CalibratedFirstOrderHydrolysisDigestionModel': ...
        def getObservationCount(self) -> int: ...
        def getRSquared(self) -> float: ...
        def getRootMeanSquaredError(self) -> float: ...
        def isHydrolysisRateAtSearchBoundary(self) -> bool: ...

class ModelFidelity(java.lang.Enum['ModelFidelity']):
    SCREENING: typing.ClassVar['ModelFidelity'] = ...
    ENGINEERING: typing.ClassVar['ModelFidelity'] = ...
    CALIBRATED: typing.ClassVar['ModelFidelity'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'ModelFidelity': ...
    @staticmethod
    def values() -> typing.MutableSequence['ModelFidelity']: ...

class EmpiricalYieldDigestionModel(AnaerobicDigestionModel):
    def __init__(self): ...
    def calculate(self, anaerobicDigestionInput: AnaerobicDigestionInput) -> AnaerobicDigestionResult: ...
    def getFidelity(self) -> ModelFidelity: ...
    def getModelIdentifier(self) -> java.lang.String: ...

class FirstOrderHydrolysisDigestionModel(EmpiricalYieldDigestionModel):
    def __init__(self): ...
    def calculate(self, anaerobicDigestionInput: AnaerobicDigestionInput) -> AnaerobicDigestionResult: ...
    def getFidelity(self) -> ModelFidelity: ...
    def getModelIdentifier(self) -> java.lang.String: ...
    def setTemperatureCorrection(self, double: float, double2: float) -> None: ...

class CalibratedFirstOrderHydrolysisDigestionModel(FirstOrderHydrolysisDigestionModel):
    def __init__(self, double: float, double2: float, string: typing.Union[java.lang.String, str], double3: float, double4: float, double5: float, double6: float, double7: float, double8: float): ...
    def getEvidenceReference(self) -> java.lang.String: ...
    def getFidelity(self) -> ModelFidelity: ...
    def getHydrolysisRatePerDay(self) -> float: ...
    def getMaximumRetentionTimeDays(self) -> float: ...
    def getMaximumTemperatureK(self) -> float: ...
    def getMaximumVsDestruction(self) -> float: ...
    def getMinimumRetentionTimeDays(self) -> float: ...
    def getMinimumTemperatureK(self) -> float: ...
    def getModelIdentifier(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.reactor.digestion")``.

    AnaerobicDigestionInput: typing.Type[AnaerobicDigestionInput]
    AnaerobicDigestionModel: typing.Type[AnaerobicDigestionModel]
    AnaerobicDigestionResult: typing.Type[AnaerobicDigestionResult]
    CalibratedFirstOrderHydrolysisDigestionModel: typing.Type[CalibratedFirstOrderHydrolysisDigestionModel]
    EmpiricalYieldDigestionModel: typing.Type[EmpiricalYieldDigestionModel]
    FirstOrderHydrolysisDigestionModel: typing.Type[FirstOrderHydrolysisDigestionModel]
    FirstOrderHydrolysisModelCalibrator: typing.Type[FirstOrderHydrolysisModelCalibrator]
    ModelFidelity: typing.Type[ModelFidelity]
