
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering
import jneqsim.process.engineering.impact
import jneqsim.process.engineering.model
import jneqsim.process.processmodel.lifecycle.event
import jneqsim.process.safety.risk.sis
import typing



class HazopLopaSrsWorkflow:
    @staticmethod
    def run(lopaScenarioDefinition: 'LopaScenarioDefinition', srsDesignInputs: 'HazopLopaSrsWorkflow.SrsDesignInputs') -> 'HazopLopaSrsWorkflow.Result': ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def getLopaResult(self) -> jneqsim.process.safety.risk.sis.LOPAResult: ...
        def getSrsDraft(self) -> 'SafetyRequirementSpecificationDraft': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SrsDesignInputs(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
        class Builder:
            def build(self) -> 'HazopLopaSrsWorkflow.SrsDesignInputs': ...
            def bypassPolicy(self, string: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def maximumResponseTimeSeconds(self, double: float) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def proofTestIntervalHours(self, double: float) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def resetPolicy(self, string: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def safeState(self, string: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def trip(self, string: typing.Union[java.lang.String, str], tripDirection: 'SafetyRequirementSpecificationDraft.TripDirection', double: float, string2: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...
            def votingArchitecture(self, string: typing.Union[java.lang.String, str]) -> 'HazopLopaSrsWorkflow.SrsDesignInputs.Builder': ...

class LopaScenarioDefinition(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'LopaScenarioDefinition.Builder': ...
    def getConsequence(self) -> java.lang.String: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getFrequencyBasisReference(self) -> java.lang.String: ...
    def getHazopDeviationId(self) -> java.lang.String: ...
    def getHazopNodeId(self) -> java.lang.String: ...
    def getInitiatingEvent(self) -> java.lang.String: ...
    def getInitiatingEventFrequencyPerYear(self) -> float: ...
    def getProtectionLayers(self) -> java.util.List['ProtectionLayerDefinition']: ...
    def getScenarioId(self) -> java.lang.String: ...
    def getTargetFrequencyPerYear(self) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def addProtectionLayer(self, protectionLayerDefinition: 'ProtectionLayerDefinition') -> 'LopaScenarioDefinition.Builder': ...
        def build(self) -> 'LopaScenarioDefinition': ...
        def consequence(self, string: typing.Union[java.lang.String, str]) -> 'LopaScenarioDefinition.Builder': ...
        def equipmentTag(self, string: typing.Union[java.lang.String, str]) -> 'LopaScenarioDefinition.Builder': ...
        def frequencyBasisReference(self, string: typing.Union[java.lang.String, str]) -> 'LopaScenarioDefinition.Builder': ...
        def initiatingEvent(self, string: typing.Union[java.lang.String, str], double: float) -> 'LopaScenarioDefinition.Builder': ...
        def targetFrequencyPerYear(self, double: float) -> 'LopaScenarioDefinition.Builder': ...

class ProtectionLayerDefinition(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], layerType: 'ProtectionLayerDefinition.LayerType', double: float) -> 'ProtectionLayerDefinition.Builder': ...
    def getCreditFindings(self) -> java.util.List[java.lang.String]: ...
    def getId(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getProbabilityOfFailureOnDemand(self) -> float: ...
    def isCreditEligible(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def auditable(self, boolean: bool) -> 'ProtectionLayerDefinition.Builder': ...
        def build(self) -> 'ProtectionLayerDefinition': ...
        def evidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'ProtectionLayerDefinition.Builder': ...
        def independentFromInitiatingEvent(self, boolean: bool) -> 'ProtectionLayerDefinition.Builder': ...
        def independentFromOtherLayers(self, boolean: bool) -> 'ProtectionLayerDefinition.Builder': ...
        def proofTestIntervalHours(self, double: float) -> 'ProtectionLayerDefinition.Builder': ...
        def specific(self, boolean: bool) -> 'ProtectionLayerDefinition.Builder': ...
    class LayerType(java.lang.Enum['ProtectionLayerDefinition.LayerType']):
        BPCS: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        ALARM_AND_OPERATOR: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        RELIEF: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        MECHANICAL: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        EXISTING_SIS: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        PROCEDURAL: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        OTHER: typing.ClassVar['ProtectionLayerDefinition.LayerType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ProtectionLayerDefinition.LayerType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ProtectionLayerDefinition.LayerType']: ...

class SafetyRequirementSpecificationDraft(java.io.Serializable):
    def getApprovalStatus(self) -> jneqsim.process.engineering.EngineeringApprovalStatus: ...
    def getRequiredSil(self) -> int: ...
    def getSifTag(self) -> java.lang.String: ...
    def getSrsRequirementId(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class TripDirection(java.lang.Enum['SafetyRequirementSpecificationDraft.TripDirection']):
        HIGH: typing.ClassVar['SafetyRequirementSpecificationDraft.TripDirection'] = ...
        LOW: typing.ClassVar['SafetyRequirementSpecificationDraft.TripDirection'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyRequirementSpecificationDraft.TripDirection': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyRequirementSpecificationDraft.TripDirection']: ...

class SafetyStudyRevalidationPlanner:
    SAFETY_STUDY_TYPE_PROPERTY: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, generalizedImpactAnalyzer: jneqsim.process.engineering.impact.GeneralizedImpactAnalyzer): ...
    def plan(self, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, modelChangeEvent: jneqsim.process.processmodel.lifecycle.event.ModelChangeEvent) -> 'SafetyStudyRevalidationPlanner.Result': ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def getImpactAnalysis(self) -> jneqsim.process.engineering.impact.ImpactAnalysisResult: ...
        def getTasks(self) -> java.util.List['SafetyStudyRevalidationPlanner.Task']: ...
        def isRevalidationRequired(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class SafetyRevalidationAction(java.lang.Enum['SafetyStudyRevalidationPlanner.SafetyRevalidationAction']):
        REVIEW_SCENARIO_SET: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RECHECK_IPL_ELIGIBILITY: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RECALCULATE_FREQUENCY: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        REVISE_REQUIREMENTS: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RECALCULATE_PFD_PFH_UNCERTAINTY: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RECHECK_DEGRADED_MODES: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RERUN_CLOSED_LOOP_SCENARIOS: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        REVIEW_SAFE_STATE_AND_DEADLINE: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        RECALCULATE_RELIEF_AND_TRANSIENT_DISPOSAL: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        REVIEW_CONCURRENCY_AND_CAPACITY: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        REBUILD_FACILITY_HANDOFF: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        REAPPROVE: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyRevalidationAction'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyStudyRevalidationPlanner.SafetyRevalidationAction': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyStudyRevalidationPlanner.SafetyRevalidationAction']: ...
    class SafetyStudyType(java.lang.Enum['SafetyStudyRevalidationPlanner.SafetyStudyType']):
        HAZOP: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        LOPA: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        SRS: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        SIF_RELIABILITY: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        SIF_DYNAMIC_VERIFICATION: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        RELIEF_BLOWDOWN_FLARE: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        FACILITY_RESPONSE: typing.ClassVar['SafetyStudyRevalidationPlanner.SafetyStudyType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyStudyRevalidationPlanner.SafetyStudyType': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyStudyRevalidationPlanner.SafetyStudyType']: ...
    class Task(java.io.Serializable):
        def getNodeId(self) -> java.lang.String: ...
        def getSafetyActions(self) -> java.util.List['SafetyStudyRevalidationPlanner.SafetyRevalidationAction']: ...
        def getStudyType(self) -> 'SafetyStudyRevalidationPlanner.SafetyStudyType': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.safety.lifecycle")``.

    HazopLopaSrsWorkflow: typing.Type[HazopLopaSrsWorkflow]
    LopaScenarioDefinition: typing.Type[LopaScenarioDefinition]
    ProtectionLayerDefinition: typing.Type[ProtectionLayerDefinition]
    SafetyRequirementSpecificationDraft: typing.Type[SafetyRequirementSpecificationDraft]
    SafetyStudyRevalidationPlanner: typing.Type[SafetyStudyRevalidationPlanner]
