
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.model
import jneqsim.process.processmodel.lifecycle.event
import typing



class GeneralizedImpactAnalyzer:
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, list: java.util.List['ImpactAnalysisRule']): ...
    @typing.overload
    def analyze(self, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, collection: typing.Union[java.util.Collection[typing.Union[java.lang.String, str]], typing.Sequence[typing.Union[java.lang.String, str]], typing.Set[typing.Union[java.lang.String, str]]]) -> 'ImpactAnalysisResult': ...
    @typing.overload
    def analyze(self, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, modelChangeEvent: jneqsim.process.processmodel.lifecycle.event.ModelChangeEvent) -> 'ImpactAnalysisResult': ...
    @staticmethod
    def defaultRules() -> java.util.List['ImpactAnalysisRule']: ...
    def getRules(self) -> java.util.List['ImpactAnalysisRule']: ...

class ImpactAction(java.lang.Enum['ImpactAction']):
    REVIEW_CHANGE: typing.ClassVar['ImpactAction'] = ...
    RECALCULATE: typing.ClassVar['ImpactAction'] = ...
    REGENERATE: typing.ClassVar['ImpactAction'] = ...
    REVALIDATE: typing.ClassVar['ImpactAction'] = ...
    REAPPROVE: typing.ClassVar['ImpactAction'] = ...
    REQUALIFY: typing.ClassVar['ImpactAction'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'ImpactAction': ...
    @staticmethod
    def values() -> typing.MutableSequence['ImpactAction']: ...

class ImpactAnalysisResult(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    SCHEMA_URI: typing.ClassVar[java.lang.String] = ...
    def getEventId(self) -> java.lang.String: ...
    def getGraphRevision(self) -> java.lang.String: ...
    def getImpact(self, string: typing.Union[java.lang.String, str]) -> 'ImpactedEngineeringObject': ...
    def getImpactedObjects(self) -> java.util.List['ImpactedEngineeringObject']: ...
    def getProjectId(self) -> java.lang.String: ...
    def getPropagationCycleEdgeIds(self) -> java.util.List[java.lang.String]: ...
    def getReapprovalNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getRecalculationCycleNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getRecalculationOrder(self) -> java.util.List[java.lang.String]: ...
    def getUnresolvedSubjectIds(self) -> java.util.List[java.lang.String]: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ImpactAnalysisRule(java.io.Serializable):
    def __init__(self, kind: jneqsim.process.engineering.model.EngineeringEdge.Kind, direction: 'ImpactAnalysisRule.Direction', impactAction: ImpactAction): ...
    def getAction(self) -> ImpactAction: ...
    def getDirection(self) -> 'ImpactAnalysisRule.Direction': ...
    def getRelationship(self) -> jneqsim.process.engineering.model.EngineeringEdge.Kind: ...
    class Direction(java.lang.Enum['ImpactAnalysisRule.Direction']):
        SOURCE_TO_TARGET: typing.ClassVar['ImpactAnalysisRule.Direction'] = ...
        TARGET_TO_SOURCE: typing.ClassVar['ImpactAnalysisRule.Direction'] = ...
        BIDIRECTIONAL: typing.ClassVar['ImpactAnalysisRule.Direction'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ImpactAnalysisRule.Direction': ...
        @staticmethod
        def values() -> typing.MutableSequence['ImpactAnalysisRule.Direction']: ...

class ImpactedEngineeringObject(java.io.Serializable):
    def getNodeId(self) -> java.lang.String: ...
    def getNodeKind(self) -> jneqsim.process.engineering.model.EngineeringNode.Kind: ...
    def getPropagationDepth(self) -> int: ...
    def getPropagationPath(self) -> java.util.List[java.lang.String]: ...
    def getReasonEdgeIds(self) -> java.util.List[java.lang.String]: ...
    def getRequiredActions(self) -> java.util.List[ImpactAction]: ...
    def isDirectChange(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.impact")``.

    GeneralizedImpactAnalyzer: typing.Type[GeneralizedImpactAnalyzer]
    ImpactAction: typing.Type[ImpactAction]
    ImpactAnalysisResult: typing.Type[ImpactAnalysisResult]
    ImpactAnalysisRule: typing.Type[ImpactAnalysisRule]
    ImpactedEngineeringObject: typing.Type[ImpactedEngineeringObject]
