
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment.separator.entrainment
import typing



class DemistingInternal(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def applyDatabaseRecord(self, internalsRecord: jneqsim.process.equipment.separator.entrainment.SeparatorInternalsDatabase.InternalsRecord) -> None: ...
    def calcGasVelocity(self, double: float, double2: float, double3: float) -> float: ...
    def calcLiquidCarryOver(self, double: float, double2: float) -> float: ...
    def calcPressureDrop(self, double: float, double2: float) -> float: ...
    @staticmethod
    def fromDatabase(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'DemistingInternal': ...
    @staticmethod
    def fromDatabaseType(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getArea(self) -> float: ...
    def getD50Um(self) -> float: ...
    def getEuNumber(self) -> float: ...
    def getKFactor(self) -> float: ...
    def getMaxEfficiency(self) -> float: ...
    def getMaxKFactor(self) -> float: ...
    def getMinKFactor(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getOperatingWindow(self, double: float) -> 'InternalOperatingWindow': ...
    def getReference(self) -> java.lang.String: ...
    def getSharpness(self) -> float: ...
    def getSubType(self) -> java.lang.String: ...
    def getThickness(self) -> float: ...
    def getType(self) -> java.lang.String: ...
    def getVoidFraction(self) -> float: ...
    def getWireDiameter(self) -> float: ...
    def setArea(self, double: float) -> None: ...
    def setD50Um(self, double: float) -> None: ...
    def setEuNumber(self, double: float) -> None: ...
    def setKFactor(self, double: float) -> None: ...
    def setMaxEfficiency(self, double: float) -> None: ...
    def setMaxKFactor(self, double: float) -> None: ...
    def setMinKFactor(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setReference(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSharpness(self, double: float) -> None: ...
    def setSubType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThickness(self, double: float) -> None: ...
    def setType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setVoidFraction(self, double: float) -> None: ...
    def setWireDiameter(self, double: float) -> None: ...
    @staticmethod
    def toDatabaseType(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...

class InternalOperatingWindow(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, string4: typing.Union[java.lang.String, str]): ...
    def classify(self) -> None: ...
    def getMaxKFactor(self) -> float: ...
    def getMinKFactor(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getOperatingKFactor(self) -> float: ...
    def getRatedEfficiency(self) -> float: ...
    def getReference(self) -> java.lang.String: ...
    def getStatus(self) -> 'InternalOperatingWindow.WindowStatus': ...
    def getSubType(self) -> java.lang.String: ...
    def getTurndownRatio(self) -> float: ...
    def getType(self) -> java.lang.String: ...
    def getUtilization(self) -> float: ...
    def isInRange(self) -> bool: ...
    def setMaxKFactor(self, double: float) -> None: ...
    def setMinKFactor(self, double: float) -> None: ...
    def setName(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setOperatingKFactor(self, double: float) -> None: ...
    def setRatedEfficiency(self, double: float) -> None: ...
    def setReference(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSubType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class WindowStatus(java.lang.Enum['InternalOperatingWindow.WindowStatus']):
        BELOW_MIN_TURNDOWN: typing.ClassVar['InternalOperatingWindow.WindowStatus'] = ...
        IN_RANGE: typing.ClassVar['InternalOperatingWindow.WindowStatus'] = ...
        ABOVE_MAX_FLOODING: typing.ClassVar['InternalOperatingWindow.WindowStatus'] = ...
        UNKNOWN: typing.ClassVar['InternalOperatingWindow.WindowStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'InternalOperatingWindow.WindowStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['InternalOperatingWindow.WindowStatus']: ...

class DemistingInternalWithDrainage(DemistingInternal):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def calcLiquidCarryOver(self, double: float, double2: float) -> float: ...
    def getDrainageEfficiency(self) -> float: ...
    def setDrainageEfficiency(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.mechanicaldesign.separator.internals")``.

    DemistingInternal: typing.Type[DemistingInternal]
    DemistingInternalWithDrainage: typing.Type[DemistingInternalWithDrainage]
    InternalOperatingWindow: typing.Type[InternalOperatingWindow]
