
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import jpype
import jneqsim.fluidmechanics.flowsolver
import jneqsim.fluidmechanics.flowsolver.onephaseflowsolver
import jneqsim.fluidmechanics.flowsystem.onephaseflowsystem.pipeflowsystem
import jneqsim.thermo
import typing



class OnePhaseFlowConvergenceReport(java.io.Serializable):
    def __init__(self, convergenceReason: 'OnePhaseFlowConvergenceReport.ConvergenceReason', boolean: bool, int: int, int2: int, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, double11: float, double12: float, double13: float, double14: float, double15: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], string: typing.Union[java.lang.String, str]): ...
    def getDensityRelativeTolerance(self) -> float: ...
    def getDensityResidualHistory(self) -> typing.MutableSequence[float]: ...
    def getFinalFiniteVolumeMassKg(self) -> float: ...
    def getFinalThermodynamicMassKg(self) -> float: ...
    def getFiniteVolumeMassResidualKg(self) -> float: ...
    def getInitialFiniteVolumeMassKg(self) -> float: ...
    def getInletBoundaryMassKg(self) -> float: ...
    def getMassBalanceRelativeTolerance(self) -> float: ...
    def getMaximumRelativeDensityResidual(self) -> float: ...
    def getMaximumRelativeNonlinearUpdate(self) -> float: ...
    def getMaximumScaledMassEquationResidual(self) -> float: ...
    def getMaximumScaledMomentumEquationResidual(self) -> float: ...
    def getMessage(self) -> java.lang.String: ...
    def getNetBoundaryMassKg(self) -> float: ...
    def getNonlinearIterations(self) -> int: ...
    def getNonlinearUpdateHistory(self) -> typing.MutableSequence[float]: ...
    def getNonlinearUpdateTolerance(self) -> float: ...
    def getOutletBoundaryMassKg(self) -> float: ...
    def getReason(self) -> 'OnePhaseFlowConvergenceReport.ConvergenceReason': ...
    def getRelativeFiniteVolumeMassResidual(self) -> float: ...
    def getRelativeThermodynamicMassResidual(self) -> float: ...
    def getScaledMassEquationResidualHistory(self) -> typing.MutableSequence[float]: ...
    def getScaledMomentumEquationResidualHistory(self) -> typing.MutableSequence[float]: ...
    def getSolverType(self) -> int: ...
    def getThermodynamicMassResidualKg(self) -> float: ...
    def isConverged(self) -> bool: ...
    def isDynamic(self) -> bool: ...
    def isNonlinearMetricEquationResidual(self) -> bool: ...
    @staticmethod
    def notRun() -> 'OnePhaseFlowConvergenceReport': ...
    def toJson(self) -> java.lang.String: ...
    class ConvergenceReason(java.lang.Enum['OnePhaseFlowConvergenceReport.ConvergenceReason']):
        NOT_RUN: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        CONVERGED: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        MAX_ITERATIONS_REACHED: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        LINE_SEARCH_FAILED: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        NUMERICAL_FAILURE: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        NON_FINITE_RESIDUAL: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        DENSITY_INCONSISTENT: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        MASS_BALANCE_FAILED: typing.ClassVar['OnePhaseFlowConvergenceReport.ConvergenceReason'] = ...
        def isConverged(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OnePhaseFlowConvergenceReport.ConvergenceReason': ...
        @staticmethod
        def values() -> typing.MutableSequence['OnePhaseFlowConvergenceReport.ConvergenceReason']: ...

class OnePhasePipeFlowSolver(jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.OnePhaseFlowSolver):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pipeFlowSystem: jneqsim.fluidmechanics.flowsystem.onephaseflowsystem.pipeflowsystem.PipeFlowSystem, double: float, int: int): ...
    def clone(self) -> 'OnePhasePipeFlowSolver': ...

class OnePhaseSpeciesConservationReport(java.io.Serializable):
    def getComponentNames(self) -> typing.MutableSequence[java.lang.String]: ...
    def getCouplingIterations(self) -> int: ...
    def getDensityResidualHistory(self) -> typing.MutableSequence[float]: ...
    def getFinalInventoryKg(self) -> typing.MutableSequence[float]: ...
    def getInitialInventoryKg(self) -> typing.MutableSequence[float]: ...
    def getInletBoundaryMassKg(self) -> typing.MutableSequence[float]: ...
    def getInventoryResidualKg(self) -> typing.MutableSequence[float]: ...
    def getMassFractionProfile(self) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    def getMaximumMassFraction(self) -> float: ...
    def getMaximumMassFractionChangeHistory(self) -> typing.MutableSequence[float]: ...
    def getMaximumMassFractionSumError(self) -> float: ...
    def getMaximumRelativeInventoryResidual(self) -> float: ...
    def getMaximumThermodynamicMassFractionError(self) -> float: ...
    def getMessage(self) -> java.lang.String: ...
    def getMinimumMassFraction(self) -> float: ...
    def getOutletBoundaryMassKg(self) -> typing.MutableSequence[float]: ...
    def getReason(self) -> 'OnePhaseSpeciesConservationReport.ConservationReason': ...
    def getRelativeInventoryResidual(self) -> typing.MutableSequence[float]: ...
    def getTransportDiagnostics(self) -> 'SpeciesTransportDiagnostics': ...
    def isConverged(self) -> bool: ...
    @staticmethod
    def notRun() -> 'OnePhaseSpeciesConservationReport': ...
    def toJson(self) -> java.lang.String: ...
    class ConservationReason(java.lang.Enum['OnePhaseSpeciesConservationReport.ConservationReason']):
        NOT_RUN: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        CONVERGED: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        INVALID_STATE: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        UNSUPPORTED_FLOW: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        COMPONENT_BALANCE_FAILED: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        COMPOSITION_BOUNDS_FAILED: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        COUPLING_NOT_CONVERGED: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        THERMODYNAMIC_SYNC_FAILED: typing.ClassVar['OnePhaseSpeciesConservationReport.ConservationReason'] = ...
        def isConverged(self) -> bool: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'OnePhaseSpeciesConservationReport.ConservationReason': ...
        @staticmethod
        def values() -> typing.MutableSequence['OnePhaseSpeciesConservationReport.ConservationReason']: ...

class SpeciesTransportDiagnostics(java.io.Serializable):
    def getCellCourantNumbers(self) -> typing.MutableSequence[float]: ...
    def getCellPecletNumbers(self) -> typing.MutableSequence[float]: ...
    def getCellPhysicalDispersionNumbers(self) -> typing.MutableSequence[float]: ...
    def getEffectiveCellCourantNumber(self) -> float: ...
    def getFirstOrderImplicitNumericalDispersionM2PerSecond(self) -> typing.MutableSequence[float]: ...
    def getInletDispersionBoundaryCondition(self) -> jneqsim.fluidmechanics.flowsolver.AxialDispersionBoundaryCondition: ...
    def getMaximumCellCourantNumber(self) -> float: ...
    def getMaximumCellPhysicalDispersionNumber(self) -> float: ...
    def getMaximumFirstOrderImplicitNumericalDispersionM2PerSecond(self) -> float: ...
    def getMaximumPhysicalAxialDispersionM2PerSecond(self) -> float: ...
    def getMessage(self) -> java.lang.String: ...
    def getMinimumPhysicalAxialDispersionM2PerSecond(self) -> float: ...
    def getOutletDispersionBoundaryCondition(self) -> jneqsim.fluidmechanics.flowsolver.AxialDispersionBoundaryCondition: ...
    def getPhysicalAxialDispersionM2PerSecond(self) -> typing.MutableSequence[float]: ...
    def getPhysicalDispersionModelName(self) -> java.lang.String: ...
    def getScheme(self) -> jneqsim.fluidmechanics.flowsolver.SpeciesAdvectionScheme: ...
    def getSubsteps(self) -> int: ...
    def isPhysicalDispersionIncluded(self) -> bool: ...
    @staticmethod
    def notRun() -> 'SpeciesTransportDiagnostics': ...
    def toJson(self) -> java.lang.String: ...

class OnePhaseFixedStaggeredGrid(OnePhasePipeFlowSolver, jneqsim.thermo.ThermodynamicConstantsInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, pipeFlowSystem: jneqsim.fluidmechanics.flowsystem.onephaseflowsystem.pipeflowsystem.PipeFlowSystem, double: float, int: int, boolean: bool): ...
    def clone(self) -> 'OnePhaseFixedStaggeredGrid': ...
    def getAxialDispersionModel(self) -> jneqsim.fluidmechanics.flowsolver.AxialDispersionModel: ...
    def getLastConvergenceReport(self) -> OnePhaseFlowConvergenceReport: ...
    def getLastSpeciesConservationReport(self) -> OnePhaseSpeciesConservationReport: ...
    def getSpeciesAdvectionScheme(self) -> jneqsim.fluidmechanics.flowsolver.SpeciesAdvectionScheme: ...
    def initComposition(self, int: int) -> None: ...
    def initFinalResults(self) -> None: ...
    def initMatrix(self) -> None: ...
    def initPressure(self, int: int) -> None: ...
    def initProfiles(self) -> None: ...
    def initTemperature(self, int: int) -> None: ...
    def initVelocity(self, int: int) -> None: ...
    def isConservativeSpeciesTransportEnabled(self) -> bool: ...
    def isFailOnNonConvergence(self) -> bool: ...
    def setAxialDispersionModel(self, axialDispersionModel: jneqsim.fluidmechanics.flowsolver.AxialDispersionModel) -> None: ...
    def setComponentConservationMatrix(self, int: int) -> None: ...
    def setConservativeSpeciesTransportEnabled(self, boolean: bool) -> None: ...
    def setEnergyMatrixTDMA(self) -> None: ...
    def setFailOnNonConvergence(self, boolean: bool) -> None: ...
    def setImpulsMatrixTDMA(self) -> None: ...
    def setMassConservationMatrixTDMA(self) -> None: ...
    def setSpeciesAdvectionScheme(self, speciesAdvectionScheme: jneqsim.fluidmechanics.flowsolver.SpeciesAdvectionScheme) -> None: ...
    def solveTDMA(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver")``.

    OnePhaseFixedStaggeredGrid: typing.Type[OnePhaseFixedStaggeredGrid]
    OnePhaseFlowConvergenceReport: typing.Type[OnePhaseFlowConvergenceReport]
    OnePhasePipeFlowSolver: typing.Type[OnePhasePipeFlowSolver]
    OnePhaseSpeciesConservationReport: typing.Type[OnePhaseSpeciesConservationReport]
    SpeciesTransportDiagnostics: typing.Type[SpeciesTransportDiagnostics]
