
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.thermo.characterization
import typing



class BioFeedstockPreparation(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getMassClosureFraction(self) -> float: ...
    def getPowerKW(self) -> float: ...
    def getPreparedFeedRateKgPerHr(self) -> float: ...
    def getPreparedFeedstock(self) -> jneqsim.thermo.characterization.BioFeedstock: ...
    def getResults(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getWaterRemovedKgPerHr(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setDrySolidsLossFraction(self, double: float) -> None: ...
    def setEnergyIntensities(self, double: float, double2: float, double3: float) -> None: ...
    def setFeedstock(self, bioFeedstock: jneqsim.thermo.characterization.BioFeedstock, double: float) -> None: ...
    def setTargetDensityKgPerM3(self, double: float) -> None: ...
    def setTargetTotalSolidsFraction(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.solidhandling")``.

    BioFeedstockPreparation: typing.Type[BioFeedstockPreparation]
