
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jpype
import jneqsim.thermo.system
import typing



class DispersedPhaseSlipModel(java.lang.Enum['DispersedPhaseSlipModel']):
    USER_SPECIFIED: typing.ClassVar['DispersedPhaseSlipModel'] = ...
    TERMINAL_VELOCITY: typing.ClassVar['DispersedPhaseSlipModel'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'DispersedPhaseSlipModel': ...
    @staticmethod
    def values() -> typing.MutableSequence['DispersedPhaseSlipModel']: ...

class EvaporationProfilePoint:
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    @typing.overload
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, doubleArray: typing.Union[typing.List[float], jpype.JArray], double9: float, double10: float, double11: float): ...
    def getCharacteristicDispersedPhaseSize(self) -> float: ...
    def getCharacteristicLiquidSize(self) -> float: ...
    def getComponentMolarFluxes(self) -> typing.MutableSequence[float]: ...
    def getDispersedPhaseRelativeVelocity(self) -> float: ...
    def getDistance(self) -> float: ...
    def getGasTemperature(self) -> float: ...
    def getGasVelocity(self) -> float: ...
    def getInterfacialAreaPerLength(self) -> float: ...
    def getLiquidTemperature(self) -> float: ...
    def getLiquidVelocity(self) -> float: ...
    def getRemainingInjectedLiquidFraction(self) -> float: ...
    def getRemainingTrackedPhaseFraction(self) -> float: ...
    def getTotalMolarFlux(self) -> float: ...

class LiquidDistribution(java.lang.Enum['LiquidDistribution']):
    DROPLETS: typing.ClassVar['LiquidDistribution'] = ...
    WALL_FILM: typing.ClassVar['LiquidDistribution'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'LiquidDistribution': ...
    @staticmethod
    def values() -> typing.MutableSequence['LiquidDistribution']: ...

class PipelineEvaporationConfig:
    def __init__(self): ...
    def getAmbientTemperature(self) -> float: ...
    def getCompletionFraction(self) -> float: ...
    def getGasVelocity(self) -> float: ...
    def getInitialBubbleDiameter(self) -> float: ...
    def getInitialDropletDiameter(self) -> float: ...
    def getInitialFilmThickness(self) -> float: ...
    def getInitialStepLength(self) -> float: ...
    def getLiquidDistribution(self) -> LiquidDistribution: ...
    def getLiquidVelocity(self) -> float: ...
    def getMaximumDonorFractionPerStep(self) -> float: ...
    def getMaximumNumberOfSteps(self) -> int: ...
    def getMaximumStepLength(self) -> float: ...
    def getMaximumTemperatureChangePerStep(self) -> float: ...
    def getMinimumStepLength(self) -> float: ...
    def getOverallWallHeatTransferCoefficient(self) -> float: ...
    def getPipeDiameter(self) -> float: ...
    def getPipeInclinationAngle(self) -> float: ...
    def getPipeLength(self) -> float: ...
    def getPipeRoughness(self) -> float: ...
    def getSlipModel(self) -> DispersedPhaseSlipModel: ...
    def getWettedPerimeterFraction(self) -> float: ...
    def isUseAbramzonSirignano(self) -> bool: ...
    def setAmbientTemperature(self, double: float) -> None: ...
    def setCompletionFraction(self, double: float) -> None: ...
    def setGasVelocity(self, double: float) -> None: ...
    def setInitialBubbleDiameter(self, double: float) -> None: ...
    def setInitialDropletDiameter(self, double: float) -> None: ...
    def setInitialFilmThickness(self, double: float) -> None: ...
    def setInitialStepLength(self, double: float) -> None: ...
    def setLiquidDistribution(self, liquidDistribution: LiquidDistribution) -> None: ...
    def setLiquidVelocity(self, double: float) -> None: ...
    def setMaximumDonorFractionPerStep(self, double: float) -> None: ...
    def setMaximumNumberOfSteps(self, int: int) -> None: ...
    def setMaximumStepLength(self, double: float) -> None: ...
    def setMaximumTemperatureChangePerStep(self, double: float) -> None: ...
    def setMinimumStepLength(self, double: float) -> None: ...
    def setOverallWallHeatTransferCoefficient(self, double: float) -> None: ...
    def setPipeDiameter(self, double: float) -> None: ...
    def setPipeInclinationAngle(self, double: float) -> None: ...
    def setPipeLength(self, double: float) -> None: ...
    def setPipeRoughness(self, double: float) -> None: ...
    def setSlipModel(self, dispersedPhaseSlipModel: DispersedPhaseSlipModel) -> None: ...
    def setUseAbramzonSirignano(self, boolean: bool) -> None: ...
    def setWettedPerimeterFraction(self, double: float) -> None: ...
    def validate(self) -> None: ...

class PipelineEvaporationResult:
    def getCompleteDissolutionDistance(self) -> float: ...
    def getCompleteEvaporationDistance(self) -> float: ...
    def getCompletionDistance(self) -> float: ...
    def getMaximumComponentMolarBalanceError(self) -> float: ...
    def getOutletSystem(self) -> jneqsim.thermo.system.SystemInterface: ...
    def getProfile(self) -> java.util.List[EvaporationProfilePoint]: ...
    def getRelativeEnergyBalanceError(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isCompleteDissolution(self) -> bool: ...
    def isCompleteEvaporation(self) -> bool: ...
    def isCompleteTransfer(self) -> bool: ...
    def isGasDissolutionStudy(self) -> bool: ...

class PipelineEvaporationStudy:
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, pipelineEvaporationConfig: PipelineEvaporationConfig): ...
    def run(self) -> PipelineEvaporationResult: ...

class PipelineDissolutionResult(PipelineEvaporationResult): ...

class PipelineDissolutionStudy(PipelineEvaporationStudy):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface, pipelineEvaporationConfig: PipelineEvaporationConfig): ...
    def run(self) -> PipelineDissolutionResult: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.pipeline.evaporation")``.

    DispersedPhaseSlipModel: typing.Type[DispersedPhaseSlipModel]
    EvaporationProfilePoint: typing.Type[EvaporationProfilePoint]
    LiquidDistribution: typing.Type[LiquidDistribution]
    PipelineDissolutionResult: typing.Type[PipelineDissolutionResult]
    PipelineDissolutionStudy: typing.Type[PipelineDissolutionStudy]
    PipelineEvaporationConfig: typing.Type[PipelineEvaporationConfig]
    PipelineEvaporationResult: typing.Type[PipelineEvaporationResult]
    PipelineEvaporationStudy: typing.Type[PipelineEvaporationStudy]
