
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.model
import jneqsim.process.engineering.numerics
import jneqsim.process.processmodel
import typing



class DesignCaseEngine:
    @staticmethod
    def run(processSystem: jneqsim.process.processmodel.ProcessSystem, list: java.util.List['EngineeringDesignCase'], list2: java.util.List['EngineeringMetric']) -> 'EngineeringDesignEnvelope': ...
    @staticmethod
    def runDetailed(processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseSet: 'EngineeringCaseSet', engineeringCaseRunOptions: 'EngineeringCaseRunOptions') -> 'EngineeringCaseRunReport': ...

class DesignCaseResult(java.io.Serializable):
    def getDesignCase(self) -> 'EngineeringDesignCase': ...
    def getMessage(self) -> java.lang.String: ...
    def getMetricResults(self) -> java.util.Map[java.lang.String, 'DesignCaseResult.MetricResult']: ...
    def getNumericalHealthReport(self) -> jneqsim.process.engineering.numerics.EngineeringNumericalHealthReport: ...
    def getStatus(self) -> java.lang.String: ...
    def getValues(self) -> java.util.Map[java.lang.String, float]: ...
    def isConverged(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class MetricResult(java.io.Serializable):
        def getLimitStatus(self) -> java.lang.String: ...
        def getStatus(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringCaseExecutionException(java.lang.IllegalStateException):
    def __init__(self, string: typing.Union[java.lang.String, str], engineeringCaseRunReport: 'EngineeringCaseRunReport'): ...
    def getPartialReport(self) -> 'EngineeringCaseRunReport': ...

class EngineeringCaseFailurePolicy(java.lang.Enum['EngineeringCaseFailurePolicy']):
    RETURN_PARTIAL: typing.ClassVar['EngineeringCaseFailurePolicy'] = ...
    THROW_WITH_PARTIAL_RESULT: typing.ClassVar['EngineeringCaseFailurePolicy'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringCaseFailurePolicy': ...
    @staticmethod
    def values() -> typing.MutableSequence['EngineeringCaseFailurePolicy']: ...

class EngineeringCaseRunOptions(java.io.Serializable):
    @staticmethod
    def builder() -> 'EngineeringCaseRunOptions.Builder': ...
    def getFailurePolicy(self) -> EngineeringCaseFailurePolicy: ...
    def getNumericalHealthCriteria(self) -> jneqsim.process.engineering.numerics.EngineeringNumericalHealthCriteria: ...
    def getParallelism(self) -> int: ...
    def isConvergenceRequired(self) -> bool: ...
    @staticmethod
    def sequential() -> 'EngineeringCaseRunOptions': ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EngineeringCaseRunOptions': ...
        def failurePolicy(self, engineeringCaseFailurePolicy: EngineeringCaseFailurePolicy) -> 'EngineeringCaseRunOptions.Builder': ...
        def numericalHealthCriteria(self, engineeringNumericalHealthCriteria: jneqsim.process.engineering.numerics.EngineeringNumericalHealthCriteria) -> 'EngineeringCaseRunOptions.Builder': ...
        def parallelism(self, int: int) -> 'EngineeringCaseRunOptions.Builder': ...
        def requireConvergence(self, boolean: bool) -> 'EngineeringCaseRunOptions.Builder': ...

class EngineeringCaseRunReport(java.io.Serializable):
    def getCaseSetId(self) -> java.lang.String: ...
    def getDefinitionFingerprint(self) -> java.lang.String: ...
    def getEnvelope(self) -> 'EngineeringDesignEnvelope': ...
    def getResultFingerprint(self) -> java.lang.String: ...
    def isAccepted(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def requireComplete(self) -> 'EngineeringCaseRunReport': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringCaseRunner:
    @staticmethod
    def run(processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseSet: 'EngineeringCaseSet', engineeringCaseRunOptions: EngineeringCaseRunOptions) -> EngineeringCaseRunReport: ...

class EngineeringCaseSet(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def addCase(self, engineeringDesignCase: 'EngineeringDesignCase') -> 'EngineeringCaseSet': ...
    def addMetric(self, engineeringMetric: 'EngineeringMetric') -> 'EngineeringCaseSet': ...
    def getCases(self) -> java.util.List['EngineeringDesignCase']: ...
    def getId(self) -> java.lang.String: ...
    def getMetrics(self) -> java.util.List['EngineeringMetric']: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignCase(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], type: 'EngineeringDesignCase.Type', configurator: typing.Union['EngineeringDesignCase.Configurator', typing.Callable]): ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignCase': ...
    def addInput(self, input: 'EngineeringDesignCase.Input') -> 'EngineeringDesignCase': ...
    def getApprovalStatus(self) -> java.lang.String: ...
    def getCaseGroup(self) -> java.lang.String: ...
    def getDescription(self) -> java.lang.String: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getId(self) -> java.lang.String: ...
    def getInputs(self) -> java.util.List['EngineeringDesignCase.Input']: ...
    def getName(self) -> java.lang.String: ...
    def getPriority(self) -> int: ...
    def getType(self) -> 'EngineeringDesignCase.Type': ...
    def isEnabled(self) -> bool: ...
    def isRequired(self) -> bool: ...
    def setApprovalStatus(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignCase': ...
    def setCaseGroup(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignCase': ...
    def setDescription(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignCase': ...
    def setEnabled(self, boolean: bool) -> 'EngineeringDesignCase': ...
    def setPriority(self, int: int) -> 'EngineeringDesignCase': ...
    def setRequired(self, boolean: bool) -> 'EngineeringDesignCase': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Configurator(java.io.Serializable):
        def configure(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> None: ...
    class Input(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Type(java.lang.Enum['EngineeringDesignCase.Type']):
        NORMAL: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        MAXIMUM_PRODUCTION: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        MINIMUM_TURNDOWN: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        STARTUP: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        SHUTDOWN: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        UTILITY_FAILURE: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        EQUIPMENT_TRIP: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        SETTLE_OUT: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        BLOCKED_OUTLET: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        FIRE: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        BLOWDOWN: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        AMBIENT_EXTREME: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        CUSTOM: typing.ClassVar['EngineeringDesignCase.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignCase.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringDesignCase.Type']: ...

class EngineeringDesignCaseMatrix(java.io.Serializable):
    def __init__(self, list: java.util.List[EngineeringDesignCase], list2: java.util.List['EngineeringMetric'], engineeringDesignEnvelope: 'EngineeringDesignEnvelope'): ...
    def toMap(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignEnvelope(java.io.Serializable):
    def getCaseResults(self) -> java.util.List[DesignCaseResult]: ...
    def getConfiguredMetrics(self) -> java.util.List['EngineeringMetric']: ...
    def getFailedCaseCount(self) -> int: ...
    def getGoverningValues(self) -> java.util.Map[java.lang.String, 'EngineeringDesignEnvelope.GoverningValue']: ...
    def getLimitViolationCount(self) -> int: ...
    def getMissingGoverningMetricIds(self) -> java.util.List[java.lang.String]: ...
    def getPartialCaseCount(self) -> int: ...
    def getSkippedCaseCount(self) -> int: ...
    def getSuccessfulCaseCount(self) -> int: ...
    def getUnassessedGoverningMetricIds(self) -> java.util.List[java.lang.String]: ...
    def hasCaseFailures(self) -> bool: ...
    def isAccepted(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def toCalculations(self) -> java.util.List[jneqsim.process.engineering.model.EngineeringCalculation]: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class GoverningValue(java.io.Serializable):
        def getDesignCaseId(self) -> java.lang.String: ...
        def getMetric(self) -> 'EngineeringMetric': ...
        def getValue(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringMetric(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], governingDirection: 'EngineeringMetric.GoverningDirection', extractor: typing.Union['EngineeringMetric.Extractor', typing.Callable]): ...
    def assess(self, double: float) -> java.lang.String: ...
    @staticmethod
    def compressorChartExtrapolationFlag(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorControlLineMargin(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorDischargeTemperature(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorPolytropicEfficiency(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorPolytropicHead(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorPower(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorRecycleCoolerDuty(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorRequiredRecycleFraction(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorSpeed(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorStonewallMargin(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def compressorSurgeMargin(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def controlValveRequiredCv(string: typing.Union[java.lang.String, str], double: float) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentDuty(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentInletDensity(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentInletMassFlow(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentInletVolumeFlow(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentOutletVolumeFlow(string: typing.Union[java.lang.String, str], int: int, string2: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentPressure(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentPressureDrop(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def equipmentTemperature(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    def getGoverningDirection(self) -> 'EngineeringMetric.GoverningDirection': ...
    def getId(self) -> java.lang.String: ...
    def getLowerAcceptanceLimit(self) -> float: ...
    def getName(self) -> java.lang.String: ...
    def getSubjectTag(self) -> java.lang.String: ...
    def getUnit(self) -> java.lang.String: ...
    def getUpperAcceptanceLimit(self) -> float: ...
    @staticmethod
    def pumpNpshMargin(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    @staticmethod
    def pumpPower(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric': ...
    def setAcceptanceRange(self, double: float, double2: float) -> 'EngineeringMetric': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Extractor(java.io.Serializable):
        def extract(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> float: ...
    class GoverningDirection(java.lang.Enum['EngineeringMetric.GoverningDirection']):
        MAXIMUM: typing.ClassVar['EngineeringMetric.GoverningDirection'] = ...
        MINIMUM: typing.ClassVar['EngineeringMetric.GoverningDirection'] = ...
        MAXIMUM_ABSOLUTE: typing.ClassVar['EngineeringMetric.GoverningDirection'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringMetric.GoverningDirection': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringMetric.GoverningDirection']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.designcase")``.

    DesignCaseEngine: typing.Type[DesignCaseEngine]
    DesignCaseResult: typing.Type[DesignCaseResult]
    EngineeringCaseExecutionException: typing.Type[EngineeringCaseExecutionException]
    EngineeringCaseFailurePolicy: typing.Type[EngineeringCaseFailurePolicy]
    EngineeringCaseRunOptions: typing.Type[EngineeringCaseRunOptions]
    EngineeringCaseRunReport: typing.Type[EngineeringCaseRunReport]
    EngineeringCaseRunner: typing.Type[EngineeringCaseRunner]
    EngineeringCaseSet: typing.Type[EngineeringCaseSet]
    EngineeringDesignCase: typing.Type[EngineeringDesignCase]
    EngineeringDesignCaseMatrix: typing.Type[EngineeringDesignCaseMatrix]
    EngineeringDesignEnvelope: typing.Type[EngineeringDesignEnvelope]
    EngineeringMetric: typing.Type[EngineeringMetric]
