
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.thermo.system
import typing



class AirDemandController(java.io.Serializable):
    def __init__(self): ...
    def calculateOxygenDemand(self, systemInterface: jneqsim.thermo.system.SystemInterface) -> float: ...
    def calculateTrimmedOxygenDemand(self, systemInterface: jneqsim.thermo.system.SystemInterface, double: float) -> float: ...
    def getTargetH2SToSO2Ratio(self) -> float: ...
    def setFeedbackGain(self, double: float) -> None: ...
    def setTargetH2SToSO2Ratio(self, double: float) -> None: ...
    def setTrimLimits(self, double: float, double2: float) -> None: ...

class ClausCatalyticConverter(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCatalystType(self) -> 'ClausCatalyticConverter.CatalystType': ...
    def getClausConversion(self) -> float: ...
    def getCosConversion(self) -> float: ...
    def getCs2Conversion(self) -> float: ...
    def getTemperatureRise(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAdiabatic(self, boolean: bool) -> None: ...
    def setCalibrationFactor(self, double: float) -> None: ...
    def setCatalystActivity(self, double: float) -> None: ...
    def setCatalystType(self, catalystType: 'ClausCatalyticConverter.CatalystType') -> None: ...
    def setGasHourlySpaceVelocity(self, double: float) -> None: ...
    def setParticleEffectivenessFactor(self, double: float) -> None: ...
    def setPressureDrop(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    class CatalystType(java.lang.Enum['ClausCatalyticConverter.CatalystType']):
        ALUMINA: typing.ClassVar['ClausCatalyticConverter.CatalystType'] = ...
        TITANIA: typing.ClassVar['ClausCatalyticConverter.CatalystType'] = ...
        MIXED: typing.ClassVar['ClausCatalyticConverter.CatalystType'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ClausCatalyticConverter.CatalystType': ...
        @staticmethod
        def values() -> typing.MutableSequence['ClausCatalyticConverter.CatalystType']: ...

class ClausReactionFurnace(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getAmmoniaConversion(self) -> float: ...
    def getFurnaceTemperature(self) -> float: ...
    def getH2SOxidizedMoles(self) -> float: ...
    def getMethaneConversion(self) -> float: ...
    def getModelMode(self) -> 'ClausReactionFurnace.ModelMode': ...
    def getSulfurBalanceError(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setEnergyMode(self, energyMode: 'ClausReactionFurnace.EnergyMode') -> None: ...
    def setHeatLossFraction(self, double: float) -> None: ...
    def setKineticCalibrationFactor(self, double: float) -> None: ...
    def setModelMode(self, modelMode: 'ClausReactionFurnace.ModelMode') -> None: ...
    def setResidenceTime(self, double: float) -> None: ...
    def setSpecifiedOutletTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setThermalClausApproach(self, double: float) -> None: ...
    class EnergyMode(java.lang.Enum['ClausReactionFurnace.EnergyMode']):
        ADIABATIC: typing.ClassVar['ClausReactionFurnace.EnergyMode'] = ...
        ISOTHERMAL: typing.ClassVar['ClausReactionFurnace.EnergyMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ClausReactionFurnace.EnergyMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['ClausReactionFurnace.EnergyMode']: ...
    class ModelMode(java.lang.Enum['ClausReactionFurnace.ModelMode']):
        EQUILIBRIUM: typing.ClassVar['ClausReactionFurnace.ModelMode'] = ...
        REDUCED_KINETIC: typing.ClassVar['ClausReactionFurnace.ModelMode'] = ...
        EMPIRICAL_PLANT_CALIBRATED: typing.ClassVar['ClausReactionFurnace.ModelMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'ClausReactionFurnace.ModelMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['ClausReactionFurnace.ModelMode']: ...

class ReactiveWasteHeatBoiler(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCosConversion(self) -> float: ...
    def getCs2Conversion(self) -> float: ...
    def getHeatDuty(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getOutletSulfurAllotropeFractions(self) -> java.util.Map[java.lang.String, float]: ...
    def getSteamProduction(self, string: typing.Union[java.lang.String, str]) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setNumberOfCells(self, int: int) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureDrop(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setResidenceTime(self, double: float) -> None: ...

class SulfurCondenser(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getCondensedSulfur(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getHeatDuty(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getInletSulfurDewPoint(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getLiquidSulfurStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getOutletDewPointMargin(self) -> float: ...
    def getOutletSulfurAllotropeFractions(self) -> java.util.Map[java.lang.String, float]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setLiquidSulfurEntrainmentFraction(self, double: float) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float) -> None: ...
    @typing.overload
    def setOutletTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setPressureDrop(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setSulfurRemovalEfficiency(self, double: float) -> None: ...

class SulfurRecoveryPerformance(java.io.Serializable):
    def getAirControlIterations(self) -> int: ...
    def getFeedSulfurKgPerHour(self) -> float: ...
    def getFurnaceTemperatureK(self) -> float: ...
    def getOverallSulfurRecoveryPercent(self) -> float: ...
    def getOxygenDemandMoles(self) -> float: ...
    def getRecoveredSulfurKgPerHour(self) -> float: ...
    def getRecycleIterations(self) -> int: ...
    def getStackSO2KgPerHour(self) -> float: ...
    def getSulfurBalanceRelativeError(self) -> float: ...
    def getSulfurRecoveryPercent(self) -> float: ...
    def getTailGasH2SToSO2Ratio(self) -> float: ...
    def isAirControlConverged(self) -> bool: ...
    def isRecycleConverged(self) -> bool: ...

class SulfurRecoveryProcessBuilder:
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def build(self) -> 'SulfurRecoveryUnit': ...
    def catalyticStages(self, int: int) -> 'SulfurRecoveryProcessBuilder': ...
    def configuration(self, configuration: 'SulfurRecoveryUnit.Configuration') -> 'SulfurRecoveryProcessBuilder': ...
    def incinerator(self, boolean: bool) -> 'SulfurRecoveryProcessBuilder': ...
    def oxidantOxygenMoleFraction(self, double: float) -> 'SulfurRecoveryProcessBuilder': ...
    def splitFlowFurnaceFraction(self, double: float) -> 'SulfurRecoveryProcessBuilder': ...
    def tailGasTreatment(self, boolean: bool) -> 'SulfurRecoveryProcessBuilder': ...
    def targetH2SToSO2Ratio(self, double: float) -> 'SulfurRecoveryProcessBuilder': ...

class SulfurRecoveryUnit(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getAcidGasRecycleStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getCatalyticConverters(self) -> java.util.List[ClausCatalyticConverter]: ...
    def getClausTailGasStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getCombinedSulfurProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getConfiguration(self) -> 'SulfurRecoveryUnit.Configuration': ...
    def getPerformance(self) -> SulfurRecoveryPerformance: ...
    def getReactionFurnace(self) -> ClausReactionFurnace: ...
    def getSulfurCondensers(self) -> java.util.List[SulfurCondenser]: ...
    def getSulfurProductStreams(self) -> java.util.List[jneqsim.process.equipment.stream.StreamInterface]: ...
    def getTailGasTreatmentUnit(self) -> 'TailGasTreatmentUnit': ...
    def getThermalIncinerator(self) -> 'ThermalIncinerator': ...
    def getWasteHeatBoiler(self) -> ReactiveWasteHeatBoiler: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAirControlTolerance(self, double: float) -> None: ...
    def setCatalystType(self, int: int, catalystType: ClausCatalyticConverter.CatalystType) -> None: ...
    def setConfiguration(self, configuration: 'SulfurRecoveryUnit.Configuration') -> None: ...
    def setConverterInletTemperature(self, int: int, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setIncineratorEnabled(self, boolean: bool) -> None: ...
    def setMaximumAirControlIterations(self, int: int) -> None: ...
    def setNumberOfCatalyticStages(self, int: int) -> None: ...
    def setOxidantOxygenMoleFraction(self, double: float) -> None: ...
    def setRecycleConvergence(self, double: float, int: int, double2: float) -> None: ...
    def setSplitFlowFurnaceFraction(self, double: float) -> None: ...
    def setTailGasTreatmentEnabled(self, boolean: bool) -> None: ...
    def setTargetH2SToSO2Ratio(self, double: float) -> None: ...
    class Configuration(java.lang.Enum['SulfurRecoveryUnit.Configuration']):
        STRAIGHT_THROUGH: typing.ClassVar['SulfurRecoveryUnit.Configuration'] = ...
        SPLIT_FLOW: typing.ClassVar['SulfurRecoveryUnit.Configuration'] = ...
        OXYGEN_ENRICHED: typing.ClassVar['SulfurRecoveryUnit.Configuration'] = ...
        SUB_DEW_POINT: typing.ClassVar['SulfurRecoveryUnit.Configuration'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SulfurRecoveryUnit.Configuration': ...
        @staticmethod
        def values() -> typing.MutableSequence['SulfurRecoveryUnit.Configuration']: ...

class TailGasTreatmentUnit(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getAbsorbedH2SMoles(self) -> float: ...
    def getAcidGasRecycleStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    def getHydrogenAddedMoles(self) -> float: ...
    def getHydrogenationConversion(self) -> float: ...
    def getHydrolysisConversion(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setCo2CoAbsorptionFraction(self, double: float) -> None: ...
    def setH2SRemovalEfficiency(self, double: float) -> None: ...
    def setHydrogenStoichiometricFactor(self, double: float) -> None: ...
    def setReactorTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setResidenceTime(self, double: float) -> None: ...

class ThermalIncinerator(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getSo2Emission(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSulfurDestructionEfficiency(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setExcessOxygenFraction(self, double: float) -> None: ...
    def setMixingFactor(self, double: float) -> None: ...
    def setOxidantOxygenMoleFraction(self, double: float) -> None: ...
    def setResidenceTime(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float) -> None: ...
    @typing.overload
    def setTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...

class SubDewPointSulfurReactor(ClausCatalyticConverter):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getBedMode(self) -> 'SubDewPointSulfurReactor.BedMode': ...
    def getStoredSulfur(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSulfurProductStream(self) -> jneqsim.process.equipment.stream.StreamInterface: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAdsorptionEfficiency(self, double: float) -> None: ...
    def setBedMode(self, bedMode: 'SubDewPointSulfurReactor.BedMode') -> None: ...
    def setRegenerationFractionPerRun(self, double: float) -> None: ...
    def setSulfurCapacity(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    class BedMode(java.lang.Enum['SubDewPointSulfurReactor.BedMode']):
        ADSORPTION: typing.ClassVar['SubDewPointSulfurReactor.BedMode'] = ...
        REGENERATION: typing.ClassVar['SubDewPointSulfurReactor.BedMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SubDewPointSulfurReactor.BedMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['SubDewPointSulfurReactor.BedMode']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.reactor.sulfurrecovery")``.

    AirDemandController: typing.Type[AirDemandController]
    ClausCatalyticConverter: typing.Type[ClausCatalyticConverter]
    ClausReactionFurnace: typing.Type[ClausReactionFurnace]
    ReactiveWasteHeatBoiler: typing.Type[ReactiveWasteHeatBoiler]
    SubDewPointSulfurReactor: typing.Type[SubDewPointSulfurReactor]
    SulfurCondenser: typing.Type[SulfurCondenser]
    SulfurRecoveryPerformance: typing.Type[SulfurRecoveryPerformance]
    SulfurRecoveryProcessBuilder: typing.Type[SulfurRecoveryProcessBuilder]
    SulfurRecoveryUnit: typing.Type[SulfurRecoveryUnit]
    TailGasTreatmentUnit: typing.Type[TailGasTreatmentUnit]
    ThermalIncinerator: typing.Type[ThermalIncinerator]
