
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.process.logic
import jneqsim.process.logic.voting
import jneqsim.process.processmodel
import jneqsim.process.safety.scenario
import typing



class ClosedLoopSafetyFunction(jneqsim.process.logic.ProcessLogic, jneqsim.process.safety.scenario.DynamicSafetyScenarioEvidenceProvider):
    def activate(self) -> None: ...
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], processSystem: jneqsim.process.processmodel.ProcessSystem, votingPattern: jneqsim.process.logic.voting.VotingPattern, processLogic: jneqsim.process.logic.ProcessLogic) -> 'ClosedLoopSafetyFunction.Builder': ...
    def deactivate(self) -> None: ...
    def execute(self, double: float) -> None: ...
    def getDynamicSafetyScenarioEvidence(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getName(self) -> java.lang.String: ...
    def getSifId(self) -> java.lang.String: ...
    def getState(self) -> jneqsim.process.logic.LogicState: ...
    def getStatusDescription(self) -> java.lang.String: ...
    def getTargetEquipment(self) -> java.util.List[jneqsim.process.equipment.ProcessEquipmentInterface]: ...
    def isActive(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def reset(self) -> bool: ...
    class Builder:
        def addChannel(self, safetyFunctionChannel: 'SafetyFunctionChannel') -> 'ClosedLoopSafetyFunction.Builder': ...
        def build(self) -> 'ClosedLoopSafetyFunction': ...
        def logicSolverDelaySeconds(self, double: float) -> 'ClosedLoopSafetyFunction.Builder': ...

class SafetyFunctionChannel(java.io.Serializable):
    @staticmethod
    def highTrip(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, signalExtractor: typing.Union['SafetyFunctionChannel.SignalExtractor', typing.Callable]) -> 'SafetyFunctionChannel.Builder': ...
    @staticmethod
    def lowTrip(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, signalExtractor: typing.Union['SafetyFunctionChannel.SignalExtractor', typing.Callable]) -> 'SafetyFunctionChannel.Builder': ...
    class Builder:
        def bias(self, double: float) -> 'SafetyFunctionChannel.Builder': ...
        def build(self) -> 'SafetyFunctionChannel': ...
        def faultMode(self, faultMode: 'SafetyFunctionChannel.FaultMode') -> 'SafetyFunctionChannel.Builder': ...
        def responseDelaySeconds(self, double: float) -> 'SafetyFunctionChannel.Builder': ...
    class FaultMode(java.lang.Enum['SafetyFunctionChannel.FaultMode']):
        HEALTHY: typing.ClassVar['SafetyFunctionChannel.FaultMode'] = ...
        BYPASSED: typing.ClassVar['SafetyFunctionChannel.FaultMode'] = ...
        STUCK_NORMAL: typing.ClassVar['SafetyFunctionChannel.FaultMode'] = ...
        STUCK_TRIP: typing.ClassVar['SafetyFunctionChannel.FaultMode'] = ...
        BIASED: typing.ClassVar['SafetyFunctionChannel.FaultMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionChannel.FaultMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionChannel.FaultMode']: ...
    class SignalExtractor(java.io.Serializable):
        def extract(self, processSystem: jneqsim.process.processmodel.ProcessSystem) -> float: ...
    class TripDirection(java.lang.Enum['SafetyFunctionChannel.TripDirection']):
        HIGH: typing.ClassVar['SafetyFunctionChannel.TripDirection'] = ...
        LOW: typing.ClassVar['SafetyFunctionChannel.TripDirection'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'SafetyFunctionChannel.TripDirection': ...
        @staticmethod
        def values() -> typing.MutableSequence['SafetyFunctionChannel.TripDirection']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.sif")``.

    ClosedLoopSafetyFunction: typing.Type[ClosedLoopSafetyFunction]
    SafetyFunctionChannel: typing.Type[SafetyFunctionChannel]
