
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.calculation
import typing



class MechanicalIntegrityQualificationCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['MechanicalIntegrityQualificationCalculation.Input', 'MechanicalIntegrityQualificationCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'MechanicalIntegrityQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'MechanicalIntegrityQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['MechanicalIntegrityQualificationCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
        class Builder:
            def approvals(self, boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
            def build(self) -> 'MechanicalIntegrityQualificationCalculation.Input': ...
            def externalPressureAndBuckling(self, double: float, double2: float, double3: float) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
            def fatigueAndExternalLoads(self, double: float, double2: float) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
            def internalPressure(self, double: float, double2: float, double3: float, double4: float) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
            def nozzleReinforcement(self, double: float, double2: float) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
            def temperatureAndCorrosion(self, double: float, double2: float, double3: float, double4: float) -> 'MechanicalIntegrityQualificationCalculation.Input.Builder': ...
    class Result(jneqsim.process.engineering.calculation.EngineeringConstraintResult, java.io.Serializable):
        def allConstraintsSatisfied(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.mechanical")``.

    MechanicalIntegrityQualificationCalculation: typing.Type[MechanicalIntegrityQualificationCalculation]
