
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering.model
import typing



class Cfihos20HandoverExporter:
    @staticmethod
    def export(engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, cfihos20ReferenceDataMapping: 'Cfihos20ReferenceDataMapping', path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'Cfihos20HandoverExporter.Result': ...
    class Result:
        def getAssessmentFile(self) -> java.nio.file.Path: ...
        def getManifestFile(self) -> java.nio.file.Path: ...
        def getOutputDirectory(self) -> java.nio.file.Path: ...
        def getReport(self) -> 'Cfihos20HandoverReport': ...
        def getUnmappedFile(self) -> java.nio.file.Path: ...

class Cfihos20HandoverReport(java.io.Serializable):
    def getFileDigests(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getFindings(self) -> java.util.List['Cfihos20HandoverReport.Finding']: ...
    def getStatus(self) -> 'Cfihos20HandoverReport.Status': ...
    def isReadyForPrincipalTransformation(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Finding(java.io.Serializable):
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Status(java.lang.Enum['Cfihos20HandoverReport.Status']):
        READY_FOR_PRINCIPAL_TRANSFORMATION: typing.ClassVar['Cfihos20HandoverReport.Status'] = ...
        INCOMPLETE: typing.ClassVar['Cfihos20HandoverReport.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Cfihos20HandoverReport.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['Cfihos20HandoverReport.Status']: ...

class Cfihos20ReferenceDataMapping(java.io.Serializable):
    @staticmethod
    def builder(edition: 'Cfihos20ReferenceDataMapping.Edition') -> 'Cfihos20ReferenceDataMapping.Builder': ...
    def getDocumentTypeId(self, string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def getEdition(self) -> 'Cfihos20ReferenceDataMapping.Edition': ...
    def getMappingAuthority(self) -> java.lang.String: ...
    def getMappingRevision(self) -> java.lang.String: ...
    def getNodeClassification(self, string: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.NodeClassification': ...
    def getPropertyDefinition(self, string: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.PropertyDefinition': ...
    def getSourceSha256(self) -> java.lang.String: ...
    def getSourceUri(self) -> java.lang.String: ...
    def isApprovedForProject(self) -> bool: ...
    def isSourceDigestVerified(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def approvedBy(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
        def build(self) -> 'Cfihos20ReferenceDataMapping': ...
        def mapDocument(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
        def mapNode(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
        def mapProperty(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
        def source(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
        def verifiedSource(self, string: typing.Union[java.lang.String, str], path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'Cfihos20ReferenceDataMapping.Builder': ...
    class Edition(java.lang.Enum['Cfihos20ReferenceDataMapping.Edition']):
        CORE: typing.ClassVar['Cfihos20ReferenceDataMapping.Edition'] = ...
        EXTENDED: typing.ClassVar['Cfihos20ReferenceDataMapping.Edition'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'Cfihos20ReferenceDataMapping.Edition': ...
        @staticmethod
        def values() -> typing.MutableSequence['Cfihos20ReferenceDataMapping.Edition']: ...
    class NodeClassification(java.io.Serializable):
        def getEquipmentClassId(self) -> java.lang.String: ...
        def getTagClassId(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class PropertyDefinition(java.io.Serializable):
        def getPropertyId(self) -> java.lang.String: ...
        def getUnitOfMeasureId(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.handover")``.

    Cfihos20HandoverExporter: typing.Type[Cfihos20HandoverExporter]
    Cfihos20HandoverReport: typing.Type[Cfihos20HandoverReport]
    Cfihos20ReferenceDataMapping: typing.Type[Cfihos20ReferenceDataMapping]
