
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.calculation
import typing



class ValveInstrumentQualificationCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['ValveInstrumentQualificationCalculation.Input', 'ValveInstrumentQualificationCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'ValveInstrumentQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'ValveInstrumentQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['ValveInstrumentQualificationCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
        class Builder:
            def actuator(self, double: float, double2: float, double3: float, double4: float) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
            def approvals(self, boolean: bool, boolean2: bool, boolean3: bool, boolean4: bool, boolean5: bool) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
            def build(self) -> 'ValveInstrumentQualificationCalculation.Input': ...
            def leakage(self, double: float, double2: float) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
            def responseBudget(self, double: float, double2: float, double3: float, double4: float) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
            def thermowell(self, double: float, double2: float, double3: float) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
            def transmitterRange(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> 'ValveInstrumentQualificationCalculation.Input.Builder': ...
    class Result(jneqsim.process.engineering.calculation.EngineeringConstraintResult, java.io.Serializable):
        def allConstraintsSatisfied(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.instrumentation")``.

    ValveInstrumentQualificationCalculation: typing.Type[ValveInstrumentQualificationCalculation]
