
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.equipment
import jneqsim.util.validation
import typing



class BatteryStorage(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    ELECTRICAL_PORT: typing.ClassVar[java.lang.String] = ...
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...
    def charge(self, double: float, double2: float) -> None: ...
    def discharge(self, double: float, double2: float) -> float: ...
    def enableAutomaticBalancing(self, double: float, double2: float, int: int) -> None: ...
    def getCapacity(self) -> float: ...
    def getCurrentPower(self) -> float: ...
    def getStateOfCharge(self) -> float: ...
    def getStateOfChargeFraction(self) -> float: ...
    def isTripped(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setCapacity(self, double: float) -> None: ...
    def setEfficiencies(self, double: float, double2: float) -> None: ...
    def setPowerLimits(self, double: float, double2: float) -> None: ...
    def setPowerRampRate(self, double: float) -> None: ...
    def setStateOfCharge(self, double: float) -> None: ...
    def setTargetPower(self, double: float) -> None: ...
    def setTripped(self, boolean: bool) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.battery")``.

    BatteryStorage: typing.Type[BatteryStorage]
