
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.compressor
import jneqsim.process.equipment.compressor.driver
import jneqsim.process.equipment.expander
import jneqsim.process.equipment.stream
import jneqsim.process.processmodel
import jneqsim.process.util.report
import jneqsim.util.validation
import typing



class CommittedEnergyGenerator(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    OUTPUT_PORT: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], energyType: jneqsim.process.equipment.stream.EnergyType): ...
    def getCumulativeStartupCost(self) -> float: ...
    def getCumulativeStartupEmissionsKg(self) -> float: ...
    def getCurrentPower(self) -> float: ...
    def getLastStepResult(self) -> 'CommittedEnergyGenerator.StepResult': ...
    def getOutputType(self) -> jneqsim.process.equipment.stream.EnergyType: ...
    def getRequestedPower(self) -> float: ...
    def getStartupCount(self) -> int: ...
    def getTimeInState(self) -> float: ...
    def initializeCommitment(self, boolean: bool, double: float, double2: float) -> None: ...
    def isCommitted(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setMinimumUpDownTimes(self, double: float, double2: float) -> None: ...
    def setPowerLimits(self, double: float, double2: float) -> None: ...
    def setRampRates(self, double: float, double2: float) -> None: ...
    def setRequestedPower(self, double: float) -> None: ...
    def setStartupPenalty(self, double: float, double2: float) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...
    class StepResult(java.io.Serializable):
        def getGeneratedPower(self) -> float: ...
        def getRequestedPower(self) -> float: ...
        def isCommitted(self) -> bool: ...
        def isStartBlocked(self) -> bool: ...
        def isStarted(self) -> bool: ...
        def isStopBlocked(self) -> bool: ...
        def isStopped(self) -> bool: ...

class CoupledProcessEnergyResult(java.io.Serializable):
    def __init__(self, boolean: bool, terminationReason: 'CoupledProcessEnergyResult.TerminationReason', int: int, double: float, double2: float, list: java.util.List['CoupledProcessEnergyResult.IterationResult'], list2: java.util.List[jneqsim.process.equipment.stream.EnergyNetworkReport]): ...
    def getEnergyReports(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyNetworkReport]: ...
    def getIterationHistory(self) -> java.util.List['CoupledProcessEnergyResult.IterationResult']: ...
    def getIterations(self) -> int: ...
    def getMaximumPowerResidual(self) -> float: ...
    def getMaximumProcessResidual(self) -> float: ...
    def getTerminationReason(self) -> 'CoupledProcessEnergyResult.TerminationReason': ...
    def isConverged(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    class IterationResult(java.io.Serializable):
        def __init__(self, int: int, double: float, double2: float, boolean: bool): ...
        def getIteration(self) -> int: ...
        def getPowerResidual(self) -> float: ...
        def getProcessResidual(self) -> float: ...
        def isConverged(self) -> bool: ...
    class TerminationReason(java.lang.Enum['CoupledProcessEnergyResult.TerminationReason']):
        CONVERGED: typing.ClassVar['CoupledProcessEnergyResult.TerminationReason'] = ...
        MAXIMUM_ITERATIONS: typing.ClassVar['CoupledProcessEnergyResult.TerminationReason'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CoupledProcessEnergyResult.TerminationReason': ...
        @staticmethod
        def values() -> typing.MutableSequence['CoupledProcessEnergyResult.TerminationReason']: ...

class CoupledProcessEnergySolver(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def addEnergyBus(self, energyBus: jneqsim.process.equipment.stream.EnergyBus) -> None: ...
    def getEnergyBuses(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyBus]: ...
    def getMaximumIterations(self) -> int: ...
    def getMinimumIterations(self) -> int: ...
    def getPowerTolerance(self) -> float: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProcessTolerance(self) -> float: ...
    def getRelaxationFactor(self) -> float: ...
    def run(self) -> CoupledProcessEnergyResult: ...
    def setMaximumIterations(self, int: int) -> None: ...
    def setMinimumIterations(self, int: int) -> None: ...
    def setPowerTolerance(self, double: float) -> None: ...
    def setProcessTolerance(self, double: float) -> None: ...
    def setRelaxationFactor(self, double: float) -> None: ...
    def solve(self) -> CoupledProcessEnergyResult: ...

class EnergyConverter(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    INPUT_PORT: typing.ClassVar[java.lang.String] = ...
    OUTPUT_PORT: typing.ClassVar[java.lang.String] = ...
    LOSS_PORT: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], energyType: jneqsim.process.equipment.stream.EnergyType, energyType2: jneqsim.process.equipment.stream.EnergyType): ...
    def getEfficiency(self) -> float: ...
    def getHeatLoss(self) -> float: ...
    def getIdleLoss(self) -> float: ...
    def getInputPower(self) -> float: ...
    def getInputType(self) -> jneqsim.process.equipment.stream.EnergyType: ...
    def getMaximumInputPower(self) -> float: ...
    def getOperatingEfficiency(self) -> float: ...
    def getOutputPower(self) -> float: ...
    def getOutputType(self) -> jneqsim.process.equipment.stream.EnergyType: ...
    def getRampRate(self) -> float: ...
    def getRequiredInputPowerForOutput(self, double: float) -> float: ...
    def isTripped(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setEfficiency(self, double: float) -> None: ...
    def setIdleLoss(self, double: float) -> None: ...
    def setMaximumInputPower(self, double: float) -> None: ...
    def setRampRate(self, double: float) -> None: ...
    def setRequestedInputPower(self, double: float) -> None: ...
    def setTripped(self, boolean: bool) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class EnergyNetworkSolver(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], energyBus: jneqsim.process.equipment.stream.EnergyBus): ...
    def addEnergyBus(self, energyBus: jneqsim.process.equipment.stream.EnergyBus) -> None: ...
    def getEnergyBuses(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyBus]: ...
    def getReports(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyNetworkReport]: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class EnergyTimeSeriesProfile(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], interpolation: 'EnergyTimeSeriesProfile.Interpolation', list: java.util.List['EnergyTimeSeriesProfile.Point']): ...
    def getEndTimeSeconds(self) -> float: ...
    def getInterpolation(self) -> 'EnergyTimeSeriesProfile.Interpolation': ...
    def getName(self) -> java.lang.String: ...
    def getPoints(self) -> java.util.List['EnergyTimeSeriesProfile.Point']: ...
    def getValue(self, double: float) -> float: ...
    @staticmethod
    def linear(string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> 'EnergyTimeSeriesProfile': ...
    @staticmethod
    def step(string: typing.Union[java.lang.String, str], doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> 'EnergyTimeSeriesProfile': ...
    class Interpolation(java.lang.Enum['EnergyTimeSeriesProfile.Interpolation']):
        STEP: typing.ClassVar['EnergyTimeSeriesProfile.Interpolation'] = ...
        LINEAR: typing.ClassVar['EnergyTimeSeriesProfile.Interpolation'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EnergyTimeSeriesProfile.Interpolation': ...
        @staticmethod
        def values() -> typing.MutableSequence['EnergyTimeSeriesProfile.Interpolation']: ...
    class Point(java.io.Serializable):
        def __init__(self, double: float, double2: float): ...
        def getTimeSeconds(self) -> float: ...
        def getValue(self) -> float: ...

class EnergyTimeSeriesResult(java.io.Serializable):
    def getCo2EmissionsKg(self) -> float: ...
    def getCurtailedEnergyMWh(self) -> float: ...
    def getIntervals(self) -> java.util.List['EnergyTimeSeriesResult.IntervalResult']: ...
    def getOperatingCost(self) -> float: ...
    def getServedEnergyMWh(self) -> float: ...
    def getTotalDurationSeconds(self) -> float: ...
    def getUnmetEnergyMWh(self) -> float: ...
    def toJson(self) -> java.lang.String: ...
    class IntervalResult(java.io.Serializable):
        def getDurationSeconds(self) -> float: ...
        def getIntervalIndex(self) -> int: ...
        def getNetworkReports(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyNetworkReport]: ...
        def getStartTimeSeconds(self) -> float: ...

class EnergyTimeSeriesSimulator(java.io.Serializable):
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem): ...
    def addEnergyBus(self, energyBus: jneqsim.process.equipment.stream.EnergyBus) -> None: ...
    def addProfile(self, energyTimeSeriesProfile: EnergyTimeSeriesProfile, profileTarget: typing.Union['EnergyTimeSeriesSimulator.ProfileTarget', typing.Callable]) -> None: ...
    def getDurationSeconds(self) -> float: ...
    def getEnergyBuses(self) -> java.util.List[jneqsim.process.equipment.stream.EnergyBus]: ...
    def getExecutionMode(self) -> 'EnergyTimeSeriesSimulator.ExecutionMode': ...
    def getIntervalSeconds(self) -> float: ...
    def getProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getProfileBindings(self) -> java.util.List['EnergyTimeSeriesSimulator.ProfileBinding']: ...
    def run(self) -> EnergyTimeSeriesResult: ...
    def setDurationSeconds(self, double: float) -> None: ...
    def setExecutionMode(self, executionMode: 'EnergyTimeSeriesSimulator.ExecutionMode') -> None: ...
    def setIntervalSeconds(self, double: float) -> None: ...
    class ExecutionMode(java.lang.Enum['EnergyTimeSeriesSimulator.ExecutionMode']):
        STEADY_STATE: typing.ClassVar['EnergyTimeSeriesSimulator.ExecutionMode'] = ...
        TRANSIENT: typing.ClassVar['EnergyTimeSeriesSimulator.ExecutionMode'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EnergyTimeSeriesSimulator.ExecutionMode': ...
        @staticmethod
        def values() -> typing.MutableSequence['EnergyTimeSeriesSimulator.ExecutionMode']: ...
    class ProfileBinding:
        def __init__(self, energyTimeSeriesProfile: EnergyTimeSeriesProfile, profileTarget: typing.Union['EnergyTimeSeriesSimulator.ProfileTarget', typing.Callable]): ...
        def getProfile(self) -> EnergyTimeSeriesProfile: ...
    class ProfileTarget:
        def apply(self, double: float) -> None: ...

class LoadEfficiencyCurve(java.io.Serializable):
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def getEfficiencies(self) -> typing.MutableSequence[float]: ...
    def getEfficiency(self, double: float) -> float: ...
    def getLoadFractions(self) -> typing.MutableSequence[float]: ...
    def toString(self) -> java.lang.String: ...

class MotorAssistedDriveTrain(java.io.Serializable):
    def __init__(self, expander: jneqsim.process.equipment.expander.Expander, compressor: jneqsim.process.equipment.compressor.Compressor, electricMotor: 'ElectricMotor', energyBus: jneqsim.process.equipment.stream.EnergyBus, mechanicalShaft: jneqsim.process.equipment.stream.MechanicalShaft): ...
    def getAssistMotor(self) -> 'ElectricMotor': ...
    def getShaft(self) -> jneqsim.process.equipment.stream.MechanicalShaft: ...
    def setPowerTargets(self, double: float, double2: float) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class MotorDriveTrain(java.io.Serializable):
    def __init__(self, electricMotor: 'ElectricMotor', processEquipmentBaseClass: jneqsim.process.equipment.ProcessEquipmentBaseClass, energyBus: jneqsim.process.equipment.stream.EnergyBus, mechanicalShaft: jneqsim.process.equipment.stream.MechanicalShaft): ...
    def getDrivenEquipment(self) -> jneqsim.process.equipment.ProcessEquipmentBaseClass: ...
    def getElectricalBus(self) -> jneqsim.process.equipment.stream.EnergyBus: ...
    def getMotor(self) -> 'ElectricMotor': ...
    def getShaft(self) -> jneqsim.process.equipment.stream.MechanicalShaft: ...
    def setRequestedShaftPower(self, double: float) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class OffshoreEnergyReferenceCase:
    @staticmethod
    def getGasGeneratedEnergyMWh(energyTimeSeriesResult: EnergyTimeSeriesResult) -> float: ...
    @staticmethod
    def getWindCurtailedEnergyMWh(energyTimeSeriesResult: EnergyTimeSeriesResult) -> float: ...
    @staticmethod
    def getWindGeneratedEnergyMWh(energyTimeSeriesResult: EnergyTimeSeriesResult) -> float: ...
    @staticmethod
    def requireAcceptanceCriteria(energyTimeSeriesResult: EnergyTimeSeriesResult) -> None: ...
    @staticmethod
    def run24HourCase() -> EnergyTimeSeriesResult: ...

class ThermalUtilityConsumer(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    INPUT_PORT: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], utilityLevel: jneqsim.process.equipment.stream.UtilityLevel): ...
    def clearProcessTemperatureRequirement(self) -> None: ...
    def getAllocatedPower(self) -> float: ...
    def getMinimumApproachTemperature(self) -> float: ...
    def getRequiredProcessTemperature(self) -> float: ...
    def getUtilityLevel(self) -> jneqsim.process.equipment.stream.UtilityLevel: ...
    def hasProcessTemperatureRequirement(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setProcessTemperatureRequirement(self, double: float, double2: float) -> None: ...
    def setRequestedPower(self, double: float) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class ThermalUtilityHydraulicModel(java.io.Serializable):
    def __init__(self): ...
    def getDensity(self) -> float: ...
    def getFlowArea(self) -> float: ...
    def getFrictionFactor(self, double: float) -> float: ...
    def getHydraulicPower(self, double: float) -> float: ...
    def getInternalDiameter(self) -> float: ...
    def getLength(self) -> float: ...
    def getMaximumMassFlow(self) -> float: ...
    def getPressureDrop(self, double: float) -> float: ...
    def getPumpPower(self, double: float) -> float: ...
    def getReynoldsNumber(self, double: float) -> float: ...
    def getVelocity(self, double: float) -> float: ...
    def isWithinCapacity(self, double: float) -> bool: ...
    def setCapacityLimits(self, double: float, double2: float) -> None: ...
    def setFluidProperties(self, double: float, double2: float) -> None: ...
    def setGeometry(self, double: float, double2: float, double3: float) -> None: ...
    def setLocalLossCoefficient(self, double: float) -> None: ...
    def setPumpEfficiency(self, double: float) -> None: ...

class ThermalUtilityQualityAnalysis:
    @staticmethod
    def canServeProcessTemperature(utilityEnergyBus: 'UtilityEnergyBus', double: float, double2: float) -> bool: ...
    @staticmethod
    def getCurtailedExergyRate(utilityEnergyBus: 'UtilityEnergyBus', double: float) -> float: ...
    @staticmethod
    def getEffectiveTemperature(utilityEnergyBus: 'UtilityEnergyBus') -> float: ...
    @staticmethod
    def getExergyFactor(utilityEnergyBus: 'UtilityEnergyBus', double: float) -> float: ...
    @staticmethod
    def getExergyRateForDuty(utilityEnergyBus: 'UtilityEnergyBus', double: float, double2: float) -> float: ...
    @staticmethod
    def getServedExergyRate(utilityEnergyBus: 'UtilityEnergyBus', double: float) -> float: ...
    @staticmethod
    def getUnmetExergyRate(utilityEnergyBus: 'UtilityEnergyBus', double: float) -> float: ...
    @staticmethod
    def isHeatingUtility(utilityLevel: jneqsim.process.equipment.stream.UtilityLevel) -> bool: ...
    @staticmethod
    def requireFeasibleProcessTemperature(utilityEnergyBus: 'UtilityEnergyBus', double: float, double2: float) -> None: ...

class ThermalUtilitySource(jneqsim.process.equipment.ProcessEquipmentBaseClass):
    OUTPUT_PORT: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], utilityLevel: jneqsim.process.equipment.stream.UtilityLevel): ...
    def getAvailablePower(self) -> float: ...
    def getUtilityLevel(self) -> jneqsim.process.equipment.stream.UtilityLevel: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setAvailablePower(self, double: float) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class ThermalUtilityState(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float): ...
    def getPressure(self) -> float: ...
    def getSpecificEnthalpy(self) -> float: ...
    def getTemperature(self) -> float: ...
    def toJson(self) -> java.lang.String: ...

class UtilityEnergyBus(jneqsim.process.equipment.stream.EnergyBus):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], utilityLevel: jneqsim.process.equipment.stream.UtilityLevel): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], utilityLevel: jneqsim.process.equipment.stream.UtilityLevel, double: float, double2: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], utilityLevel: jneqsim.process.equipment.stream.UtilityLevel, thermalUtilityState: ThermalUtilityState, thermalUtilityState2: ThermalUtilityState): ...
    def clearThermodynamicStates(self) -> None: ...
    def getAcceptedMassFlow(self) -> float: ...
    def getCurtailedMassFlow(self) -> float: ...
    @typing.overload
    def getMassFlowForDuty(self, double: float) -> float: ...
    @typing.overload
    def getMassFlowForDuty(self, double: float, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> float: ...
    def getOfferedMassFlow(self) -> float: ...
    def getRequestedMassFlow(self) -> float: ...
    def getReturnState(self) -> ThermalUtilityState: ...
    def getReturnTemperature(self) -> float: ...
    def getServedMassFlow(self) -> float: ...
    def getSpecificDuty(self) -> float: ...
    def getSupplyPressure(self) -> float: ...
    def getSupplyState(self) -> ThermalUtilityState: ...
    def getSupplyTemperature(self) -> float: ...
    def getUnmetMassFlow(self) -> float: ...
    def getUtilityLevel(self) -> jneqsim.process.equipment.stream.UtilityLevel: ...
    def hasThermodynamicStates(self) -> bool: ...
    def setReturnTemperature(self, double: float) -> None: ...
    def setSupplyPressure(self, double: float) -> None: ...
    def setSupplyTemperature(self, double: float) -> None: ...
    def setThermodynamicStates(self, thermalUtilityState: ThermalUtilityState, thermalUtilityState2: ThermalUtilityState) -> None: ...

class ElectricMotor(EnergyConverter):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...
    def clearOperatingSpeed(self) -> None: ...
    def clearPerformanceModel(self) -> None: ...
    def getAvailableShaftPower(self) -> float: ...
    def getEfficiencyAtOutputPower(self, double: float) -> float: ...
    def getOperatingSpeed(self) -> float: ...
    def getPerformanceModel(self) -> jneqsim.process.equipment.compressor.driver.ElectricMotorDriver: ...
    def hasPerformanceModel(self) -> bool: ...
    def setOperatingSpeed(self, double: float) -> None: ...
    def setPerformanceModel(self, electricMotorDriver: jneqsim.process.equipment.compressor.driver.ElectricMotorDriver) -> None: ...
    def validateSetup(self) -> jneqsim.util.validation.ValidationResult: ...

class Gearbox(EnergyConverter):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getSpeedRatio(self) -> float: ...
    def setSpeedRatio(self, double: float) -> None: ...

class Inverter(EnergyConverter):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getOutputFrequency(self) -> float: ...
    def getOutputVoltage(self) -> float: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setOutputElectricalQuality(self, double: float, double2: float) -> None: ...

class LoadMappedEnergyConverter(EnergyConverter):
    def clearLoadEfficiencyCurve(self) -> None: ...
    def getEfficiencyAtOutputPower(self, double: float) -> float: ...
    def getLoadEfficiencyCurve(self) -> LoadEfficiencyCurve: ...
    def getRatedOutputPower(self) -> float: ...
    def hasLoadEfficiencyCurve(self) -> bool: ...
    def setLoadEfficiencyCurve(self, loadEfficiencyCurve: LoadEfficiencyCurve) -> None: ...
    def setRatedOutputPower(self, double: float) -> None: ...

class Generator(LoadMappedEnergyConverter):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...

class PrimeMover(LoadMappedEnergyConverter):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], double: float): ...

class Transformer(LoadMappedEnergyConverter):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def getVoltageRatio(self) -> float: ...
    def setVoltageRatio(self, double: float) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.energy")``.

    CommittedEnergyGenerator: typing.Type[CommittedEnergyGenerator]
    CoupledProcessEnergyResult: typing.Type[CoupledProcessEnergyResult]
    CoupledProcessEnergySolver: typing.Type[CoupledProcessEnergySolver]
    ElectricMotor: typing.Type[ElectricMotor]
    EnergyConverter: typing.Type[EnergyConverter]
    EnergyNetworkSolver: typing.Type[EnergyNetworkSolver]
    EnergyTimeSeriesProfile: typing.Type[EnergyTimeSeriesProfile]
    EnergyTimeSeriesResult: typing.Type[EnergyTimeSeriesResult]
    EnergyTimeSeriesSimulator: typing.Type[EnergyTimeSeriesSimulator]
    Gearbox: typing.Type[Gearbox]
    Generator: typing.Type[Generator]
    Inverter: typing.Type[Inverter]
    LoadEfficiencyCurve: typing.Type[LoadEfficiencyCurve]
    LoadMappedEnergyConverter: typing.Type[LoadMappedEnergyConverter]
    MotorAssistedDriveTrain: typing.Type[MotorAssistedDriveTrain]
    MotorDriveTrain: typing.Type[MotorDriveTrain]
    OffshoreEnergyReferenceCase: typing.Type[OffshoreEnergyReferenceCase]
    PrimeMover: typing.Type[PrimeMover]
    ThermalUtilityConsumer: typing.Type[ThermalUtilityConsumer]
    ThermalUtilityHydraulicModel: typing.Type[ThermalUtilityHydraulicModel]
    ThermalUtilityQualityAnalysis: typing.Type[ThermalUtilityQualityAnalysis]
    ThermalUtilitySource: typing.Type[ThermalUtilitySource]
    ThermalUtilityState: typing.Type[ThermalUtilityState]
    Transformer: typing.Type[Transformer]
    UtilityEnergyBus: typing.Type[UtilityEnergyBus]
