
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class EngineeringAutomationStudy(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addConstraint(self, constraint: 'EngineeringAutomationStudy.Constraint') -> 'EngineeringAutomationStudy': ...
    def addDecisionVariable(self, decisionVariable: 'EngineeringAutomationStudy.DecisionVariable') -> 'EngineeringAutomationStudy': ...
    def addObjective(self, objective: 'EngineeringAutomationStudy.Objective') -> 'EngineeringAutomationStudy': ...
    def getConstraints(self) -> java.util.List['EngineeringAutomationStudy.Constraint']: ...
    def getDecisionVariables(self) -> java.util.List['EngineeringAutomationStudy.DecisionVariable']: ...
    def getId(self) -> java.lang.String: ...
    def getName(self) -> java.lang.String: ...
    def getObjectives(self) -> java.util.List['EngineeringAutomationStudy.Objective']: ...
    class Constraint(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, string3: typing.Union[java.lang.String, str], constraintSeverity: 'EngineeringAutomationStudy.ConstraintSeverity', string4: typing.Union[java.lang.String, str]): ...
        def getId(self) -> java.lang.String: ...
        def getLowerBound(self) -> float: ...
        def getMetricKey(self) -> java.lang.String: ...
        def getSeverity(self) -> 'EngineeringAutomationStudy.ConstraintSeverity': ...
        def getStandardsReference(self) -> java.lang.String: ...
        def getUnit(self) -> java.lang.String: ...
        def getUpperBound(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class ConstraintSeverity(java.lang.Enum['EngineeringAutomationStudy.ConstraintSeverity']):
        HARD: typing.ClassVar['EngineeringAutomationStudy.ConstraintSeverity'] = ...
        ADVISORY: typing.ClassVar['EngineeringAutomationStudy.ConstraintSeverity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringAutomationStudy.ConstraintSeverity': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringAutomationStudy.ConstraintSeverity']: ...
    class DecisionVariable(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, string4: typing.Union[java.lang.String, str]): ...
        def getGraphNodeId(self) -> java.lang.String: ...
        def getId(self) -> java.lang.String: ...
        def getInitialValue(self) -> float: ...
        def getLowerBound(self) -> float: ...
        def getProcessAddress(self) -> java.lang.String: ...
        def getScreeningLevels(self) -> int: ...
        def getUnit(self) -> java.lang.String: ...
        def getUpperBound(self) -> float: ...
        def setScreeningLevels(self, int: int) -> 'EngineeringAutomationStudy.DecisionVariable': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Objective(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], objectiveSense: 'EngineeringAutomationStudy.ObjectiveSense', double: float): ...
        def getId(self) -> java.lang.String: ...
        def getMetricKey(self) -> java.lang.String: ...
        def getSense(self) -> 'EngineeringAutomationStudy.ObjectiveSense': ...
        def getWeight(self) -> float: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class ObjectiveSense(java.lang.Enum['EngineeringAutomationStudy.ObjectiveSense']):
        MINIMIZE: typing.ClassVar['EngineeringAutomationStudy.ObjectiveSense'] = ...
        MAXIMIZE: typing.ClassVar['EngineeringAutomationStudy.ObjectiveSense'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringAutomationStudy.ObjectiveSense': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringAutomationStudy.ObjectiveSense']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.automation")``.

    EngineeringAutomationStudy: typing.Type[EngineeringAutomationStudy]
