
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import jpype
import typing



class BukacekWaterInGas:
    def __init__(self): ...
    @staticmethod
    def getWaterInGas(double: float, double2: float) -> float: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @staticmethod
    def waterDewPointTemperature(double: float, double2: float) -> float: ...

class DuanSun:
    def __init__(self): ...
    def bublePointPressure(self, double: float, double2: float, double3: float) -> float: ...
    def calcCO2solubility(self, double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...

class NitricSulfuricAcidVaporPressure:
    MIN_RECOMMENDED_TEMPERATURE_K: typing.ClassVar[float] = ...
    MAX_RECOMMENDED_TEMPERATURE_K: typing.ClassVar[float] = ...
    MOLAR_MASS_WATER: typing.ClassVar[float] = ...
    MOLAR_MASS_NITRIC: typing.ClassVar[float] = ...
    MOLAR_MASS_SULFURIC: typing.ClassVar[float] = ...
    @staticmethod
    def activityCoefficientNitricAcid(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def activityCoefficientSulfuricAcid(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def activityCoefficientWater(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def isWithinRecommendedTemperatureRange(double: float) -> bool: ...
    @staticmethod
    def moleFractionsFromMassFractions(double: float, double2: float, double3: float) -> typing.MutableSequence[float]: ...
    @staticmethod
    def partialPressureNitricAcid(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def partialPressureSulfuricAcid(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def partialPressureWater(double: float, double2: float, double3: float, double4: float) -> float: ...
    @staticmethod
    def pureVaporPressureNitricAcid(double: float) -> float: ...
    @staticmethod
    def pureVaporPressureSulfuricAcid(double: float) -> float: ...
    @staticmethod
    def pureVaporPressureWater(double: float) -> float: ...

class Water:
    def __init__(self): ...
    def density(self) -> float: ...
    @staticmethod
    def main(stringArray: typing.Union[typing.List[java.lang.String], jpype.JArray]) -> None: ...
    @staticmethod
    def waterDensity(double: float) -> float: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.thermo.util.empiric")``.

    BukacekWaterInGas: typing.Type[BukacekWaterInGas]
    DuanSun: typing.Type[DuanSun]
    NitricSulfuricAcidVaporPressure: typing.Type[NitricSulfuricAcidVaporPressure]
    Water: typing.Type[Water]
