
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering
import jneqsim.process.engineering.dexpi
import jneqsim.process.engineering.pid.rules
import jneqsim.process.equipment
import typing



class NorsokPidRuleCatalog:
    @staticmethod
    def completeProposals() -> 'PidRuleCatalog': ...
    @staticmethod
    def controlAndInstrumentation() -> 'PidRuleCatalog': ...

class PidCompletenessFinding(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], severity: 'PidCompletenessFinding.Severity', string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def getSeverity(self) -> 'PidCompletenessFinding.Severity': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Severity(java.lang.Enum['PidCompletenessFinding.Severity']):
        ERROR: typing.ClassVar['PidCompletenessFinding.Severity'] = ...
        REVIEW: typing.ClassVar['PidCompletenessFinding.Severity'] = ...
        WARNING: typing.ClassVar['PidCompletenessFinding.Severity'] = ...
        INFORMATION: typing.ClassVar['PidCompletenessFinding.Severity'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'PidCompletenessFinding.Severity': ...
        @staticmethod
        def values() -> typing.MutableSequence['PidCompletenessFinding.Severity']: ...

class PidCompletenessReport(java.io.Serializable):
    def getFindings(self) -> java.util.List[PidCompletenessFinding]: ...
    def isReadyForApproval(self) -> bool: ...
    def isStructurallyComplete(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PidCompletenessValidator:
    @staticmethod
    def validate(pidDesignModel: 'PidDesignModel') -> PidCompletenessReport: ...

class PidDesignBasis(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def attribute(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'PidDesignBasis': ...
    def getAreaCode(self) -> java.lang.String: ...
    def getAttributes(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getFirstSequenceNumber(self) -> int: ...
    def getProfileId(self) -> java.lang.String: ...
    def getSequenceWidth(self) -> int: ...
    def isProposeControlFunctions(self) -> bool: ...
    def isProposeSafeguarding(self) -> bool: ...
    def setFirstSequenceNumber(self, int: int) -> 'PidDesignBasis': ...
    def setProposeControlFunctions(self, boolean: bool) -> 'PidDesignBasis': ...
    def setProposeSafeguarding(self, boolean: bool) -> 'PidDesignBasis': ...
    def setSequenceWidth(self, int: int) -> 'PidDesignBasis': ...

class PidDesignContext:
    def __init__(self, engineeringProject: jneqsim.process.engineering.EngineeringProject, pidDesignBasis: PidDesignBasis): ...
    def getBasis(self) -> PidDesignBasis: ...
    def getProject(self) -> jneqsim.process.engineering.EngineeringProject: ...
    def getTagAllocator(self) -> 'PidTagAllocator': ...
    def requirements(self, string: typing.Union[java.lang.String, str], type: jneqsim.process.engineering.EngineeringRequirement.Type) -> java.util.List[jneqsim.process.engineering.EngineeringRequirement]: ...

class PidDesignModel(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def add(self, pidElement: 'PidElement') -> 'PidDesignModel': ...
    def getElements(self) -> java.util.List['PidElement']: ...
    def getElementsByType(self, pidElementType: 'PidElementType') -> java.util.List['PidElement']: ...
    def getElementsForEquipment(self, string: typing.Union[java.lang.String, str]) -> java.util.List['PidElement']: ...
    def getProfileId(self) -> java.lang.String: ...
    def getProjectId(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PidDesignRule:
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List['PidElement']: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class PidDesignSynthesizer:
    @staticmethod
    def synthesize(engineeringProject: jneqsim.process.engineering.EngineeringProject, pidDesignBasis: PidDesignBasis, pidRuleCatalog: 'PidRuleCatalog') -> PidDesignModel: ...

class PidDexpiMaterializer:
    @staticmethod
    def materialize(pidDesignModel: PidDesignModel, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> None: ...

class PidElement(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], pidElementType: 'PidElementType'): ...
    def attribute(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'PidElement': ...
    def connect(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def description(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def equipment(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def getAttributes(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getConnectedElementIds(self) -> java.util.List[java.lang.String]: ...
    def getEquipmentTag(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getLineTag(self) -> java.lang.String: ...
    def getRequirementIds(self) -> java.util.List[java.lang.String]: ...
    def getRuleId(self) -> java.lang.String: ...
    def getStandardReferences(self) -> java.util.List[java.lang.String]: ...
    def getStatus(self) -> 'PidProposalStatus': ...
    def getTag(self) -> java.lang.String: ...
    def getType(self) -> 'PidElementType': ...
    def line(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def provenance(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def requirement(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def service(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def standard(self, string: typing.Union[java.lang.String, str]) -> 'PidElement': ...
    def status(self, pidProposalStatus: 'PidProposalStatus') -> 'PidElement': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PidElementType(java.lang.Enum['PidElementType']):
    MEASUREMENT: typing.ClassVar['PidElementType'] = ...
    INDICATOR: typing.ClassVar['PidElementType'] = ...
    CONTROLLER: typing.ClassVar['PidElementType'] = ...
    CONTROL_VALVE: typing.ClassVar['PidElementType'] = ...
    ISOLATION_VALVE: typing.ClassVar['PidElementType'] = ...
    SHUTDOWN_VALVE: typing.ClassVar['PidElementType'] = ...
    BLOWDOWN_VALVE: typing.ClassVar['PidElementType'] = ...
    CHECK_VALVE: typing.ClassVar['PidElementType'] = ...
    SAFETY_RELIEF_VALVE: typing.ClassVar['PidElementType'] = ...
    RUPTURE_DISK: typing.ClassVar['PidElementType'] = ...
    ALARM: typing.ClassVar['PidElementType'] = ...
    TRIP: typing.ClassVar['PidElementType'] = ...
    SAFETY_FUNCTION: typing.ClassVar['PidElementType'] = ...
    DRAIN: typing.ClassVar['PidElementType'] = ...
    VENT: typing.ClassVar['PidElementType'] = ...
    SAMPLE_POINT: typing.ClassVar['PidElementType'] = ...
    NOZZLE: typing.ClassVar['PidElementType'] = ...
    SIGNAL: typing.ClassVar['PidElementType'] = ...
    OFF_PAGE_CONNECTOR: typing.ClassVar['PidElementType'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'PidElementType': ...
    @staticmethod
    def values() -> typing.MutableSequence['PidElementType']: ...

class PidEngineeringPackageExporter:
    @staticmethod
    def export(engineeringProject: jneqsim.process.engineering.EngineeringProject, pidDesignModel: PidDesignModel, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'PidEngineeringPackageExporter.ExportResult': ...
    class ExportResult:
        def getCompletenessReportFile(self) -> java.nio.file.Path: ...
        def getDesignModelFile(self) -> java.nio.file.Path: ...
        def getEngineeringPackage(self) -> jneqsim.process.engineering.dexpi.DexpiEngineeringExporter.ExportResult: ...

class PidHazopStudyReport(java.io.Serializable):
    def getNodes(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
    def isReadyForHazopWorkshop(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class PidHazopStudyRunner:
    @staticmethod
    def run(engineeringProject: jneqsim.process.engineering.EngineeringProject, pidDesignModel: PidDesignModel) -> PidHazopStudyReport: ...

class PidProposalStatus(java.lang.Enum['PidProposalStatus']):
    PROPOSED: typing.ClassVar['PidProposalStatus'] = ...
    REVIEW_REQUIRED: typing.ClassVar['PidProposalStatus'] = ...
    APPROVED: typing.ClassVar['PidProposalStatus'] = ...
    REJECTED: typing.ClassVar['PidProposalStatus'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'PidProposalStatus': ...
    @staticmethod
    def values() -> typing.MutableSequence['PidProposalStatus']: ...

class PidRuleCatalog(java.io.Serializable):
    def __init__(self): ...
    def add(self, pidDesignRule: PidDesignRule) -> 'PidRuleCatalog': ...
    def getRules(self) -> java.util.List[PidDesignRule]: ...

class PidTagAllocator(java.io.Serializable):
    def __init__(self, pidDesignBasis: PidDesignBasis): ...
    def allocate(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    def reserve(self, string: typing.Union[java.lang.String, str]) -> 'PidTagAllocator': ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.pid")``.

    NorsokPidRuleCatalog: typing.Type[NorsokPidRuleCatalog]
    PidCompletenessFinding: typing.Type[PidCompletenessFinding]
    PidCompletenessReport: typing.Type[PidCompletenessReport]
    PidCompletenessValidator: typing.Type[PidCompletenessValidator]
    PidDesignBasis: typing.Type[PidDesignBasis]
    PidDesignContext: typing.Type[PidDesignContext]
    PidDesignModel: typing.Type[PidDesignModel]
    PidDesignRule: typing.Type[PidDesignRule]
    PidDesignSynthesizer: typing.Type[PidDesignSynthesizer]
    PidDexpiMaterializer: typing.Type[PidDexpiMaterializer]
    PidElement: typing.Type[PidElement]
    PidElementType: typing.Type[PidElementType]
    PidEngineeringPackageExporter: typing.Type[PidEngineeringPackageExporter]
    PidHazopStudyReport: typing.Type[PidHazopStudyReport]
    PidHazopStudyRunner: typing.Type[PidHazopStudyRunner]
    PidProposalStatus: typing.Type[PidProposalStatus]
    PidRuleCatalog: typing.Type[PidRuleCatalog]
    PidTagAllocator: typing.Type[PidTagAllocator]
    rules: jneqsim.process.engineering.pid.rules.__module_protocol__
