
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.thermo.system
import typing



class CombustionCalculator(java.io.Serializable):
    def __init__(self, systemInterface: jneqsim.thermo.system.SystemInterface): ...
    def calculate(self) -> 'CombustionCalculator.CombustionResult': ...
    def calibrateCoFromMeasuredPpmv(self, double: float, double2: float) -> 'CombustionCalculator': ...
    def calibrateNoxFromMeasuredPpmv(self, double: float, double2: float) -> 'CombustionCalculator': ...
    @staticmethod
    def correctToReferenceO2(double: float, double2: float, double3: float) -> float: ...
    def enableThermalCoScaling(self, double: float) -> 'CombustionCalculator': ...
    def enableThermalNoxScaling(self, double: float) -> 'CombustionCalculator': ...
    def getBurnerType(self) -> 'CombustionCalculator.BurnerType': ...
    def getCoCalibrationFactor(self) -> float: ...
    def getNoxCalibrationFactor(self) -> float: ...
    def setAirFlowRate(self, double: float) -> 'CombustionCalculator': ...
    def setAnnualOperatingHours(self, double: float) -> 'CombustionCalculator': ...
    def setAssumedFuelH2sPpmv(self, double: float) -> 'CombustionCalculator': ...
    def setBurnerType(self, burnerType: 'CombustionCalculator.BurnerType') -> 'CombustionCalculator': ...
    def setCh4SlipFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setCoCalibrationFactor(self, double: float) -> 'CombustionCalculator': ...
    def setCoFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setExcessAirRatio(self, double: float) -> 'CombustionCalculator': ...
    def setFuelFlowRate(self, double: float) -> 'CombustionCalculator': ...
    def setFuelNoxFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setN2oFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setNormalTemperatureC(self, double: float) -> 'CombustionCalculator': ...
    def setNoxCalibrationFactor(self, double: float) -> 'CombustionCalculator': ...
    def setNoxFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setPmFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setPromptNoxFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    def setReferenceO2VolPercent(self, double: float) -> 'CombustionCalculator': ...
    def setSo3FractionOfSox(self, double: float) -> 'CombustionCalculator': ...
    def setStackDiameterM(self, double: float) -> 'CombustionCalculator': ...
    def setStackGasTemperatureC(self, double: float) -> 'CombustionCalculator': ...
    def setStackPressureBara(self, double: float) -> 'CombustionCalculator': ...
    def setThermalCoActivationTempK(self, double: float) -> 'CombustionCalculator': ...
    def setThermalNoxActivationTempK(self, double: float) -> 'CombustionCalculator': ...
    def setVocFactorGPerGJ(self, double: float) -> 'CombustionCalculator': ...
    class BurnerType(java.lang.Enum['CombustionCalculator.BurnerType']):
        CONVENTIONAL: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        LOW_NOX: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        ULTRA_LOW_NOX: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        GAS_TURBINE_CONVENTIONAL: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        GAS_TURBINE_DLE: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        GAS_TURBINE_WET: typing.ClassVar['CombustionCalculator.BurnerType'] = ...
        def getCoGPerGJ(self) -> float: ...
        def getDescription(self) -> java.lang.String: ...
        def getNoxGPerGJ(self) -> float: ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'CombustionCalculator.BurnerType': ...
        @staticmethod
        def values() -> typing.MutableSequence['CombustionCalculator.BurnerType']: ...
    class CombustionResult(java.io.Serializable):
        excessAirRatio: float = ...
        airDriven: bool = ...
        airFlowKgPerHr: float = ...
        subStoichiometric: bool = ...
        fuelFlowKgPerHr: float = ...
        fuelH2sBasis: java.lang.String = ...
        fuelLhvKJperKg: float = ...
        fuelEnergyGJperHr: float = ...
        airFuelMassRatio: float = ...
        stoichAirFuelMassRatio: float = ...
        exhaustO2VolPercent: float = ...
        exhaustO2VolPercentDry: float = ...
        waterVolPercent: float = ...
        totalFlueKgPerHr: float = ...
        adiabaticFlameTemperatureK: float = ...
        flueMoleFraction: java.util.Map = ...
        pollutantPpmv: java.util.Map = ...
        pollutantPpmvDry: java.util.Map = ...
        pollutantPpmvAtReferenceO2: java.util.Map = ...
        referenceO2VolPercent: float = ...
        pollutantMgPerNm3Dry: java.util.Map = ...
        pollutantMgPerNm3AtReferenceO2: java.util.Map = ...
        normalTemperatureC: float = ...
        flueGasNm3PerHrWet: float = ...
        flueGasNm3PerHrDry: float = ...
        annualOperatingHours: float = ...
        massRateTonnesPerYear: java.util.Map = ...
        noxThermalKgPerHr: float = ...
        noxPromptKgPerHr: float = ...
        noxFuelKgPerHr: float = ...
        stackGasTemperatureC: float = ...
        stackPressureBara: float = ...
        stackActualM3PerHr: float = ...
        stackVelocityMPerS: float = ...
        waterDewPointC: float = ...
        acidDewPointC: float = ...
        noxCalibrationFactor: float = ...
        coCalibrationFactor: float = ...
        massRateKgPerHr: java.util.Map = ...
        def __init__(self): ...
        def getFlueMoleFraction(self, string: typing.Union[java.lang.String, str]) -> float: ...
        def getMassRateKgPerHr(self, string: typing.Union[java.lang.String, str]) -> float: ...
        def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.util.combustion")``.

    CombustionCalculator: typing.Type[CombustionCalculator]
