
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import jpype
import typing



class GasMaterialBalance(java.io.Serializable):
    @staticmethod
    def bg(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def colePlot(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], double4: float) -> typing.MutableSequence[typing.MutableSequence[float]]: ...
    @staticmethod
    def fitHavlenaOdeh(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], doubleArray4: typing.Union[typing.List[float], jpype.JArray], double5: float) -> 'GasMaterialBalance.Result': ...
    @typing.overload
    @staticmethod
    def fitVolumetric(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float, double4: float) -> 'GasMaterialBalance.Result': ...
    @typing.overload
    @staticmethod
    def fitVolumetric(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> 'GasMaterialBalance.Result': ...
    class Result(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float): ...
        def getOgip(self) -> float: ...
        def getPiOverZi(self) -> float: ...
        def getRSquared(self) -> float: ...
        def getSlope(self) -> float: ...

class OilMaterialBalance(java.io.Serializable):
    @staticmethod
    def driveIndices(double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float) -> typing.MutableSequence[float]: ...
    @staticmethod
    def efw(double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> float: ...
    @staticmethod
    def eg(double: float, double2: float, double3: float) -> float: ...
    @staticmethod
    def eo(double: float, double2: float, double3: float, double4: float, double5: float) -> float: ...
    @staticmethod
    def fitDepletionDrive(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> 'OilMaterialBalance.Result': ...
    @staticmethod
    def fitGasCapDrive(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray]) -> 'OilMaterialBalance.Result': ...
    @staticmethod
    def fitWaterDrive(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], doubleArray3: typing.Union[typing.List[float], jpype.JArray], double4: float) -> 'OilMaterialBalance.Result': ...
    @staticmethod
    def withdrawalF(double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float) -> float: ...
    class Result(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float): ...
        def getM(self) -> float: ...
        def getOoip(self) -> float: ...
        def getRSquared(self) -> float: ...

class VanEverdingenHurstAquifer(java.io.Serializable):
    @staticmethod
    def aquiferConstant(double: float, double2: float, double3: float, double4: float, double5: float) -> float: ...
    @staticmethod
    def cumulativeInfluxCarterTracy(doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray], double3: float, double4: float) -> typing.MutableSequence[float]: ...
    @staticmethod
    def dimensionlessPressure(double: float, double2: float) -> float: ...
    @staticmethod
    def dimensionlessPressureDerivative(double: float, double2: float) -> float: ...
    @staticmethod
    def dimensionlessTime(double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> float: ...
    @staticmethod
    def exportAqutab(doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float) -> java.lang.String: ...
    @staticmethod
    def influenceTable(doubleArray: typing.Union[typing.List[float], jpype.JArray], double2: float) -> typing.MutableSequence[float]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.pvtsimulation.reservoirproperties.materialbalance")``.

    GasMaterialBalance: typing.Type[GasMaterialBalance]
    OilMaterialBalance: typing.Type[OilMaterialBalance]
    VanEverdingenHurstAquifer: typing.Type[VanEverdingenHurstAquifer]
