
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering
import jneqsim.process.engineering.designcase
import jneqsim.process.engineering.dexpi
import jneqsim.process.engineering.model
import jneqsim.process.engineering.validation
import typing



class EngineeringApprovalLedger:
    @staticmethod
    def build(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, engineeringGraphDiff: jneqsim.process.engineering.model.EngineeringGraphDiff) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringAutomationPlan:
    @staticmethod
    def build(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, engineeringDesignEnvelope: jneqsim.process.engineering.designcase.EngineeringDesignEnvelope) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDeliverableCompiler:
    @typing.overload
    @staticmethod
    def compile(engineeringProject: jneqsim.process.engineering.EngineeringProject, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'EngineeringDeliverableCompiler.CompilationResult': ...
    @typing.overload
    @staticmethod
    def compile(engineeringProject: jneqsim.process.engineering.EngineeringProject, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph) -> 'EngineeringDeliverableCompiler.CompilationResult': ...
    class CompilationResult:
        def getCompilerManifestFile(self) -> java.nio.file.Path: ...
        def getDesignEnvelope(self) -> jneqsim.process.engineering.designcase.EngineeringDesignEnvelope: ...
        def getDesignEnvelopeFile(self) -> java.nio.file.Path: ...
        def getDexpiResult(self) -> jneqsim.process.engineering.dexpi.DexpiEngineeringExporter.ExportResult: ...
        def getEngineeringApprovalLedgerFile(self) -> java.nio.file.Path: ...
        def getEngineeringAutomationPlanFile(self) -> java.nio.file.Path: ...
        def getEngineeringCalculationDagFile(self) -> java.nio.file.Path: ...
        def getEngineeringConnectivityFile(self) -> java.nio.file.Path: ...
        def getEngineeringDesignCaseMatrixFile(self) -> java.nio.file.Path: ...
        def getEngineeringDexpiRoundTripReportFile(self) -> java.nio.file.Path: ...
        def getEngineeringDisciplinePackageFile(self) -> java.nio.file.Path: ...
        def getEngineeringGraph(self) -> jneqsim.process.engineering.model.EngineeringGraph: ...
        def getEngineeringGraphFile(self) -> java.nio.file.Path: ...
        def getEquipmentRegisterFile(self) -> java.nio.file.Path: ...
        def getInstrumentRegisterFile(self) -> java.nio.file.Path: ...
        def getLineRegisterFile(self) -> java.nio.file.Path: ...
        def getModelPackageFile(self) -> java.nio.file.Path: ...
        def getNumericalHealthFile(self) -> java.nio.file.Path: ...
        def getOutputDirectory(self) -> java.nio.file.Path: ...
        def getProductionReadinessFile(self) -> java.nio.file.Path: ...
        def getQualificationPlanFile(self) -> java.nio.file.Path: ...
        def getRevisionDiffFile(self) -> java.nio.file.Path: ...
        def getValidationReport(self) -> jneqsim.process.engineering.validation.EngineeringPackageValidationReport: ...
        def getValidationReportFile(self) -> java.nio.file.Path: ...
        def getVerticalSliceExecutionManifestFile(self) -> java.nio.file.Path: ...
        def getVerticalSliceQualificationFile(self) -> java.nio.file.Path: ...

class EngineeringDisciplinePackage:
    @staticmethod
    def build(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, engineeringDesignEnvelope: jneqsim.process.engineering.designcase.EngineeringDesignEnvelope) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.deliverables")``.

    EngineeringApprovalLedger: typing.Type[EngineeringApprovalLedger]
    EngineeringAutomationPlan: typing.Type[EngineeringAutomationPlan]
    EngineeringDeliverableCompiler: typing.Type[EngineeringDeliverableCompiler]
    EngineeringDisciplinePackage: typing.Type[EngineeringDisciplinePackage]
