
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.engineering.calculation
import jneqsim.process.engineering.design
import jneqsim.process.engineering.designcase
import jneqsim.process.engineering.piping
import jneqsim.process.processmodel
import typing



class CompressorOperatingEnvelopeDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class CompressorPackageDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class ControlValveDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class HeatExchangerPreliminaryDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class InstrumentRangeAndResponseDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class InventoryEquipmentDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class LineHydraulicDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class MaterialSelectionDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], boolean: bool, boolean2: bool, boolean3: bool, double: float, double2: float, double3: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class PipingNetworkDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], pipingRulePack: jneqsim.process.engineering.piping.PipingRulePack, list: java.util.List['PipingNetworkDesignModule.SegmentDefinition']): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], pipingRulePack: jneqsim.process.engineering.piping.PipingRulePack, list: java.util.List['PipingNetworkDesignModule.SegmentDefinition'], doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...
    class SegmentDefinition(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], boolean: bool, boolean2: bool, double: float): ...
        def getLineTag(self) -> java.lang.String: ...
        @staticmethod
        def processLine(string: typing.Union[java.lang.String, str], boolean: bool) -> 'PipingNetworkDesignModule.SegmentDefinition': ...
        @staticmethod
        def reliefInlet(string: typing.Union[java.lang.String, str], boolean: bool, double: float) -> 'PipingNetworkDesignModule.SegmentDefinition': ...

class PressureEquipmentMechanicalDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, double2: float, double3: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class ProcessSafetyDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class PumpPackageDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, double2: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class RatedCapacityDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, doubleArray: typing.Union[typing.List[float], jpype.JArray]): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class ReliefDeviceDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], *double: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...

class SeparatorProcessDesignModule(jneqsim.process.engineering.design.EngineeringDesignModule):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], double: float, double2: float, double3: float): ...
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: jneqsim.process.engineering.design.EngineeringDesignState, engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.design.EngineeringDesignModuleResult: ...
    def getId(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.design.modules")``.

    CompressorOperatingEnvelopeDesignModule: typing.Type[CompressorOperatingEnvelopeDesignModule]
    CompressorPackageDesignModule: typing.Type[CompressorPackageDesignModule]
    ControlValveDesignModule: typing.Type[ControlValveDesignModule]
    HeatExchangerPreliminaryDesignModule: typing.Type[HeatExchangerPreliminaryDesignModule]
    InstrumentRangeAndResponseDesignModule: typing.Type[InstrumentRangeAndResponseDesignModule]
    InventoryEquipmentDesignModule: typing.Type[InventoryEquipmentDesignModule]
    LineHydraulicDesignModule: typing.Type[LineHydraulicDesignModule]
    MaterialSelectionDesignModule: typing.Type[MaterialSelectionDesignModule]
    PipingNetworkDesignModule: typing.Type[PipingNetworkDesignModule]
    PressureEquipmentMechanicalDesignModule: typing.Type[PressureEquipmentMechanicalDesignModule]
    ProcessSafetyDesignModule: typing.Type[ProcessSafetyDesignModule]
    PumpPackageDesignModule: typing.Type[PumpPackageDesignModule]
    RatedCapacityDesignModule: typing.Type[RatedCapacityDesignModule]
    ReliefDeviceDesignModule: typing.Type[ReliefDeviceDesignModule]
    SeparatorProcessDesignModule: typing.Type[SeparatorProcessDesignModule]
