
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class BasketTestPoint(java.io.Serializable):
    def __init__(self, selfHeatingGeometry: 'SelfHeatingGeometry', double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str]): ...
    def getCharacteristicDimensionM(self) -> float: ...
    def getCriticalTemperatureK(self) -> float: ...
    def getGeometry(self) -> 'SelfHeatingGeometry': ...

class BasketTestRegression:
    def __init__(self): ...
    @typing.overload
    def addPoint(self, basketTestPoint: BasketTestPoint) -> 'BasketTestRegression': ...
    @typing.overload
    def addPoint(self, selfHeatingGeometry: 'SelfHeatingGeometry', double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str]) -> 'BasketTestRegression': ...
    def regress(self) -> 'BasketTestRegressionResult': ...
    def setEffectiveThermalConductivity(self, double: float) -> 'BasketTestRegression': ...

class BasketTestRegressionResult(java.io.Serializable):
    def __init__(self, int: int, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, boolean: bool, list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def createAnalyzer(self, selfHeatingGeometry: 'SelfHeatingGeometry', double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str]) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def getActivationEnergyJPerMol(self) -> float: ...
    def getEffectiveConductivityWPerMK(self) -> float: ...
    def getIntercept(self) -> float: ...
    def getPointCount(self) -> int: ...
    def getRSquared(self) -> float: ...
    def getSlope(self) -> float: ...
    def getVolumetricPreFactorWPerM3(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isConductivityProvided(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class PorousMediaSelfHeatingAnalyzer:
    def __init__(self): ...
    def analyze(self) -> 'PorousMediaSelfHeatingResult': ...
    def forPipeInsulation(self, double: float, string: typing.Union[java.lang.String, str], double2: float, string2: typing.Union[java.lang.String, str]) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setActivationEnergy(self, double: float, string: typing.Union[java.lang.String, str]) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setBoundaryTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setCharacteristicDimension(self, double: float, string: typing.Union[java.lang.String, str]) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setEffectiveThermalConductivity(self, double: float) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setGeometry(self, selfHeatingGeometry: 'SelfHeatingGeometry') -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setKinetics(self, double: float, double2: float, double3: float) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setMarginalRatio(self, double: float) -> 'PorousMediaSelfHeatingAnalyzer': ...
    def setVolumetricHeatReleasePreFactor(self, double: float) -> 'PorousMediaSelfHeatingAnalyzer': ...

class PorousMediaSelfHeatingResult(java.io.Serializable):
    def __init__(self, selfHeatingGeometry: 'SelfHeatingGeometry', double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, double11: float, double12: float, double13: float, selfHeatingVerdict: 'SelfHeatingVerdict', list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getActivationEnergyJPerMol(self) -> float: ...
    def getBoundaryTemperatureK(self) -> float: ...
    def getCharacteristicDimensionM(self) -> float: ...
    def getCriticalDimensionM(self) -> float: ...
    def getCriticalTemperatureK(self) -> float: ...
    def getDelta(self) -> float: ...
    def getDeltaCrit(self) -> float: ...
    def getDeltaRatio(self) -> float: ...
    def getDimensionMarginM(self) -> float: ...
    def getEffectiveConductivityWPerMK(self) -> float: ...
    def getFkTemperatureScaleK(self) -> float: ...
    def getGeometry(self) -> 'SelfHeatingGeometry': ...
    def getTemperatureMarginK(self) -> float: ...
    def getVerdict(self) -> 'SelfHeatingVerdict': ...
    def getVolumetricPreFactorWPerM3(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isSelfIgnitionPredicted(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class SelfHeatingGeometry(java.lang.Enum['SelfHeatingGeometry']):
    SLAB: typing.ClassVar['SelfHeatingGeometry'] = ...
    INFINITE_CYLINDER: typing.ClassVar['SelfHeatingGeometry'] = ...
    SPHERE: typing.ClassVar['SelfHeatingGeometry'] = ...
    CUBE: typing.ClassVar['SelfHeatingGeometry'] = ...
    EQUICYLINDER: typing.ClassVar['SelfHeatingGeometry'] = ...
    def getDeltaCrit(self) -> float: ...
    def getDimensionDescription(self) -> java.lang.String: ...
    def getShapeFactor(self) -> int: ...
    def isOneDimensional(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'SelfHeatingGeometry': ...
    @staticmethod
    def values() -> typing.MutableSequence['SelfHeatingGeometry']: ...

class SelfHeatingInductionResult(java.io.Serializable):
    def __init__(self, selfHeatingGeometry: SelfHeatingGeometry, double: float, double2: float, double3: float, double4: float, boolean: bool, double5: float, double6: float, double7: float, boolean2: bool, double8: float, list: java.util.List['SelfHeatingTimePoint'], list2: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getBoundaryTemperatureK(self) -> float: ...
    def getCharacteristicDimensionM(self) -> float: ...
    def getGeometry(self) -> SelfHeatingGeometry: ...
    def getHistory(self) -> java.util.List['SelfHeatingTimePoint']: ...
    def getIgnitionRiseK(self) -> float: ...
    def getInductionTimeHours(self) -> float: ...
    def getInductionTimeS(self) -> float: ...
    def getInitialTemperatureK(self) -> float: ...
    def getPeakTemperatureK(self) -> float: ...
    def getPeakTemperatureRiseK(self) -> float: ...
    def getSimulatedTimeS(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isIgnited(self) -> bool: ...
    def isSteadyStateReached(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...

class SelfHeatingInductionSolver:
    def __init__(self): ...
    def setActivationEnergy(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SelfHeatingInductionSolver': ...
    def setBoundaryTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SelfHeatingInductionSolver': ...
    def setBulkProperties(self, double: float, double2: float) -> 'SelfHeatingInductionSolver': ...
    def setCharacteristicDimension(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SelfHeatingInductionSolver': ...
    def setEffectiveThermalConductivity(self, double: float) -> 'SelfHeatingInductionSolver': ...
    def setGeometry(self, selfHeatingGeometry: SelfHeatingGeometry) -> 'SelfHeatingInductionSolver': ...
    def setIgnitionRise(self, double: float) -> 'SelfHeatingInductionSolver': ...
    def setInitialTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SelfHeatingInductionSolver': ...
    def setMaxTime(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SelfHeatingInductionSolver': ...
    def setNodeCount(self, int: int) -> 'SelfHeatingInductionSolver': ...
    def setVolumetricHeatCapacity(self, double: float) -> 'SelfHeatingInductionSolver': ...
    def setVolumetricHeatReleasePreFactor(self, double: float) -> 'SelfHeatingInductionSolver': ...
    def solve(self) -> SelfHeatingInductionResult: ...

class SelfHeatingTimePoint(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float): ...
    def getCentreTemperatureK(self) -> float: ...
    def getMaxTemperatureK(self) -> float: ...
    def getTimeS(self) -> float: ...

class SelfHeatingVerdict(java.lang.Enum['SelfHeatingVerdict']):
    SUBCRITICAL: typing.ClassVar['SelfHeatingVerdict'] = ...
    MARGINAL: typing.ClassVar['SelfHeatingVerdict'] = ...
    SELF_IGNITION: typing.ClassVar['SelfHeatingVerdict'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'SelfHeatingVerdict': ...
    @staticmethod
    def values() -> typing.MutableSequence['SelfHeatingVerdict']: ...

class SemenovSelfHeatingAnalyzer:
    PSI_CRIT: typing.ClassVar[float] = ...
    def __init__(self): ...
    def analyze(self) -> 'SemenovSelfHeatingResult': ...
    def setActivationEnergy(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SemenovSelfHeatingAnalyzer': ...
    def setAmbientTemperature(self, double: float, string: typing.Union[java.lang.String, str]) -> 'SemenovSelfHeatingAnalyzer': ...
    def setBodySize(self, double: float, double2: float) -> 'SemenovSelfHeatingAnalyzer': ...
    def setHeatTransferCoefficient(self, double: float) -> 'SemenovSelfHeatingAnalyzer': ...
    def setMarginalRatio(self, double: float) -> 'SemenovSelfHeatingAnalyzer': ...
    def setVolumetricHeatReleasePreFactor(self, double: float) -> 'SemenovSelfHeatingAnalyzer': ...

class SemenovSelfHeatingResult(java.io.Serializable):
    def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float, double10: float, double11: float, double12: float, selfHeatingVerdict: SelfHeatingVerdict, list: java.util.List[typing.Union[java.lang.String, str]]): ...
    def getActivationEnergyJPerMol(self) -> float: ...
    def getAmbientTemperatureK(self) -> float: ...
    def getCriticalTemperatureK(self) -> float: ...
    def getCriticalTemperatureRiseK(self) -> float: ...
    def getHeatTransferCoefficientWPerM2K(self) -> float: ...
    def getPsi(self) -> float: ...
    def getPsiCrit(self) -> float: ...
    def getPsiRatio(self) -> float: ...
    def getSurfaceAreaM2(self) -> float: ...
    def getTemperatureMarginK(self) -> float: ...
    def getVerdict(self) -> SelfHeatingVerdict: ...
    def getVolumeM3(self) -> float: ...
    def getVolumetricPreFactorWPerM3(self) -> float: ...
    def getWarnings(self) -> java.util.List[java.lang.String]: ...
    def isSelfIgnitionPredicted(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.selfheating")``.

    BasketTestPoint: typing.Type[BasketTestPoint]
    BasketTestRegression: typing.Type[BasketTestRegression]
    BasketTestRegressionResult: typing.Type[BasketTestRegressionResult]
    PorousMediaSelfHeatingAnalyzer: typing.Type[PorousMediaSelfHeatingAnalyzer]
    PorousMediaSelfHeatingResult: typing.Type[PorousMediaSelfHeatingResult]
    SelfHeatingGeometry: typing.Type[SelfHeatingGeometry]
    SelfHeatingInductionResult: typing.Type[SelfHeatingInductionResult]
    SelfHeatingInductionSolver: typing.Type[SelfHeatingInductionSolver]
    SelfHeatingTimePoint: typing.Type[SelfHeatingTimePoint]
    SelfHeatingVerdict: typing.Type[SelfHeatingVerdict]
    SemenovSelfHeatingAnalyzer: typing.Type[SemenovSelfHeatingAnalyzer]
    SemenovSelfHeatingResult: typing.Type[SemenovSelfHeatingResult]
