
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util
import jneqsim.process.engineering.pid
import jneqsim.process.equipment
import typing



class CompressorControlPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class CompressorSafeguardingPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class PressureReliefPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class ProcessTopologyPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class PumpControlPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class PumpSafeguardingPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class SeparatorControlPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class SeparatorSafeguardingPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class ThermalControlPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...

class ThermalSafeguardingPidRule(jneqsim.process.engineering.pid.PidDesignRule):
    RULE_ID: typing.ClassVar[java.lang.String] = ...
    def __init__(self): ...
    def getId(self) -> java.lang.String: ...
    def getOrder(self) -> int: ...
    def propose(self, pidDesignContext: jneqsim.process.engineering.pid.PidDesignContext, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> java.util.List[jneqsim.process.engineering.pid.PidElement]: ...
    def supports(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> bool: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.pid.rules")``.

    CompressorControlPidRule: typing.Type[CompressorControlPidRule]
    CompressorSafeguardingPidRule: typing.Type[CompressorSafeguardingPidRule]
    PressureReliefPidRule: typing.Type[PressureReliefPidRule]
    ProcessTopologyPidRule: typing.Type[ProcessTopologyPidRule]
    PumpControlPidRule: typing.Type[PumpControlPidRule]
    PumpSafeguardingPidRule: typing.Type[PumpSafeguardingPidRule]
    SeparatorControlPidRule: typing.Type[SeparatorControlPidRule]
    SeparatorSafeguardingPidRule: typing.Type[SeparatorSafeguardingPidRule]
    ThermalControlPidRule: typing.Type[ThermalControlPidRule]
    ThermalSafeguardingPidRule: typing.Type[ThermalSafeguardingPidRule]
