
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import typing



class AcousticInducedVibrationResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, pipingFivLikelihood: 'PipingFivLikelihood', map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], string2: typing.Union[java.lang.String, str]): ...
    def getAllowablePwlDb(self) -> float: ...
    def getCircuitName(self) -> java.lang.String: ...
    def getContributingFactors(self) -> java.util.Map[java.lang.String, float]: ...
    def getLikelihood(self) -> 'PipingFivLikelihood': ...
    def getMarginDb(self) -> float: ...
    def getPwlDb(self) -> float: ...
    def getRecommendation(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...

class AcousticInducedVibrationScreening(java.io.Serializable):
    @staticmethod
    def bandFor(double: float) -> 'PipingFivLikelihood': ...
    @staticmethod
    def recommendation(pipingFivLikelihood: 'PipingFivLikelihood') -> java.lang.String: ...
    @staticmethod
    def screen(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float) -> AcousticInducedVibrationResult: ...

class FivLikelihoodResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, pipingFivLikelihood: 'PipingFivLikelihood', map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], string2: typing.Union[java.lang.String, str]): ...
    def getCircuitName(self) -> java.lang.String: ...
    def getContributingFactors(self) -> java.util.Map[java.lang.String, float]: ...
    def getLikelihood(self) -> 'PipingFivLikelihood': ...
    def getLofScore(self) -> float: ...
    def getRecommendation(self) -> java.lang.String: ...
    def toJson(self) -> java.lang.String: ...

class FlowInducedPulsationResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], pipingFivLikelihood: 'PipingFivLikelihood', boolean: bool, double: float, double2: float, list: java.util.List['FlowInducedPulsationResult.BranchMode'], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]], string2: typing.Union[java.lang.String, str]): ...
    def getBranchName(self) -> java.lang.String: ...
    def getContributingFactors(self) -> java.util.Map[java.lang.String, float]: ...
    def getLikelihood(self) -> 'PipingFivLikelihood': ...
    def getLowestResonanceVelocityMPerS(self) -> float: ...
    def getModes(self) -> java.util.List['FlowInducedPulsationResult.BranchMode']: ...
    def getRecommendation(self) -> java.lang.String: ...
    def getSheddingFrequencyHz(self) -> float: ...
    def isAnyModeLockedIn(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    class BranchMode(java.io.Serializable):
        def __init__(self, int: int, double: float, double2: float, double3: float, boolean: bool, double4: float, double5: float, double6: float): ...
        def getEnvelopeHighHz(self) -> float: ...
        def getEnvelopeLowHz(self) -> float: ...
        def getFrequencyHz(self) -> float: ...
        def getModeIndex(self) -> int: ...
        def getResonanceVelocityHighMPerS(self) -> float: ...
        def getResonanceVelocityLowMPerS(self) -> float: ...
        def getResonanceVelocityMPerS(self) -> float: ...
        def isLockedIn(self) -> bool: ...

class FlowInducedPulsationScreening(java.io.Serializable):
    DEFAULT_STROUHAL_MODE_A: typing.ClassVar[float] = ...
    DEFAULT_STROUHAL_MODE_C: typing.ClassVar[float] = ...
    LOCK_IN_ENVELOPE_FRACTION: typing.ClassVar[float] = ...
    REFERENCE_RHO_V2: typing.ClassVar[float] = ...
    DEFAULT_MODE_COUNT: typing.ClassVar[int] = ...
    NEGLIGIBLE_SEVERITY: typing.ClassVar[float] = ...
    @staticmethod
    def bandFor(boolean: bool, double: float) -> 'PipingFivLikelihood': ...
    @staticmethod
    def effectiveWidth(double: float, double2: float) -> float: ...
    @staticmethod
    def eigenFrequency(int: int, double: float, double2: float, acousticTermination: 'FlowInducedPulsationScreening.AcousticTermination') -> float: ...
    @staticmethod
    def recommendation(pipingFivLikelihood: 'PipingFivLikelihood', boolean: bool) -> java.lang.String: ...
    @typing.overload
    @staticmethod
    def screen(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float) -> FlowInducedPulsationResult: ...
    @typing.overload
    @staticmethod
    def screen(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, acousticTermination: 'FlowInducedPulsationScreening.AcousticTermination', double8: float, int: int) -> FlowInducedPulsationResult: ...
    class AcousticTermination(java.lang.Enum['FlowInducedPulsationScreening.AcousticTermination']):
        CLOSED: typing.ClassVar['FlowInducedPulsationScreening.AcousticTermination'] = ...
        OPEN: typing.ClassVar['FlowInducedPulsationScreening.AcousticTermination'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'FlowInducedPulsationScreening.AcousticTermination': ...
        @staticmethod
        def values() -> typing.MutableSequence['FlowInducedPulsationScreening.AcousticTermination']: ...

class PipingFivLikelihood(java.lang.Enum['PipingFivLikelihood']):
    LOW: typing.ClassVar['PipingFivLikelihood'] = ...
    MEDIUM: typing.ClassVar['PipingFivLikelihood'] = ...
    HIGH: typing.ClassVar['PipingFivLikelihood'] = ...
    VERY_HIGH: typing.ClassVar['PipingFivLikelihood'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'PipingFivLikelihood': ...
    @staticmethod
    def values() -> typing.MutableSequence['PipingFivLikelihood']: ...

class PipingFivScreening(java.io.Serializable):
    REFERENCE_GAS_RHO_V2: typing.ClassVar[float] = ...
    REFERENCE_LIQUID_VELOCITY: typing.ClassVar[float] = ...
    @staticmethod
    def bandFor(double: float) -> PipingFivLikelihood: ...
    @staticmethod
    def recommendation(pipingFivLikelihood: PipingFivLikelihood) -> java.lang.String: ...
    @staticmethod
    def screenGas(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, int: int, double5: float, double6: float) -> FivLikelihoodResult: ...
    @staticmethod
    def screenLiquid(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, int: int, double4: float) -> FivLikelihoodResult: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.safety.vibration")``.

    AcousticInducedVibrationResult: typing.Type[AcousticInducedVibrationResult]
    AcousticInducedVibrationScreening: typing.Type[AcousticInducedVibrationScreening]
    FivLikelihoodResult: typing.Type[FivLikelihoodResult]
    FlowInducedPulsationResult: typing.Type[FlowInducedPulsationResult]
    FlowInducedPulsationScreening: typing.Type[FlowInducedPulsationScreening]
    PipingFivLikelihood: typing.Type[PipingFivLikelihood]
    PipingFivScreening: typing.Type[PipingFivScreening]
