
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.calculation
import jneqsim.process.engineering.design.modules
import jneqsim.process.engineering.designcase
import jneqsim.process.processmodel
import typing



class DesignCandidate(java.io.Serializable, java.lang.Comparable['DesignCandidate']):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]): ...
    def compareTo(self, designCandidate: 'DesignCandidate') -> int: ...
    def getId(self) -> java.lang.String: ...
    def getUnit(self) -> java.lang.String: ...
    def getValue(self) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringConstraintResult(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], boolean: bool, double: float, double2: float, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def isSatisfied(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringConvergenceReport(java.io.Serializable):
    def areCaseRunsSuccessful(self) -> bool: ...
    def areDesignVariablesStable(self) -> bool: ...
    def areProcessValuesStable(self) -> bool: ...
    def getConstraintCount(self) -> int: ...
    def getMaximumDesignVariableRelativeChange(self) -> float: ...
    def getMaximumProcessValueRelativeChange(self) -> float: ...
    def getProcessValueTolerance(self) -> float: ...
    def getSatisfiedConstraintCount(self) -> int: ...
    def isConverged(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignConflictException(java.lang.IllegalStateException):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def getDesignVariableKey(self) -> java.lang.String: ...

class EngineeringDesignConstraint(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, string4: typing.Union[java.lang.String, str], comparison: 'EngineeringDesignConstraint.Comparison'): ...
    def evaluate(self, engineeringDesignState: 'EngineeringDesignState') -> EngineeringConstraintResult: ...
    class Comparison(java.lang.Enum['EngineeringDesignConstraint.Comparison']):
        MAXIMUM: typing.ClassVar['EngineeringDesignConstraint.Comparison'] = ...
        MINIMUM: typing.ClassVar['EngineeringDesignConstraint.Comparison'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignConstraint.Comparison': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringDesignConstraint.Comparison']: ...

class EngineeringDesignDependencyException(java.lang.IllegalArgumentException):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...

class EngineeringDesignDependencyGraph(java.io.Serializable):
    def getDependenciesById(self) -> java.util.Map[java.lang.String, java.util.List[java.lang.String]]: ...
    def getModule(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignModule': ...
    def getOrderedModuleIds(self) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def of(list: java.util.List['EngineeringDesignModule']) -> 'EngineeringDesignDependencyGraph': ...

class EngineeringDesignIteration(java.io.Serializable):
    def areAllConstraintsSatisfied(self) -> bool: ...
    def getAppliedUpdateCount(self) -> int: ...
    def getCaseReport(self) -> jneqsim.process.engineering.designcase.EngineeringCaseRunReport: ...
    def getConstraintResults(self) -> java.util.List[EngineeringConstraintResult]: ...
    def getConvergenceReport(self) -> EngineeringConvergenceReport: ...
    def getDesignVariables(self) -> java.util.List['EngineeringDesignVariable']: ...
    def getMaximumRelativeChange(self) -> float: ...
    def getModuleResults(self) -> java.util.List['EngineeringDesignModuleResult']: ...
    def getNumber(self) -> int: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignLoop:
    @staticmethod
    def run(processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseSet: jneqsim.process.engineering.designcase.EngineeringCaseSet, list: java.util.List['EngineeringDesignModule'], engineeringDesignLoopOptions: 'EngineeringDesignLoopOptions') -> 'EngineeringDesignLoopResult': ...

class EngineeringDesignLoopOptions(java.io.Serializable):
    @staticmethod
    def builder() -> 'EngineeringDesignLoopOptions.Builder': ...
    def getCaseParallelism(self) -> int: ...
    def getCaseRunOptions(self) -> jneqsim.process.engineering.designcase.EngineeringCaseRunOptions: ...
    def getMaximumIterations(self) -> int: ...
    def getProcessValueRelativeTolerance(self) -> float: ...
    def isAcceptedCaseEnvelopeRequired(self) -> bool: ...
    def isAllConstraintsRequired(self) -> bool: ...
    def isCompleteCaseEnvelopeRequired(self) -> bool: ...
    def isDiscreteOscillationDetectionEnabled(self) -> bool: ...
    def isStableProcessValuesRequired(self) -> bool: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EngineeringDesignLoopOptions': ...
        def caseParallelism(self, int: int) -> 'EngineeringDesignLoopOptions.Builder': ...
        def caseRunOptions(self, engineeringCaseRunOptions: jneqsim.process.engineering.designcase.EngineeringCaseRunOptions) -> 'EngineeringDesignLoopOptions.Builder': ...
        def detectDiscreteOscillation(self, boolean: bool) -> 'EngineeringDesignLoopOptions.Builder': ...
        def maximumIterations(self, int: int) -> 'EngineeringDesignLoopOptions.Builder': ...
        def processValueRelativeTolerance(self, double: float) -> 'EngineeringDesignLoopOptions.Builder': ...
        def requireAcceptedCaseEnvelope(self, boolean: bool) -> 'EngineeringDesignLoopOptions.Builder': ...
        def requireAllConstraints(self, boolean: bool) -> 'EngineeringDesignLoopOptions.Builder': ...
        def requireCompleteCaseEnvelope(self, boolean: bool) -> 'EngineeringDesignLoopOptions.Builder': ...
        def requireStableProcessValues(self, boolean: bool) -> 'EngineeringDesignLoopOptions.Builder': ...

class EngineeringDesignLoopResult(java.io.Serializable):
    def getDesignedProcess(self) -> jneqsim.process.processmodel.ProcessSystem: ...
    def getIterations(self) -> java.util.List[EngineeringDesignIteration]: ...
    def getState(self) -> 'EngineeringDesignState': ...
    def getTerminationReason(self) -> java.lang.String: ...
    def isConverged(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignModule(java.io.Serializable):
    def evaluate(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringCaseRunReport: jneqsim.process.engineering.designcase.EngineeringCaseRunReport, engineeringDesignState: 'EngineeringDesignState', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> 'EngineeringDesignModuleResult': ...
    def getDependencies(self) -> java.util.List[java.lang.String]: ...
    def getId(self) -> java.lang.String: ...

class EngineeringDesignModuleResult(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'EngineeringDesignModuleResult.Builder': ...
    def getConstraints(self) -> java.util.List[EngineeringDesignConstraint]: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    def getModuleId(self) -> java.lang.String: ...
    def getUpdates(self) -> java.util.List['EngineeringDesignUpdate']: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def addConstraint(self, engineeringDesignConstraint: EngineeringDesignConstraint) -> 'EngineeringDesignModuleResult.Builder': ...
        def addUpdate(self, engineeringDesignUpdate: 'EngineeringDesignUpdate') -> 'EngineeringDesignModuleResult.Builder': ...
        def build(self) -> 'EngineeringDesignModuleResult': ...
        def evidence(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'EngineeringDesignModuleResult.Builder': ...
        def warning(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignModuleResult.Builder': ...

class EngineeringDesignState(java.io.Serializable):
    def __init__(self): ...
    def contains(self, string: typing.Union[java.lang.String, str]) -> bool: ...
    def get(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignValue': ...
    def getValues(self) -> java.util.Map[java.lang.String, 'EngineeringDesignValue']: ...
    def requireValue(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignUpdate(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> 'EngineeringDesignUpdate.Builder': ...
    def getCandidates(self) -> typing.MutableSequence[DesignCandidate]: ...
    def getConflictResolution(self) -> 'EngineeringDesignUpdate.ConflictResolution': ...
    def getGoverningCaseId(self) -> java.lang.String: ...
    def getKey(self) -> java.lang.String: ...
    def getRelativeTolerance(self) -> float: ...
    def getRequiredValue(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def selectedValue(self) -> float: ...
    class Applier(java.io.Serializable):
        def apply(self, processSystem: jneqsim.process.processmodel.ProcessSystem, double: float) -> None: ...
    class Builder:
        def applier(self, applier: typing.Union['EngineeringDesignUpdate.Applier', typing.Callable]) -> 'EngineeringDesignUpdate.Builder': ...
        def build(self) -> 'EngineeringDesignUpdate': ...
        @typing.overload
        def candidates(self, *double: float) -> 'EngineeringDesignUpdate.Builder': ...
        @typing.overload
        def candidates(self, *designCandidate: DesignCandidate) -> 'EngineeringDesignUpdate.Builder': ...
        def conflictResolution(self, conflictResolution: 'EngineeringDesignUpdate.ConflictResolution') -> 'EngineeringDesignUpdate.Builder': ...
        def governingCaseId(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignUpdate.Builder': ...
        def relativeTolerance(self, double: float) -> 'EngineeringDesignUpdate.Builder': ...
    class ConflictResolution(java.lang.Enum['EngineeringDesignUpdate.ConflictResolution']):
        REQUIRE_UNIQUE: typing.ClassVar['EngineeringDesignUpdate.ConflictResolution'] = ...
        GOVERNING_MAXIMUM: typing.ClassVar['EngineeringDesignUpdate.ConflictResolution'] = ...
        GOVERNING_MINIMUM: typing.ClassVar['EngineeringDesignUpdate.ConflictResolution'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringDesignUpdate.ConflictResolution': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringDesignUpdate.ConflictResolution']: ...

class EngineeringDesignValue(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], int: int): ...
    def getGoverningCaseId(self) -> java.lang.String: ...
    def getIteration(self) -> int: ...
    def getKey(self) -> java.lang.String: ...
    def getSourceModule(self) -> java.lang.String: ...
    def getUnit(self) -> java.lang.String: ...
    def getValue(self) -> float: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDesignVariable(java.io.Serializable):
    def getGoverningCaseId(self) -> java.lang.String: ...
    def getKey(self) -> java.lang.String: ...
    def getPreviousValue(self) -> float: ...
    def getRelativeChange(self) -> float: ...
    def getRequiredValue(self) -> float: ...
    def getSelectedCandidateId(self) -> java.lang.String: ...
    def getSelectedValue(self) -> float: ...
    def getUnit(self) -> java.lang.String: ...
    def isApplied(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.design")``.

    DesignCandidate: typing.Type[DesignCandidate]
    EngineeringConstraintResult: typing.Type[EngineeringConstraintResult]
    EngineeringConvergenceReport: typing.Type[EngineeringConvergenceReport]
    EngineeringDesignConflictException: typing.Type[EngineeringDesignConflictException]
    EngineeringDesignConstraint: typing.Type[EngineeringDesignConstraint]
    EngineeringDesignDependencyException: typing.Type[EngineeringDesignDependencyException]
    EngineeringDesignDependencyGraph: typing.Type[EngineeringDesignDependencyGraph]
    EngineeringDesignIteration: typing.Type[EngineeringDesignIteration]
    EngineeringDesignLoop: typing.Type[EngineeringDesignLoop]
    EngineeringDesignLoopOptions: typing.Type[EngineeringDesignLoopOptions]
    EngineeringDesignLoopResult: typing.Type[EngineeringDesignLoopResult]
    EngineeringDesignModule: typing.Type[EngineeringDesignModule]
    EngineeringDesignModuleResult: typing.Type[EngineeringDesignModuleResult]
    EngineeringDesignState: typing.Type[EngineeringDesignState]
    EngineeringDesignUpdate: typing.Type[EngineeringDesignUpdate]
    EngineeringDesignValue: typing.Type[EngineeringDesignValue]
    EngineeringDesignVariable: typing.Type[EngineeringDesignVariable]
    modules: jneqsim.process.engineering.design.modules.__module_protocol__
