
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype
import jpype.protocol
import jneqsim.process.engineering
import jneqsim.process.engineering.calculation
import jneqsim.process.engineering.design.modules
import jneqsim.process.engineering.designcase
import jneqsim.process.engineering.instrumentation
import jneqsim.process.engineering.mechanical
import jneqsim.process.engineering.model
import jneqsim.process.engineering.numerics
import jneqsim.process.engineering.piping
import jneqsim.process.engineering.rotating
import jneqsim.process.engineering.safety
import jneqsim.process.processmodel
import typing



class DexpiToolQualificationEvidence(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], boolean: bool, boolean2: bool, int: int, string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]): ...
    def isQualified(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class DexpiToolQualificationRunner:
    @staticmethod
    def compare(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], snapshot: 'DexpiToolQualificationRunner.Snapshot', snapshot2: 'DexpiToolQualificationRunner.Snapshot', snapshot3: 'DexpiToolQualificationRunner.Snapshot', string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'DexpiToolQualificationRunner.Result': ...
    class Result(java.io.Serializable):
        def getEvidence(self) -> DexpiToolQualificationEvidence: ...
        def getSemanticDifferences(self) -> java.util.List[java.lang.String]: ...
        def isQualified(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Snapshot(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str]): ...
        def addConnection(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'DexpiToolQualificationRunner.Snapshot': ...
        def addObject(self, string: typing.Union[java.lang.String, str], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> 'DexpiToolQualificationRunner.Snapshot': ...

class EngineeringAutoConfigurationPolicy(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addCompressorOperatingEnvelope(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addControlValve(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addHeatExchanger(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, *double4: float) -> 'EngineeringAutoConfigurationPolicy': ...
    @typing.overload
    def addInletCompressionExportSlice(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str]) -> 'EngineeringAutoConfigurationPolicy': ...
    @typing.overload
    def addInletCompressionExportSlice(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float, double6: float, *double7: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addInventory(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addPipingNetwork(self, string: typing.Union[java.lang.String, str], pipingRulePack: jneqsim.process.engineering.piping.PipingRulePack, *segmentDefinition: jneqsim.process.engineering.design.modules.PipingNetworkDesignModule.SegmentDefinition) -> 'EngineeringAutoConfigurationPolicy': ...
    def addPump(self, string: typing.Union[java.lang.String, str], double: float, double2: float, *double3: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addRatedCapacity(self, string: typing.Union[java.lang.String, str], engineeringMetric: jneqsim.process.engineering.designcase.EngineeringMetric, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], double: float, *double2: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def addReliefDevice(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], engineeringMetric: jneqsim.process.engineering.designcase.EngineeringMetric, *double: float) -> 'EngineeringAutoConfigurationPolicy': ...
    def getId(self) -> java.lang.String: ...
    def getPolicyFingerprint(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...

class EngineeringAutoConfigurator:
    @staticmethod
    def configure(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringAutoConfigurationPolicy: EngineeringAutoConfigurationPolicy) -> 'EngineeringAutoConfigurator.Result': ...
    class Result(java.io.Serializable):
        def compareWith(self, result: 'EngineeringAutoConfigurator.Result') -> 'EngineeringAutoConfigurator.RevisionImpact': ...
        def getConfigurationFingerprint(self) -> java.lang.String: ...
        def getConfiguredTags(self) -> java.util.Set[java.lang.String]: ...
        def getEquipmentInventory(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
        def getExecutionBlockers(self) -> java.util.List[java.lang.String]: ...
        def getModuleDependencies(self) -> java.util.Map[java.lang.String, java.util.List[java.lang.String]]: ...
        def getUnconfiguredRecognizedTags(self) -> java.util.List[java.lang.String]: ...
        def isComplete(self) -> bool: ...
        def isExecutionReady(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class RevisionImpact(java.io.Serializable):
        def getInvalidatedArtifacts(self) -> java.util.List[java.lang.String]: ...
        def getInvalidatedModules(self) -> java.util.List[java.lang.String]: ...
        def getStatus(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringBenchmarkDataset(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def add(self, case: 'EngineeringBenchmarkDataset.Case') -> 'EngineeringBenchmarkDataset': ...
    def run(self, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]]]) -> 'EngineeringBenchmarkDataset.RunResult': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Case(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], sourceClass: 'EngineeringValidationBenchmark.SourceClass', string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str]): ...
        def expect(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], double2: float, double3: float) -> 'EngineeringBenchmarkDataset.Case': ...
        def getId(self) -> java.lang.String: ...
        def getMethodKey(self) -> java.lang.String: ...
    class ExpectedValue(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str], double2: float, double3: float): ...
    class RunResult(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def getReport(self) -> 'EngineeringBenchmarkSuite.Report': ...
        def isComplete(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringBenchmarkSuite(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def add(self, engineeringValidationBenchmark: 'EngineeringValidationBenchmark') -> 'EngineeringBenchmarkSuite': ...
    def evaluate(self) -> 'EngineeringBenchmarkSuite.Report': ...
    def requireMethod(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringBenchmarkSuite': ...
    class Report(java.io.Serializable):
        def areAllBenchmarksPassed(self) -> bool: ...
        def getBenchmarks(self) -> java.util.List['EngineeringValidationBenchmark']: ...
        def getFailedBenchmarkIds(self) -> java.util.List[java.lang.String]: ...
        def getMissingQualifyingMethods(self) -> java.util.Set[java.lang.String]: ...
        def getQualifyingMethods(self) -> java.util.Set[java.lang.String]: ...
        def getRequiredMethods(self) -> java.util.Set[java.lang.String]: ...
        def isPassed(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringExternalEvidenceAssessment:
    @staticmethod
    def assess(engineeringExternalEvidenceRegister: 'EngineeringExternalEvidenceRegister') -> 'EngineeringExternalEvidenceAssessment.Result': ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
        def isPassed(self) -> bool: ...
        def isTypePassed(self, type: 'EngineeringExternalEvidenceRecord.Type') -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringExternalEvidenceDocumentIntegrity(java.io.Serializable):
    def __init__(self): ...
    @typing.overload
    def addDocument(self, string: typing.Union[java.lang.String, str], byteArray: typing.Union[typing.List[int], jpype.JArray, bytes]) -> 'EngineeringExternalEvidenceDocumentIntegrity': ...
    @typing.overload
    def addDocument(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceDocumentIntegrity': ...
    @typing.overload
    def assess(self, engineeringExternalEvidenceRegister: 'EngineeringExternalEvidenceRegister') -> 'EngineeringExternalEvidenceDocumentIntegrity.Result': ...
    @typing.overload
    @staticmethod
    def assess(engineeringExternalEvidenceRegister: 'EngineeringExternalEvidenceRegister', engineeringExternalEvidenceDocumentIntegrity: 'EngineeringExternalEvidenceDocumentIntegrity') -> 'EngineeringExternalEvidenceDocumentIntegrity.Result': ...
    def getDocumentReferences(self) -> java.util.List[java.lang.String]: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
        def getVerifiedRecordIds(self) -> java.util.List[java.lang.String]: ...
        def isPassed(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringExternalEvidenceRecord(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], type: 'EngineeringExternalEvidenceRecord.Type', string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
    def getAuthorityJurisdiction(self) -> java.lang.String: ...
    def getDecisionBy(self) -> java.lang.String: ...
    def getDecisionDate(self) -> java.lang.String: ...
    def getDecisionReference(self) -> java.lang.String: ...
    def getDecisionRole(self) -> java.lang.String: ...
    def getDocumentId(self) -> java.lang.String: ...
    def getDocumentReference(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getIndependenceStatement(self) -> java.lang.String: ...
    def getIssuedBy(self) -> java.lang.String: ...
    def getIssuedDate(self) -> java.lang.String: ...
    def getIssuingOrganization(self) -> java.lang.String: ...
    def getMissingFields(self) -> java.util.List[java.lang.String]: ...
    def getRevision(self) -> java.lang.String: ...
    def getScopeReferences(self) -> java.util.List[java.lang.String]: ...
    def getSha256(self) -> java.lang.String: ...
    def getStatus(self) -> 'EngineeringExternalEvidenceRecord.Status': ...
    def getSupersedesRecordId(self) -> java.lang.String: ...
    def getTitle(self) -> java.lang.String: ...
    def getType(self) -> 'EngineeringExternalEvidenceRecord.Type': ...
    def isAcceptedAndComplete(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def addScopeReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def authorityJurisdiction(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def build(self) -> 'EngineeringExternalEvidenceRecord': ...
        def controlledDocument(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def decision(self, status: 'EngineeringExternalEvidenceRecord.Status', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def independenceStatement(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def issuer(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def supersedes(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
        def title(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Builder': ...
    class Status(java.lang.Enum['EngineeringExternalEvidenceRecord.Status']):
        DRAFT: typing.ClassVar['EngineeringExternalEvidenceRecord.Status'] = ...
        ACCEPTED: typing.ClassVar['EngineeringExternalEvidenceRecord.Status'] = ...
        REJECTED: typing.ClassVar['EngineeringExternalEvidenceRecord.Status'] = ...
        SUPERSEDED: typing.ClassVar['EngineeringExternalEvidenceRecord.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringExternalEvidenceRecord.Status']: ...
    class Type(java.lang.Enum['EngineeringExternalEvidenceRecord.Type']):
        ACCOUNTABLE_ENGINEERING_APPROVAL: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        VENDOR_GUARANTEE: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        HAZOP_DECISION: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        LOPA_DECISION: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        SRS_APPROVAL: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        INDEPENDENT_VALIDATION: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        CONSTRUCTION_AUTHORITY: typing.ClassVar['EngineeringExternalEvidenceRecord.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRecord.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringExternalEvidenceRecord.Type']: ...

class EngineeringExternalEvidenceRegister(java.io.Serializable):
    def __init__(self): ...
    def addRecord(self, engineeringExternalEvidenceRecord: EngineeringExternalEvidenceRecord) -> 'EngineeringExternalEvidenceRegister': ...
    def addRequirement(self, engineeringExternalEvidenceRequirement: 'EngineeringExternalEvidenceRequirement') -> 'EngineeringExternalEvidenceRegister': ...
    def getRecords(self) -> java.util.List[EngineeringExternalEvidenceRecord]: ...
    def getRequirements(self) -> java.util.List['EngineeringExternalEvidenceRequirement']: ...
    @staticmethod
    def productionMinimum(string: typing.Union[java.lang.String, str]) -> 'EngineeringExternalEvidenceRegister': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringExternalEvidenceRequirement(java.io.Serializable):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], type: EngineeringExternalEvidenceRecord.Type, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], type: EngineeringExternalEvidenceRecord.Type, string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getDescription(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getRequiredDecisionRole(self) -> java.lang.String: ...
    def getScopeReference(self) -> java.lang.String: ...
    def getType(self) -> EngineeringExternalEvidenceRecord.Type: ...
    def isSatisfiedBy(self, engineeringExternalEvidenceRecord: EngineeringExternalEvidenceRecord) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringMethodApplicabilityEnvelope(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def allowedValues(self, string: typing.Union[java.lang.String, str], *string2: typing.Union[java.lang.String, str]) -> 'EngineeringMethodApplicabilityEnvelope': ...
    def assess(self, engineeringMethodServiceContext: 'EngineeringMethodServiceContext') -> 'EngineeringMethodApplicabilityEnvelope.Assessment': ...
    def isComplete(self) -> bool: ...
    def knownLimitation(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodApplicabilityEnvelope': ...
    def numericRange(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float) -> 'EngineeringMethodApplicabilityEnvelope': ...
    def prohibitExtrapolation(self, boolean: bool) -> 'EngineeringMethodApplicabilityEnvelope': ...
    def requireInput(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodApplicabilityEnvelope': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def uncertaintyBasis(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodApplicabilityEnvelope': ...
    class Assessment(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def isContextComplete(self) -> bool: ...
        def isExecutionPermitted(self) -> bool: ...
        def isWithinEnvelope(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class NumericRange(java.io.Serializable): ...

class EngineeringMethodQualification(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], level: 'EngineeringMethodQualification.Level'): ...
    def addAcceptanceCriterion(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float) -> 'EngineeringMethodQualification': ...
    def addApplicabilityLimit(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification': ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification': ...
    def addStandardReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification': ...
    def applicabilityEnvelope(self, engineeringMethodApplicabilityEnvelope: EngineeringMethodApplicabilityEnvelope) -> 'EngineeringMethodQualification': ...
    def approve(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification': ...
    def getApplicabilityEnvelope(self) -> EngineeringMethodApplicabilityEnvelope: ...
    def getMethodId(self) -> java.lang.String: ...
    def getMethodKey(self) -> java.lang.String: ...
    def getQualifiedUses(self) -> java.util.Set['EngineeringMethodQualification.IntendedUse']: ...
    def isIndustrialQualificationComplete(self) -> bool: ...
    def isProjectQualified(self) -> bool: ...
    def qualifyFor(self, intendedUse: 'EngineeringMethodQualification.IntendedUse') -> 'EngineeringMethodQualification': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class AcceptanceCriterion(java.io.Serializable): ...
    class IntendedUse(java.lang.Enum['EngineeringMethodQualification.IntendedUse']):
        SCREENING: typing.ClassVar['EngineeringMethodQualification.IntendedUse'] = ...
        CONCEPT_SELECTION: typing.ClassVar['EngineeringMethodQualification.IntendedUse'] = ...
        PRELIMINARY_ENGINEERING: typing.ClassVar['EngineeringMethodQualification.IntendedUse'] = ...
        FEED_SUPPORT: typing.ClassVar['EngineeringMethodQualification.IntendedUse'] = ...
        OPERATIONS_ADVISORY: typing.ClassVar['EngineeringMethodQualification.IntendedUse'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification.IntendedUse': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringMethodQualification.IntendedUse']: ...
    class Level(java.lang.Enum['EngineeringMethodQualification.Level']):
        SCREENING: typing.ClassVar['EngineeringMethodQualification.Level'] = ...
        BENCHMARKED: typing.ClassVar['EngineeringMethodQualification.Level'] = ...
        INDEPENDENTLY_VERIFIED: typing.ClassVar['EngineeringMethodQualification.Level'] = ...
        PROJECT_QUALIFIED: typing.ClassVar['EngineeringMethodQualification.Level'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualification.Level': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringMethodQualification.Level']: ...

class EngineeringMethodQualificationRegistry(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def assess(self, string: typing.Union[java.lang.String, str], engineeringMethodServiceContext: 'EngineeringMethodServiceContext', report: EngineeringBenchmarkSuite.Report) -> 'EngineeringMethodQualificationRegistry.Result': ...
    def register(self, engineeringMethodQualification: EngineeringMethodQualification) -> 'EngineeringMethodQualificationRegistry': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def getMethodKey(self) -> java.lang.String: ...
        def getStatus(self) -> 'EngineeringMethodQualificationRegistry.Status': ...
        def isExecutionPermitted(self) -> bool: ...
        def isQualifiedForService(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Status(java.lang.Enum['EngineeringMethodQualificationRegistry.Status']):
        QUALIFIED_FOR_SERVICE: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        UNREGISTERED_METHOD: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        INCOMPLETE_QUALIFICATION: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        MISSING_INDEPENDENT_BENCHMARK: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        USE_NOT_QUALIFIED: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        INSUFFICIENT_SERVICE_CONTEXT: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        OUTSIDE_QUALIFIED_ENVELOPE: typing.ClassVar['EngineeringMethodQualificationRegistry.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodQualificationRegistry.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringMethodQualificationRegistry.Status']: ...

class EngineeringMethodServiceContext(java.io.Serializable):
    def __init__(self, intendedUse: EngineeringMethodQualification.IntendedUse): ...
    def categoricalValue(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringMethodServiceContext': ...
    def getCategoricalValues(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    def getIntendedUse(self) -> EngineeringMethodQualification.IntendedUse: ...
    def getNumericValues(self) -> java.util.Map[java.lang.String, 'EngineeringMethodServiceContext.Quantity']: ...
    def getSuppliedInputs(self) -> java.util.Set[java.lang.String]: ...
    def numericValue(self, string: typing.Union[java.lang.String, str], double: float, string2: typing.Union[java.lang.String, str]) -> 'EngineeringMethodServiceContext': ...
    def suppliedInput(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringMethodServiceContext': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Quantity(java.io.Serializable):
        def getUnit(self) -> java.lang.String: ...
        def getValue(self) -> float: ...

class EngineeringPilotProjectEvidence(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], scope: 'EngineeringPilotProjectEvidence.Scope', string2: typing.Union[java.lang.String, str], int: int, int2: int, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
    def getScope(self) -> 'EngineeringPilotProjectEvidence.Scope': ...
    def isAccepted(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Scope(java.lang.Enum['EngineeringPilotProjectEvidence.Scope']):
        SEPARATION_AND_COMPRESSION: typing.ClassVar['EngineeringPilotProjectEvidence.Scope'] = ...
        PUMPING_AND_HEAT_EXCHANGE: typing.ClassVar['EngineeringPilotProjectEvidence.Scope'] = ...
        RELIEF_BLOWDOWN_AND_FLARE: typing.ClassVar['EngineeringPilotProjectEvidence.Scope'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringPilotProjectEvidence.Scope': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringPilotProjectEvidence.Scope']: ...

class EngineeringPilotQualificationRunner:
    @staticmethod
    def run(string: typing.Union[java.lang.String, str], scope: EngineeringPilotProjectEvidence.Scope, string2: typing.Union[java.lang.String, str], list: java.util.List['EngineeringPilotQualificationRunner.Comparison'], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]) -> 'EngineeringPilotQualificationRunner.Result': ...
    class Comparison(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, string2: typing.Union[java.lang.String, str], double3: float, double4: float, boolean: bool): ...
        def isPassed(self) -> bool: ...
    class Result(java.io.Serializable):
        def getComparisons(self) -> java.util.List['EngineeringPilotQualificationRunner.Comparison']: ...
        def getEvidence(self) -> EngineeringPilotProjectEvidence: ...
        def isAccepted(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringProductionReadinessAssessment:
    @staticmethod
    def assess(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringProductionReadinessBasis: 'EngineeringProductionReadinessBasis') -> 'EngineeringProductionReadinessAssessment.Result': ...
    @staticmethod
    def executedMethods(engineeringProject: jneqsim.process.engineering.EngineeringProject) -> java.util.Set[java.lang.String]: ...
    class Level(java.lang.Enum['EngineeringProductionReadinessAssessment.Level']):
        NOT_READY: typing.ClassVar['EngineeringProductionReadinessAssessment.Level'] = ...
        EXPERIMENTAL: typing.ClassVar['EngineeringProductionReadinessAssessment.Level'] = ...
        VALIDATED_PRELIMINARY: typing.ClassVar['EngineeringProductionReadinessAssessment.Level'] = ...
        QUALIFIED_FEED_SUPPORT: typing.ClassVar['EngineeringProductionReadinessAssessment.Level'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringProductionReadinessAssessment.Level': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringProductionReadinessAssessment.Level']: ...
    class Result(java.io.Serializable):
        def getFailedGates(self) -> java.util.List[java.lang.String]: ...
        def getLevel(self) -> 'EngineeringProductionReadinessAssessment.Level': ...
        def isPreliminaryProductionReady(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringProductionReadinessBasis(java.io.Serializable):
    def __init__(self): ...
    def addDexpiEvidence(self, dexpiToolQualificationEvidence: DexpiToolQualificationEvidence) -> 'EngineeringProductionReadinessBasis': ...
    def addMethodQualification(self, engineeringMethodQualification: EngineeringMethodQualification) -> 'EngineeringProductionReadinessBasis': ...
    def addMethodServiceAssessment(self, result: EngineeringMethodQualificationRegistry.Result) -> 'EngineeringProductionReadinessBasis': ...
    def addNumericalHealthReport(self, engineeringNumericalHealthReport: jneqsim.process.engineering.numerics.EngineeringNumericalHealthReport) -> 'EngineeringProductionReadinessBasis': ...
    def addPilotEvidence(self, engineeringPilotProjectEvidence: EngineeringPilotProjectEvidence) -> 'EngineeringProductionReadinessBasis': ...
    def autoConfigurationResult(self, result: EngineeringAutoConfigurator.Result) -> 'EngineeringProductionReadinessBasis': ...
    def benchmarkReport(self, report: EngineeringBenchmarkSuite.Report) -> 'EngineeringProductionReadinessBasis': ...
    def compressorProtectionQualification(self, engineeringCalculationResult: jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.rotating.CompressorProtectionQualificationCalculation.Result]) -> 'EngineeringProductionReadinessBasis': ...
    def externalEvidenceDocumentIntegrity(self, engineeringExternalEvidenceDocumentIntegrity: EngineeringExternalEvidenceDocumentIntegrity) -> 'EngineeringProductionReadinessBasis': ...
    def externalEvidenceRegister(self, engineeringExternalEvidenceRegister: EngineeringExternalEvidenceRegister) -> 'EngineeringProductionReadinessBasis': ...
    def flareConsequenceQualification(self, engineeringCalculationResult: jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.safety.FlareConsequenceCalculation.Result]) -> 'EngineeringProductionReadinessBasis': ...
    def getAutoConfigurationResult(self) -> EngineeringAutoConfigurator.Result: ...
    def getBenchmarkReport(self) -> EngineeringBenchmarkSuite.Report: ...
    def getCompressorProtectionQualification(self) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.rotating.CompressorProtectionQualificationCalculation.Result]: ...
    def getDexpiEvidence(self) -> java.util.List[DexpiToolQualificationEvidence]: ...
    def getExternalEvidenceDocumentIntegrity(self) -> EngineeringExternalEvidenceDocumentIntegrity: ...
    def getExternalEvidenceRegister(self) -> EngineeringExternalEvidenceRegister: ...
    def getFlareConsequenceQualification(self) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.safety.FlareConsequenceCalculation.Result]: ...
    def getMechanicalIntegrityQualification(self) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.mechanical.MechanicalIntegrityQualificationCalculation.Result]: ...
    def getMethodQualificationRegistry(self) -> EngineeringMethodQualificationRegistry: ...
    def getMethodQualifications(self) -> java.util.List[EngineeringMethodQualification]: ...
    def getMethodServiceAssessments(self) -> java.util.List[EngineeringMethodQualificationRegistry.Result]: ...
    def getNumericalHealthReports(self) -> java.util.List[jneqsim.process.engineering.numerics.EngineeringNumericalHealthReport]: ...
    def getPilotEvidence(self) -> java.util.List[EngineeringPilotProjectEvidence]: ...
    def getReleaseQualityEvidence(self) -> 'EngineeringReleaseQualityEvidence': ...
    def getTechnicalMethodKeys(self) -> java.util.Set[java.lang.String]: ...
    def getTechnicalQualificationCalculations(self, string: typing.Union[java.lang.String, str]) -> java.util.List[jneqsim.process.engineering.model.EngineeringCalculation]: ...
    def getTransientPipingQualification(self) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.piping.TransientPipingQualificationCalculation.Result]: ...
    def getValveInstrumentQualification(self) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.instrumentation.ValveInstrumentQualificationCalculation.Result]: ...
    def mechanicalIntegrityQualification(self, engineeringCalculationResult: jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.mechanical.MechanicalIntegrityQualificationCalculation.Result]) -> 'EngineeringProductionReadinessBasis': ...
    def methodQualificationRegistry(self, engineeringMethodQualificationRegistry: EngineeringMethodQualificationRegistry) -> 'EngineeringProductionReadinessBasis': ...
    def releaseQualityEvidence(self, engineeringReleaseQualityEvidence: 'EngineeringReleaseQualityEvidence') -> 'EngineeringProductionReadinessBasis': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def transientPipingQualification(self, engineeringCalculationResult: jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.piping.TransientPipingQualificationCalculation.Result]) -> 'EngineeringProductionReadinessBasis': ...
    def valveInstrumentQualification(self, engineeringCalculationResult: jneqsim.process.engineering.calculation.EngineeringCalculationResult[jneqsim.process.engineering.instrumentation.ValveInstrumentQualificationCalculation.Result]) -> 'EngineeringProductionReadinessBasis': ...

class EngineeringQualificationPlan:
    @staticmethod
    def build(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringProductionReadinessBasis: EngineeringProductionReadinessBasis) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringReleaseQualificationRunner:
    @staticmethod
    def run(input: 'EngineeringReleaseQualificationRunner.Input') -> 'EngineeringReleaseQualificationRunner.Result': ...
    class Input(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def apiFingerprints(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def deterministicFingerprint(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def fullCiPassed(self, boolean: bool) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def maximumAcceptedSeconds(self, double: float) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def openHighSeveritySecurityFindings(self, int: int) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def passedJavaVersion(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def performanceSample(self, double: float) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def requireJavaVersion(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualificationRunner.Input': ...
        def serializationMigrationPassed(self, boolean: bool) -> 'EngineeringReleaseQualificationRunner.Input': ...
    class Result(java.io.Serializable):
        def getEvidence(self) -> 'EngineeringReleaseQualityEvidence': ...
        def getMeasurements(self) -> java.util.Map[java.lang.String, typing.Any]: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringReleaseQualityEvidence(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    def accountableReviewer(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualityEvidence': ...
    def apiCompatibilityPassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def deterministicConvergencePassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def evidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringReleaseQualityEvidence': ...
    def fullCiPassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def getMissingGates(self) -> java.util.List[java.lang.String]: ...
    def isPassed(self) -> bool: ...
    def performanceAcceptancePassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def securityReviewPassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def serializationMigrationPassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def supportedJavaMatrixPassed(self, boolean: bool) -> 'EngineeringReleaseQualityEvidence': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringSafetyLifecycleAssessment:
    @typing.overload
    @staticmethod
    def assess(engineeringProject: jneqsim.process.engineering.EngineeringProject) -> 'EngineeringSafetyLifecycleAssessment.Result': ...
    @typing.overload
    @staticmethod
    def assess(engineeringProject: jneqsim.process.engineering.EngineeringProject, engineeringExternalEvidenceRegister: EngineeringExternalEvidenceRegister) -> 'EngineeringSafetyLifecycleAssessment.Result': ...
    class Result(java.io.Serializable):
        def isPassed(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringSharedSystemPolicy(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def add(self, definition: 'EngineeringSharedSystemPolicy.Definition') -> 'EngineeringSharedSystemPolicy': ...
    def getDefinitions(self) -> java.util.List['EngineeringSharedSystemPolicy.Definition']: ...
    def getId(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...
    class Definition(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], type: 'EngineeringSharedSystemPolicy.Type', string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
        def addDemand(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float) -> 'EngineeringSharedSystemPolicy.Definition': ...
        def getAreaNames(self) -> java.util.Set[java.lang.String]: ...
        def getDemands(self) -> java.util.List['EngineeringSharedSystemPolicy.Demand']: ...
        def getId(self) -> java.lang.String: ...
        def getType(self) -> 'EngineeringSharedSystemPolicy.Type': ...
    class Demand(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float): ...
        def getAreaName(self) -> java.lang.String: ...
        def getDesignVariable(self) -> java.lang.String: ...
        def getSimultaneityFactor(self) -> float: ...
    class Type(java.lang.Enum['EngineeringSharedSystemPolicy.Type']):
        UTILITY_HEADER: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        FLARE_HEADER: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        BLOWDOWN_GROUP: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        ELECTRICAL_SYSTEM: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        SHARED_EQUIPMENT: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        OTHER: typing.ClassVar['EngineeringSharedSystemPolicy.Type'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringSharedSystemPolicy.Type': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringSharedSystemPolicy.Type']: ...

class EngineeringValidationBenchmark(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'EngineeringValidationBenchmark.Builder': ...
    def getId(self) -> java.lang.String: ...
    def getMethodId(self) -> java.lang.String: ...
    def getMethodKey(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    def getSourceClass(self) -> 'EngineeringValidationBenchmark.SourceClass': ...
    def isIndependentSource(self) -> bool: ...
    def isIndependentlyReviewed(self) -> bool: ...
    def isPassed(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def build(self) -> 'EngineeringValidationBenchmark': ...
        def check(self, string: typing.Union[java.lang.String, str], double: float, double2: float, string2: typing.Union[java.lang.String, str], double3: float, double4: float) -> 'EngineeringValidationBenchmark.Builder': ...
        def independentReview(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringValidationBenchmark.Builder': ...
        def source(self, sourceClass: 'EngineeringValidationBenchmark.SourceClass', string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> 'EngineeringValidationBenchmark.Builder': ...
    class Check(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, string2: typing.Union[java.lang.String, str], double3: float, double4: float): ...
        def getAbsoluteError(self) -> float: ...
        def getRelativeError(self) -> float: ...
        def isPassed(self) -> bool: ...
    class SourceClass(java.lang.Enum['EngineeringValidationBenchmark.SourceClass']):
        REGRESSION_BASELINE: typing.ClassVar['EngineeringValidationBenchmark.SourceClass'] = ...
        PUBLISHED_WORKED_EXAMPLE: typing.ClassVar['EngineeringValidationBenchmark.SourceClass'] = ...
        INDEPENDENT_CALCULATION: typing.ClassVar['EngineeringValidationBenchmark.SourceClass'] = ...
        VENDOR_OR_CAE_REFERENCE: typing.ClassVar['EngineeringValidationBenchmark.SourceClass'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringValidationBenchmark.SourceClass': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringValidationBenchmark.SourceClass']: ...

class ProcessModelEngineeringPackageValidator:
    @staticmethod
    def validate(map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]) -> java.util.List[java.lang.String]: ...
    @staticmethod
    def validateOrThrow(map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Any], typing.Mapping[typing.Union[java.lang.String, str], typing.Any]]) -> None: ...

class ProcessModelEngineeringSimulator:
    @typing.overload
    @staticmethod
    def run(string: typing.Union[java.lang.String, str], processModel: jneqsim.process.processmodel.ProcessModel, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration'], typing.Mapping[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration']], int: int) -> 'ProcessModelEngineeringSimulator.Result': ...
    @typing.overload
    @staticmethod
    def run(string: typing.Union[java.lang.String, str], processModel: jneqsim.process.processmodel.ProcessModel, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration'], typing.Mapping[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration']], engineeringSharedSystemPolicy: EngineeringSharedSystemPolicy, int: int) -> 'ProcessModelEngineeringSimulator.Result': ...
    @staticmethod
    def runIncremental(string: typing.Union[java.lang.String, str], processModel: jneqsim.process.processmodel.ProcessModel, map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration'], typing.Mapping[typing.Union[java.lang.String, str], 'ProcessModelEngineeringSimulator.AreaConfiguration']], engineeringSharedSystemPolicy: EngineeringSharedSystemPolicy, result: 'ProcessModelEngineeringSimulator.Result', int: int) -> 'ProcessModelEngineeringSimulator.Result': ...
    class AreaConfiguration(java.io.Serializable):
        def __init__(self, engineeringAutoConfigurationPolicy: EngineeringAutoConfigurationPolicy): ...
        def addDesignCase(self, engineeringDesignCase: jneqsim.process.engineering.designcase.EngineeringDesignCase) -> 'ProcessModelEngineeringSimulator.AreaConfiguration': ...
        def registerProposedInstruments(self, boolean: bool) -> 'ProcessModelEngineeringSimulator.AreaConfiguration': ...
    class AreaResult:
        def getConfiguration(self) -> EngineeringAutoConfigurator.Result: ...
        def getProject(self) -> jneqsim.process.engineering.EngineeringProject: ...
        def getSimulation(self) -> jneqsim.process.engineering.EngineeringSimulationResult: ...
    class Result:
        def compile(self, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> java.nio.file.Path: ...
        def getAreas(self) -> java.util.Map[java.lang.String, 'ProcessModelEngineeringSimulator.AreaResult']: ...
        def getBlockers(self) -> java.util.List[java.lang.String]: ...
        def getCoordinationFingerprint(self) -> java.lang.String: ...
        def getExecutedAreas(self) -> java.util.Set[java.lang.String]: ...
        def getFingerprint(self) -> java.lang.String: ...
        def getReusedAreas(self) -> java.util.Set[java.lang.String]: ...
        def getSharedStreamDependencies(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
        def getSharedSystemResults(self) -> java.util.List[java.util.Map[java.lang.String, typing.Any]]: ...
        def isComplete(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.production")``.

    DexpiToolQualificationEvidence: typing.Type[DexpiToolQualificationEvidence]
    DexpiToolQualificationRunner: typing.Type[DexpiToolQualificationRunner]
    EngineeringAutoConfigurationPolicy: typing.Type[EngineeringAutoConfigurationPolicy]
    EngineeringAutoConfigurator: typing.Type[EngineeringAutoConfigurator]
    EngineeringBenchmarkDataset: typing.Type[EngineeringBenchmarkDataset]
    EngineeringBenchmarkSuite: typing.Type[EngineeringBenchmarkSuite]
    EngineeringExternalEvidenceAssessment: typing.Type[EngineeringExternalEvidenceAssessment]
    EngineeringExternalEvidenceDocumentIntegrity: typing.Type[EngineeringExternalEvidenceDocumentIntegrity]
    EngineeringExternalEvidenceRecord: typing.Type[EngineeringExternalEvidenceRecord]
    EngineeringExternalEvidenceRegister: typing.Type[EngineeringExternalEvidenceRegister]
    EngineeringExternalEvidenceRequirement: typing.Type[EngineeringExternalEvidenceRequirement]
    EngineeringMethodApplicabilityEnvelope: typing.Type[EngineeringMethodApplicabilityEnvelope]
    EngineeringMethodQualification: typing.Type[EngineeringMethodQualification]
    EngineeringMethodQualificationRegistry: typing.Type[EngineeringMethodQualificationRegistry]
    EngineeringMethodServiceContext: typing.Type[EngineeringMethodServiceContext]
    EngineeringPilotProjectEvidence: typing.Type[EngineeringPilotProjectEvidence]
    EngineeringPilotQualificationRunner: typing.Type[EngineeringPilotQualificationRunner]
    EngineeringProductionReadinessAssessment: typing.Type[EngineeringProductionReadinessAssessment]
    EngineeringProductionReadinessBasis: typing.Type[EngineeringProductionReadinessBasis]
    EngineeringQualificationPlan: typing.Type[EngineeringQualificationPlan]
    EngineeringReleaseQualificationRunner: typing.Type[EngineeringReleaseQualificationRunner]
    EngineeringReleaseQualityEvidence: typing.Type[EngineeringReleaseQualityEvidence]
    EngineeringSafetyLifecycleAssessment: typing.Type[EngineeringSafetyLifecycleAssessment]
    EngineeringSharedSystemPolicy: typing.Type[EngineeringSharedSystemPolicy]
    EngineeringValidationBenchmark: typing.Type[EngineeringValidationBenchmark]
    ProcessModelEngineeringPackageValidator: typing.Type[ProcessModelEngineeringPackageValidator]
    ProcessModelEngineeringSimulator: typing.Type[ProcessModelEngineeringSimulator]
