
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering
import jneqsim.process.engineering.model
import org.w3c.dom
import typing



class DexpiEngineeringExporter:
    @staticmethod
    def export(engineeringProject: jneqsim.process.engineering.EngineeringProject, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'DexpiEngineeringExporter.ExportResult': ...
    @staticmethod
    def refreshPackageManifest(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> java.nio.file.Path: ...
    class ExportResult:
        def getCalculationsFile(self) -> java.nio.file.Path: ...
        def getCauseAndEffectFile(self) -> java.nio.file.Path: ...
        def getCompressorMapFiles(self) -> java.util.Map[java.lang.String, java.nio.file.Path]: ...
        def getDexpi20File(self) -> java.nio.file.Path: ...
        def getDexpiFile(self) -> java.nio.file.Path: ...
        def getInteroperabilityReportFile(self) -> java.nio.file.Path: ...
        def getManifestFile(self) -> java.nio.file.Path: ...
        def getPackageManifestFile(self) -> java.nio.file.Path: ...
        def getPyDexpiFile(self) -> java.nio.file.Path: ...
        def getRegisterFiles(self) -> java.util.Map[java.lang.String, java.nio.file.Path]: ...
        def getValidationFile(self) -> java.nio.file.Path: ...

class DexpiEngineeringMaterializer:
    @staticmethod
    def materialize(engineeringProject: jneqsim.process.engineering.EngineeringProject, document: org.w3c.dom.Document) -> 'DexpiEngineeringMaterializer.MaterializationResult': ...
    class CauseAndEffectEntry:
        def getCause(self) -> java.lang.String: ...
        def getEquipmentTag(self) -> java.lang.String: ...
        def getInitiatingDeviceTag(self) -> java.lang.String: ...
        def getProposedEffects(self) -> java.util.List[java.lang.String]: ...
        def getRequirementId(self) -> java.lang.String: ...
        def getSilTarget(self) -> java.lang.String: ...
        def getStandardReferences(self) -> java.util.List[java.lang.String]: ...
    class MaterializationResult:
        def getCauseAndEffectEntries(self) -> java.util.List['DexpiEngineeringMaterializer.CauseAndEffectEntry']: ...
        def getInstrumentFunctionCount(self) -> int: ...
        def getProtectiveDeviceCount(self) -> int: ...
        def toCauseAndEffectJson(self, engineeringProject: jneqsim.process.engineering.EngineeringProject) -> java.lang.String: ...

class DexpiEngineeringValidator:
    @typing.overload
    @staticmethod
    def validate(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'DexpiEngineeringValidator.ValidationResult': ...
    @typing.overload
    @staticmethod
    def validate(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], path2: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'DexpiEngineeringValidator.ValidationResult': ...
    @staticmethod
    def write(validationResult: 'DexpiEngineeringValidator.ValidationResult', path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> java.nio.file.Path: ...
    class ValidationResult:
        def __init__(self): ...
        def isValid(self) -> bool: ...
        def toJson(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringDexpiRoundTripQualifier:
    @staticmethod
    def qualify(engineeringGraph: jneqsim.process.engineering.model.EngineeringGraph, path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], path2: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], path3: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.dexpi")``.

    DexpiEngineeringExporter: typing.Type[DexpiEngineeringExporter]
    DexpiEngineeringMaterializer: typing.Type[DexpiEngineeringMaterializer]
    DexpiEngineeringValidator: typing.Type[DexpiEngineeringValidator]
    EngineeringDexpiRoundTripQualifier: typing.Type[EngineeringDexpiRoundTripQualifier]
