
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.processmodel
import typing



class EngineeringNumericalHealthAnalyzer:
    def __init__(self, processSystem: jneqsim.process.processmodel.ProcessSystem, engineeringNumericalHealthCriteria: 'EngineeringNumericalHealthCriteria'): ...
    def addEnergyClosure(self, string: typing.Union[java.lang.String, str], double: float, double2: float, string2: typing.Union[java.lang.String, str]) -> 'EngineeringNumericalHealthAnalyzer': ...
    def addEquationResidual(self, string: typing.Union[java.lang.String, str], double: float, double2: float, string2: typing.Union[java.lang.String, str]) -> 'EngineeringNumericalHealthAnalyzer': ...
    @typing.overload
    def analyze(self) -> 'EngineeringNumericalHealthReport': ...
    @typing.overload
    @staticmethod
    def analyze(processSystem: jneqsim.process.processmodel.ProcessSystem) -> 'EngineeringNumericalHealthReport': ...
    def sensitivityJacobian(self, doubleArray: typing.Union[typing.List[typing.MutableSequence[float]], jpype.JArray]) -> 'EngineeringNumericalHealthAnalyzer': ...

class EngineeringNumericalHealthCriteria(java.io.Serializable):
    def areEquationResidualsRequired(self) -> bool: ...
    @staticmethod
    def builder() -> 'EngineeringNumericalHealthCriteria.Builder': ...
    @staticmethod
    def defaults() -> 'EngineeringNumericalHealthCriteria': ...
    def getMassBalanceUnit(self) -> java.lang.String: ...
    def getMaximumEnergyBalanceErrorPercent(self) -> float: ...
    def getMaximumJacobianScaleRatio(self) -> float: ...
    def getMaximumMassBalanceErrorPercent(self) -> float: ...
    def getMaximumNormalizedResidual(self) -> float: ...
    def isEnergyClosureRequired(self) -> bool: ...
    def isSensitivityEvidenceRequired(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def __init__(self): ...
        def build(self) -> 'EngineeringNumericalHealthCriteria': ...
        def massBalanceUnit(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def maximumEnergyBalanceErrorPercent(self, double: float) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def maximumJacobianScaleRatio(self, double: float) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def maximumMassBalanceErrorPercent(self, double: float) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def maximumNormalizedResidual(self, double: float) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def requireEnergyClosure(self, boolean: bool) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def requireEquationResiduals(self, boolean: bool) -> 'EngineeringNumericalHealthCriteria.Builder': ...
        def requireSensitivityEvidence(self, boolean: bool) -> 'EngineeringNumericalHealthCriteria.Builder': ...

class EngineeringNumericalHealthReport(java.io.Serializable):
    def getEnergyClosure(self) -> java.util.List['EngineeringNumericalHealthReport.ClosureObservation']: ...
    def getEquationResiduals(self) -> java.util.List['EngineeringNumericalHealthReport.ResidualObservation']: ...
    def getFindings(self) -> java.util.List[java.lang.String]: ...
    def getJacobianHealth(self) -> 'EngineeringNumericalHealthReport.JacobianHealth': ...
    def getMassClosure(self) -> java.util.List['EngineeringNumericalHealthReport.ClosureObservation']: ...
    def getStatus(self) -> 'EngineeringNumericalHealthReport.Status': ...
    def isAcceptableForEngineering(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class ClosureObservation(java.io.Serializable):
        def getMessage(self) -> java.lang.String: ...
        def getScope(self) -> java.lang.String: ...
        def getStatus(self) -> 'EngineeringNumericalHealthReport.ObservationStatus': ...
        def getType(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class JacobianHealth(java.io.Serializable):
        def getNumericalRank(self) -> int: ...
        def getStatus(self) -> 'EngineeringNumericalHealthReport.ObservationStatus': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class ObservationStatus(java.lang.Enum['EngineeringNumericalHealthReport.ObservationStatus']):
        PASS: typing.ClassVar['EngineeringNumericalHealthReport.ObservationStatus'] = ...
        FAIL: typing.ClassVar['EngineeringNumericalHealthReport.ObservationStatus'] = ...
        NOT_APPLICABLE: typing.ClassVar['EngineeringNumericalHealthReport.ObservationStatus'] = ...
        NOT_AVAILABLE: typing.ClassVar['EngineeringNumericalHealthReport.ObservationStatus'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringNumericalHealthReport.ObservationStatus': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringNumericalHealthReport.ObservationStatus']: ...
    class ResidualObservation(java.io.Serializable):
        def getStatus(self) -> 'EngineeringNumericalHealthReport.ObservationStatus': ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Status(java.lang.Enum['EngineeringNumericalHealthReport.Status']):
        HEALTHY: typing.ClassVar['EngineeringNumericalHealthReport.Status'] = ...
        INCOMPLETE: typing.ClassVar['EngineeringNumericalHealthReport.Status'] = ...
        FAILED: typing.ClassVar['EngineeringNumericalHealthReport.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringNumericalHealthReport.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringNumericalHealthReport.Status']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.numerics")``.

    EngineeringNumericalHealthAnalyzer: typing.Type[EngineeringNumericalHealthAnalyzer]
    EngineeringNumericalHealthCriteria: typing.Type[EngineeringNumericalHealthCriteria]
    EngineeringNumericalHealthReport: typing.Type[EngineeringNumericalHealthReport]
