
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jpype
import jneqsim.process.equipment
import jneqsim.process.equipment.stream
import jneqsim.process.mechanicaldesign
import jneqsim.process.util.report
import jneqsim.util.nucleation
import typing



class Filter(jneqsim.process.equipment.TwoPortEquipment):
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str]): ...
    @typing.overload
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def disableBypass(self) -> None: ...
    def getBackwashRemovalRate(self) -> float: ...
    def getBreakthroughFraction(self) -> float: ...
    def getBreakthroughStartFraction(self) -> float: ...
    def getBypassFraction(self) -> float: ...
    def getCalculatedCapturedRate(self) -> float: ...
    def getCalculatedCleanDeltaP(self) -> float: ...
    def getCleanDeltaP(self) -> float: ...
    def getCurrentRemovalEfficiency(self) -> float: ...
    def getCvFactor(self) -> float: ...
    def getDeltaP(self) -> float: ...
    def getDifferentialPressureUtilization(self) -> float: ...
    def getElementCollapsePressure(self) -> float: ...
    def getFilterServiceType(self) -> 'FilterType': ...
    def getFlowExponent(self) -> float: ...
    def getHoldupResidenceTime(self) -> float: ...
    def getHoldupVolume(self) -> float: ...
    def getInletParticleConcentration(self) -> float: ...
    def getLoadingCapacity(self) -> float: ...
    def getLoadingFraction(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getMediaArea(self) -> float: ...
    def getMediaBedDepth(self) -> float: ...
    def getMediaParticleDiameter(self) -> float: ...
    def getMediaVoidFraction(self) -> float: ...
    def getNominalRemovalEfficiency(self) -> float: ...
    def getNumberOfElements(self) -> int: ...
    def getOutletParticleConcentration(self) -> float: ...
    def getParticleSize(self) -> float: ...
    def getPerformanceCurve(self) -> 'FilterPerformanceCurve': ...
    def getPressureDropCurve(self) -> 'FilterPressureDropCurve': ...
    def getPressureDropIncreaseAtCapacity(self) -> float: ...
    def getPressureDropModel(self) -> 'FilterPressureDropModel': ...
    def getReferenceFlowRate(self) -> float: ...
    def getRegenerationRemovalRate(self) -> float: ...
    def getSolidsLoading(self) -> float: ...
    def getSolidsLoadingRate(self) -> float: ...
    def getTerminalDeltaP(self) -> float: ...
    def getUnrestrictedDeltaP(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isBackwashActive(self) -> bool: ...
    def isBypassEnabled(self) -> bool: ...
    def isElementIntegrityVerified(self) -> bool: ...
    def isRegenerationActive(self) -> bool: ...
    def isReplacementRequired(self) -> bool: ...
    def resetDynamicState(self) -> None: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def runConditionAnalysis(self, processEquipmentInterface: jneqsim.process.equipment.ProcessEquipmentInterface) -> None: ...
    @typing.overload
    def runTransient(self, double: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, uUID: java.util.UUID) -> None: ...
    def setBackwashRemovalRate(self, double: float) -> None: ...
    def setBetaRatio(self, double: float) -> None: ...
    def setBreakthroughStartFraction(self, double: float) -> None: ...
    def setBypassCrackingDeltaP(self, double: float) -> None: ...
    def setCvFactor(self, double: float) -> None: ...
    @typing.overload
    def setDeltaP(self, double: float) -> None: ...
    @typing.overload
    def setDeltaP(self, double: float, string: typing.Union[java.lang.String, str]) -> None: ...
    def setElementCollapsePressure(self, double: float) -> None: ...
    def setElementIntegrityVerified(self, boolean: bool) -> None: ...
    def setFilterServiceType(self, filterType: 'FilterType') -> None: ...
    def setFlowExponent(self, double: float) -> None: ...
    def setHoldupVolume(self, double: float) -> None: ...
    def setInletParticleConcentration(self, double: float) -> None: ...
    def setLoadingCapacity(self, double: float) -> None: ...
    def setMediaGeometry(self, double: float, double2: float, double3: float, double4: float) -> None: ...
    def setNominalRemovalEfficiency(self, double: float) -> None: ...
    def setNumberOfElements(self, int: int) -> None: ...
    def setParticleSize(self, double: float) -> None: ...
    def setPerformanceCurve(self, filterPerformanceCurve: 'FilterPerformanceCurve') -> None: ...
    def setPressureDropCurve(self, filterPressureDropCurve: 'FilterPressureDropCurve') -> None: ...
    def setPressureDropIncreaseAtCapacity(self, double: float) -> None: ...
    def setPressureDropModel(self, filterPressureDropModel: 'FilterPressureDropModel') -> None: ...
    def setReferenceFlowRate(self, double: float) -> None: ...
    def setRegenerationRemovalRate(self, double: float) -> None: ...
    def setSolidsLoading(self, double: float) -> None: ...
    def setSolidsLoadingRate(self, double: float) -> None: ...
    def setTerminalDeltaP(self, double: float) -> None: ...
    def startBackwash(self) -> None: ...
    def startRegeneration(self) -> None: ...
    def stopBackwash(self) -> None: ...
    def stopRegeneration(self) -> None: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...

class FilterPerformanceCurve(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def getBetaRatio(self, double: float) -> float: ...
    def getBetaRatios(self) -> typing.MutableSequence[float]: ...
    def getParticleSizesMicrometre(self) -> typing.MutableSequence[float]: ...
    def getRemovalEfficiency(self, double: float) -> float: ...
    def getTestStandard(self) -> java.lang.String: ...
    def setPoints(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTestStandard(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def size(self) -> int: ...

class FilterPressureDropCurve(java.io.Serializable):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]): ...
    def getFlowRatesM3Hr(self) -> typing.MutableSequence[float]: ...
    def getPressureDrop(self, double: float) -> float: ...
    def getPressureDropsBar(self) -> typing.MutableSequence[float]: ...
    def getTestStandard(self) -> java.lang.String: ...
    def setPoints(self, doubleArray: typing.Union[typing.List[float], jpype.JArray], doubleArray2: typing.Union[typing.List[float], jpype.JArray]) -> None: ...
    def setTestStandard(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def size(self) -> int: ...

class FilterPressureDropModel(java.lang.Enum['FilterPressureDropModel']):
    FIXED: typing.ClassVar['FilterPressureDropModel'] = ...
    FLOW_SCALED: typing.ClassVar['FilterPressureDropModel'] = ...
    TABULATED: typing.ClassVar['FilterPressureDropModel'] = ...
    ERGUN: typing.ClassVar['FilterPressureDropModel'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'FilterPressureDropModel': ...
    @staticmethod
    def values() -> typing.MutableSequence['FilterPressureDropModel']: ...

class FilterType(java.lang.Enum['FilterType']):
    CARTRIDGE: typing.ClassVar['FilterType'] = ...
    BAG: typing.ClassVar['FilterType'] = ...
    Y_STRAINER: typing.ClassVar['FilterType'] = ...
    BASKET_STRAINER: typing.ClassVar['FilterType'] = ...
    COALESCER: typing.ClassVar['FilterType'] = ...
    GRANULAR_MEDIA: typing.ClassVar['FilterType'] = ...
    BACKWASHABLE_MEDIA: typing.ClassVar['FilterType'] = ...
    ACTIVATED_CARBON: typing.ClassVar['FilterType'] = ...
    def getDefaultElementArea(self) -> float: ...
    def getDefaultElementDiameter(self) -> float: ...
    def getDefaultElementLength(self) -> float: ...
    def getDefaultFlowExponent(self) -> float: ...
    def getDefaultMaximumFaceVelocity(self) -> float: ...
    def getDefaultPressureDropModel(self) -> FilterPressureDropModel: ...
    def getDisplayName(self) -> java.lang.String: ...
    def isBackwashSupported(self) -> bool: ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: typing.Union[java.lang.String, str]) -> 'FilterType': ...
    @staticmethod
    def values() -> typing.MutableSequence['FilterType']: ...

class CharCoalFilter(Filter):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...

class SulfurFilter(Filter):
    def __init__(self, string: typing.Union[java.lang.String, str], streamInterface: jneqsim.process.equipment.stream.StreamInterface): ...
    def getChangeIntervalDays(self) -> float: ...
    def getChangeIntervalHours(self) -> float: ...
    def getEstimatedCaptureEfficiency(self) -> float: ...
    def getFilterElementCapacity(self) -> float: ...
    def getFilterType(self) -> java.lang.String: ...
    def getFiltrationRating(self) -> float: ...
    def getGasFlowRate(self) -> float: ...
    def getMeanParticleDiameterMicrons(self) -> float: ...
    def getMechanicalDesign(self) -> jneqsim.process.mechanicaldesign.MechanicalDesign: ...
    def getNominalRemovalEfficiency(self) -> float: ...
    def getNucleationModel(self) -> jneqsim.util.nucleation.ClassicalNucleationTheory: ...
    def getNumberOfElements(self) -> int: ...
    def getParticleSizePercentilesUM(self) -> typing.MutableSequence[float]: ...
    def getRemovalEfficiency(self) -> float: ...
    def getResidenceTime(self) -> float: ...
    def getSolidS8MassFractionInlet(self) -> float: ...
    @typing.overload
    def getSolidSulfurRemovalRate(self) -> float: ...
    @typing.overload
    def getSolidSulfurRemovalRate(self, string: typing.Union[java.lang.String, str]) -> float: ...
    def getSupersaturationRatio(self) -> float: ...
    def initMechanicalDesign(self) -> None: ...
    def isSolidS8Detected(self) -> bool: ...
    @typing.overload
    def run(self) -> None: ...
    @typing.overload
    def run(self, uUID: java.util.UUID) -> None: ...
    def setFilterElementCapacity(self, double: float) -> None: ...
    def setFilterType(self, string: typing.Union[java.lang.String, str]) -> None: ...
    def setFiltrationRating(self, double: float) -> None: ...
    def setNumberOfElements(self, int: int) -> None: ...
    def setRemovalEfficiency(self, double: float) -> None: ...
    def setResidenceTime(self, double: float) -> None: ...
    @typing.overload
    def toJson(self, reportConfig: jneqsim.process.util.report.ReportConfig) -> java.lang.String: ...
    @typing.overload
    def toJson(self) -> java.lang.String: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.equipment.filter")``.

    CharCoalFilter: typing.Type[CharCoalFilter]
    Filter: typing.Type[Filter]
    FilterPerformanceCurve: typing.Type[FilterPerformanceCurve]
    FilterPressureDropCurve: typing.Type[FilterPressureDropCurve]
    FilterPressureDropModel: typing.Type[FilterPressureDropModel]
    FilterType: typing.Type[FilterType]
    SulfurFilter: typing.Type[SulfurFilter]
