
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.fluidmechanics.flowsolver
import jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver
import jneqsim.fluidmechanics.flowsystem.onephaseflowsystem
import typing



class OnePhaseSpeciesConservationHistory(java.io.Serializable):
    @staticmethod
    def empty() -> 'OnePhaseSpeciesConservationHistory': ...
    def getElapsedTimeSeconds(self) -> typing.MutableSequence[float]: ...
    def getReport(self, int: int) -> jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver.OnePhaseSpeciesConservationReport: ...
    def getReports(self) -> typing.MutableSequence[jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver.OnePhaseSpeciesConservationReport]: ...
    def isEmpty(self) -> bool: ...
    def size(self) -> int: ...
    def toJson(self) -> java.lang.String: ...

class PipeFlowSystem(jneqsim.fluidmechanics.flowsystem.onephaseflowsystem.OnePhaseFlowSystem):
    def __init__(self): ...
    def createSystem(self) -> None: ...
    def getAxialDispersionModel(self) -> jneqsim.fluidmechanics.flowsolver.AxialDispersionModel: ...
    def getConvergenceReport(self) -> jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver.OnePhaseFlowConvergenceReport: ...
    def getSpeciesAdvectionScheme(self) -> jneqsim.fluidmechanics.flowsolver.SpeciesAdvectionScheme: ...
    def getSpeciesConservationHistory(self) -> OnePhaseSpeciesConservationHistory: ...
    def getSpeciesConservationReport(self) -> jneqsim.fluidmechanics.flowsolver.onephaseflowsolver.onephasepipeflowsolver.OnePhaseSpeciesConservationReport: ...
    def init(self) -> None: ...
    def isConservativeSpeciesTransportEnabled(self) -> bool: ...
    def isFailOnNonConvergence(self) -> bool: ...
    def isSpeciesConservationHistoryStorageEnabled(self) -> bool: ...
    @typing.overload
    def runTransient(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransient(self, double: float, double2: float, int: int) -> None: ...
    @typing.overload
    def runTransientClosedOutlet(self, double: float, double2: float) -> None: ...
    @typing.overload
    def runTransientClosedOutlet(self, double: float, double2: float, int: int) -> None: ...
    @typing.overload
    def runTransientControlledOutletPressure(self, double: float, double2: float, double3: float) -> None: ...
    @typing.overload
    def runTransientControlledOutletPressure(self, double: float, double2: float, double3: float, int: int) -> None: ...
    @typing.overload
    def runTransientControlledOutletVelocity(self, double: float, double2: float, double3: float) -> None: ...
    @typing.overload
    def runTransientControlledOutletVelocity(self, double: float, double2: float, double3: float, int: int) -> None: ...
    def setAxialDispersionModel(self, axialDispersionModel: jneqsim.fluidmechanics.flowsolver.AxialDispersionModel) -> None: ...
    def setConservativeSpeciesTransport(self, boolean: bool) -> None: ...
    def setFailOnNonConvergence(self, boolean: bool) -> None: ...
    def setOutletClosed(self) -> None: ...
    def setOutletPressure(self, double: float) -> None: ...
    def setOutletVelocity(self, double: float) -> None: ...
    def setSpeciesAdvectionScheme(self, speciesAdvectionScheme: jneqsim.fluidmechanics.flowsolver.SpeciesAdvectionScheme) -> None: ...
    def setStoreSpeciesConservationHistory(self, boolean: bool) -> None: ...
    @typing.overload
    def solveSteadyState(self, int: int) -> None: ...
    @typing.overload
    def solveSteadyState(self, int: int, uUID: java.util.UUID) -> None: ...
    @typing.overload
    def solveTransient(self, int: int) -> None: ...
    @typing.overload
    def solveTransient(self, int: int, uUID: java.util.UUID) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.fluidmechanics.flowsystem.onephaseflowsystem.pipeflowsystem")``.

    OnePhaseSpeciesConservationHistory: typing.Type[OnePhaseSpeciesConservationHistory]
    PipeFlowSystem: typing.Type[PipeFlowSystem]
