
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import jneqsim.process.engineering
import typing



class EngineeringCalculation(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def addInput(self, input: 'EngineeringCalculation.Input') -> 'EngineeringCalculation': ...
    def addStandardReference(self, standardReference: 'EngineeringCalculation.StandardReference') -> 'EngineeringCalculation': ...
    def dependsOnCalculation(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def getDesignCaseId(self) -> java.lang.String: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getId(self) -> java.lang.String: ...
    def getInputs(self) -> java.util.List['EngineeringCalculation.Input']: ...
    def getMessage(self) -> java.lang.String: ...
    def getMethod(self) -> java.lang.String: ...
    def getPrerequisiteCalculationIds(self) -> java.util.List[java.lang.String]: ...
    def getResultUnit(self) -> java.lang.String: ...
    def getResultValue(self) -> float: ...
    def getStandardReference(self) -> java.lang.String: ...
    def getStandardReferences(self) -> java.util.List['EngineeringCalculation.StandardReference']: ...
    def getStatus(self) -> 'EngineeringCalculation.Status': ...
    def getSubjectNodeId(self) -> java.lang.String: ...
    def hasStandardsBasis(self) -> bool: ...
    def isStandardsRequired(self) -> bool: ...
    def setDesignCaseId(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def setMessage(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def setResult(self, double: float, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def setStandardReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation': ...
    def setStandardsRequired(self, boolean: bool) -> 'EngineeringCalculation': ...
    def setStatus(self, status: 'EngineeringCalculation.Status') -> 'EngineeringCalculation': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Input(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
        def getSourceNodeId(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class StandardReference(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str]): ...
        def getStandard(self) -> java.lang.String: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Status(java.lang.Enum['EngineeringCalculation.Status']):
        CALCULATED: typing.ClassVar['EngineeringCalculation.Status'] = ...
        BLOCKED: typing.ClassVar['EngineeringCalculation.Status'] = ...
        FAILED: typing.ClassVar['EngineeringCalculation.Status'] = ...
        REVIEW_REQUIRED: typing.ClassVar['EngineeringCalculation.Status'] = ...
        APPROVED: typing.ClassVar['EngineeringCalculation.Status'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculation.Status': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringCalculation.Status']: ...

class EngineeringCalculationDag(java.io.Serializable):
    @staticmethod
    def from_(list: java.util.List[EngineeringCalculation]) -> 'EngineeringCalculationDag': ...
    def getCalculationsInExecutionOrder(self) -> java.util.List[EngineeringCalculation]: ...
    def getReadiness(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculationDag.Readiness': ...
    def getTopologicalOrder(self) -> java.util.List[java.lang.String]: ...
    def toMap(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Readiness(java.lang.Enum['EngineeringCalculationDag.Readiness']):
        COMPLETE: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        READY: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        BLOCKED_BY_DEPENDENCY: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        MISSING_STANDARD_REFERENCE: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        BLOCKED: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        FAILED: typing.ClassVar['EngineeringCalculationDag.Readiness'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringCalculationDag.Readiness': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringCalculationDag.Readiness']: ...

class EngineeringDiagramLayout(java.io.Serializable):
    @staticmethod
    def build(engineeringGraph: 'EngineeringGraph') -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringEdge(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], kind: 'EngineeringEdge.Kind', string4: typing.Union[java.lang.String, str]): ...
    def getId(self) -> java.lang.String: ...
    def getKind(self) -> 'EngineeringEdge.Kind': ...
    def getRole(self) -> java.lang.String: ...
    def getSourceId(self) -> java.lang.String: ...
    def getTargetId(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Kind(java.lang.Enum['EngineeringEdge.Kind']):
        CONTAINS: typing.ClassVar['EngineeringEdge.Kind'] = ...
        CONNECTS_TO: typing.ClassVar['EngineeringEdge.Kind'] = ...
        PROTECTS: typing.ClassVar['EngineeringEdge.Kind'] = ...
        APPLIES_TO: typing.ClassVar['EngineeringEdge.Kind'] = ...
        DEPENDS_ON: typing.ClassVar['EngineeringEdge.Kind'] = ...
        GENERATED_FROM: typing.ClassVar['EngineeringEdge.Kind'] = ...
        GOVERNS: typing.ClassVar['EngineeringEdge.Kind'] = ...
        REFERENCES: typing.ClassVar['EngineeringEdge.Kind'] = ...
        HAS_PORT: typing.ClassVar['EngineeringEdge.Kind'] = ...
        PROCESS_FLOW: typing.ClassVar['EngineeringEdge.Kind'] = ...
        SIGNAL_FLOW: typing.ClassVar['EngineeringEdge.Kind'] = ...
        ENERGY_FLOW: typing.ClassVar['EngineeringEdge.Kind'] = ...
        PART_OF_LINE: typing.ClassVar['EngineeringEdge.Kind'] = ...
        MEASURES: typing.ClassVar['EngineeringEdge.Kind'] = ...
        APPROVES: typing.ClassVar['EngineeringEdge.Kind'] = ...
        SUPERSEDES: typing.ClassVar['EngineeringEdge.Kind'] = ...
        REPRESENTS_SAME_AS: typing.ClassVar['EngineeringEdge.Kind'] = ...
        AUTHORED_IN: typing.ClassVar['EngineeringEdge.Kind'] = ...
        SYNCHRONIZED_FROM: typing.ClassVar['EngineeringEdge.Kind'] = ...
        CALCULATED_BY: typing.ClassVar['EngineeringEdge.Kind'] = ...
        VALIDATED_AGAINST: typing.ClassVar['EngineeringEdge.Kind'] = ...
        CONSUMED_BY_MODEL: typing.ClassVar['EngineeringEdge.Kind'] = ...
        INVALIDATES: typing.ClassVar['EngineeringEdge.Kind'] = ...
        REQUIRES_REAPPROVAL: typing.ClassVar['EngineeringEdge.Kind'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringEdge.Kind': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringEdge.Kind']: ...

class EngineeringGraph(java.io.Serializable):
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addEdge(self, engineeringEdge: EngineeringEdge) -> 'EngineeringGraph': ...
    def addNode(self, engineeringNode: 'EngineeringNode') -> 'EngineeringGraph': ...
    def compareTo(self, engineeringGraph: 'EngineeringGraph') -> 'EngineeringGraphDiff': ...
    @staticmethod
    def fromJson(string: typing.Union[java.lang.String, str]) -> 'EngineeringGraph': ...
    def getEdges(self) -> java.util.Map[java.lang.String, EngineeringEdge]: ...
    def getNode(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringNode': ...
    def getNodes(self) -> java.util.Map[java.lang.String, 'EngineeringNode']: ...
    def getProjectId(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...
    @staticmethod
    def read(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'EngineeringGraph': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringGraphBuilder:
    @typing.overload
    @staticmethod
    def fromProject(engineeringProject: jneqsim.process.engineering.EngineeringProject) -> EngineeringGraph: ...
    @typing.overload
    @staticmethod
    def fromProject(engineeringProject: jneqsim.process.engineering.EngineeringProject, list: java.util.List[EngineeringCalculation]) -> EngineeringGraph: ...

class EngineeringGraphDiff(java.io.Serializable):
    def getAddedEdgeIds(self) -> java.util.List[java.lang.String]: ...
    def getAddedNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getFromRevision(self) -> java.lang.String: ...
    def getImpactedNodeIds(self) -> java.util.Set[java.lang.String]: ...
    def getModifiedNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getProjectId(self) -> java.lang.String: ...
    def getRemovedEdgeIds(self) -> java.util.List[java.lang.String]: ...
    def getRemovedNodeIds(self) -> java.util.List[java.lang.String]: ...
    def getToRevision(self) -> java.lang.String: ...
    def isEmpty(self) -> bool: ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class EngineeringIds:
    @staticmethod
    def canonical(string: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    @staticmethod
    def edgeId(kind: EngineeringEdge.Kind, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> java.lang.String: ...
    @staticmethod
    def nodeId(kind: 'EngineeringNode.Kind', string: typing.Union[java.lang.String, str]) -> java.lang.String: ...

class EngineeringNode(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], kind: 'EngineeringNode.Kind', string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]): ...
    def addProvenance(self, engineeringProvenance: 'EngineeringProvenance') -> 'EngineeringNode': ...
    def getExternalKey(self) -> java.lang.String: ...
    def getId(self) -> java.lang.String: ...
    def getKind(self) -> 'EngineeringNode.Kind': ...
    def getLabel(self) -> java.lang.String: ...
    def getProperties(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    def getProvenance(self) -> java.util.List['EngineeringProvenance']: ...
    def putProperty(self, string: typing.Union[java.lang.String, str], object: typing.Any) -> 'EngineeringNode': ...
    def setLabel(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringNode': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Kind(java.lang.Enum['EngineeringNode.Kind']):
        PROJECT: typing.ClassVar['EngineeringNode.Kind'] = ...
        EQUIPMENT: typing.ClassVar['EngineeringNode.Kind'] = ...
        LINE: typing.ClassVar['EngineeringNode.Kind'] = ...
        INSTRUMENT: typing.ClassVar['EngineeringNode.Kind'] = ...
        REQUIREMENT: typing.ClassVar['EngineeringNode.Kind'] = ...
        BOUNDARY: typing.ClassVar['EngineeringNode.Kind'] = ...
        DESIGN_CASE: typing.ClassVar['EngineeringNode.Kind'] = ...
        CALCULATION: typing.ClassVar['EngineeringNode.Kind'] = ...
        DOCUMENT: typing.ClassVar['EngineeringNode.Kind'] = ...
        PORT: typing.ClassVar['EngineeringNode.Kind'] = ...
        NOZZLE: typing.ClassVar['EngineeringNode.Kind'] = ...
        PIPE_SEGMENT: typing.ClassVar['EngineeringNode.Kind'] = ...
        SIGNAL_CONNECTION: typing.ClassVar['EngineeringNode.Kind'] = ...
        ENERGY_CONNECTION: typing.ClassVar['EngineeringNode.Kind'] = ...
        PROCESS_TAP: typing.ClassVar['EngineeringNode.Kind'] = ...
        APPROVAL: typing.ClassVar['EngineeringNode.Kind'] = ...
        _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
        @typing.overload
        @staticmethod
        def valueOf(class_: typing.Type[_valueOf_0__T], string: typing.Union[java.lang.String, str]) -> _valueOf_0__T: ...
        @typing.overload
        @staticmethod
        def valueOf(string: typing.Union[java.lang.String, str]) -> 'EngineeringNode.Kind': ...
        @staticmethod
        def values() -> typing.MutableSequence['EngineeringNode.Kind']: ...

class EngineeringProvenance(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str]): ...
    def addEvidenceReference(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringProvenance': ...
    def getApprovalStatus(self) -> java.lang.String: ...
    def getDesignCaseId(self) -> java.lang.String: ...
    def getEvidenceReferences(self) -> java.util.List[java.lang.String]: ...
    def getMethod(self) -> java.lang.String: ...
    def getSourceReference(self) -> java.lang.String: ...
    def getSourceType(self) -> java.lang.String: ...
    def setApprovalStatus(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringProvenance': ...
    def setDesignCaseId(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringProvenance': ...
    def setMethod(self, string: typing.Union[java.lang.String, str]) -> 'EngineeringProvenance': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.model")``.

    EngineeringCalculation: typing.Type[EngineeringCalculation]
    EngineeringCalculationDag: typing.Type[EngineeringCalculationDag]
    EngineeringDiagramLayout: typing.Type[EngineeringDiagramLayout]
    EngineeringEdge: typing.Type[EngineeringEdge]
    EngineeringGraph: typing.Type[EngineeringGraph]
    EngineeringGraphBuilder: typing.Type[EngineeringGraphBuilder]
    EngineeringGraphDiff: typing.Type[EngineeringGraphDiff]
    EngineeringIds: typing.Type[EngineeringIds]
    EngineeringNode: typing.Type[EngineeringNode]
    EngineeringProvenance: typing.Type[EngineeringProvenance]
