
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.util
import jneqsim.process.engineering.calculation
import typing



class PipingNetworkDesignCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['PipingNetworkDesignCalculation.Input', 'PipingNetworkDesignCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'PipingNetworkDesignCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'PipingNetworkDesignCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['PipingNetworkDesignCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Candidate(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], double: float, double2: float): ...
    class Case(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float): ...
        @staticmethod
        def detailed(string: typing.Union[java.lang.String, str], double: float, double2: float, double3: float, double4: float, double5: float) -> 'PipingNetworkDesignCalculation.Case': ...
    class Input(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], pipingRulePack: 'PipingRulePack', list: java.util.List['PipingNetworkDesignCalculation.Candidate'], list2: java.util.List['PipingNetworkDesignCalculation.Segment'], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], float], typing.Mapping[typing.Union[java.lang.String, str], float]]): ...
    class Result(java.io.Serializable):
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Segment(java.io.Serializable):
        def __init__(self, string: typing.Union[java.lang.String, str], boolean: bool, boolean2: bool, double: float, double2: float, double3: float, double4: float, double5: float): ...
        def addCase(self, case: 'PipingNetworkDesignCalculation.Case') -> 'PipingNetworkDesignCalculation.Segment': ...
        def simultaneousDemandGroup(self, string: typing.Union[java.lang.String, str]) -> 'PipingNetworkDesignCalculation.Segment': ...

class PipingRulePack(java.io.Serializable):
    @staticmethod
    def builder(string: typing.Union[java.lang.String, str]) -> 'PipingRulePack.Builder': ...
    def getMaximumPressureGradientBarPerKm(self) -> float: ...
    def getMaximumReliefInletLossFraction(self) -> float: ...
    def getMinimumLiquidVelocityMPerS(self) -> float: ...
    def maximumVelocity(self, boolean: bool) -> float: ...
    @staticmethod
    def norsokP0022023Ac2024() -> 'PipingRulePack': ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Builder:
        def build(self) -> 'PipingRulePack': ...
        def edition(self, string: typing.Union[java.lang.String, str]) -> 'PipingRulePack.Builder': ...
        def maximumPressureGradientBarPerKm(self, double: float) -> 'PipingRulePack.Builder': ...
        def maximumReliefInletLossFraction(self, double: float) -> 'PipingRulePack.Builder': ...
        def standard(self, string: typing.Union[java.lang.String, str]) -> 'PipingRulePack.Builder': ...
        def velocityLimits(self, double: float, double2: float, double3: float) -> 'PipingRulePack.Builder': ...

class TransientPipingQualificationCalculation(jneqsim.process.engineering.calculation.EngineeringCalculationModule['TransientPipingQualificationCalculation.Input', 'TransientPipingQualificationCalculation.Result']):
    def __init__(self): ...
    def assess(self, input: 'TransientPipingQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.CalculationReadiness: ...
    def calculate(self, input: 'TransientPipingQualificationCalculation.Input', engineeringCalculationContext: jneqsim.process.engineering.calculation.EngineeringCalculationContext) -> jneqsim.process.engineering.calculation.EngineeringCalculationResult['TransientPipingQualificationCalculation.Result']: ...
    def getMethod(self) -> java.lang.String: ...
    def getMethodVersion(self) -> java.lang.String: ...
    class Input(java.io.Serializable):
        @staticmethod
        def builder(string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str]) -> 'TransientPipingQualificationCalculation.Input.Builder': ...
        class Builder:
            def addSample(self, sample: 'TransientPipingQualificationCalculation.Sample') -> 'TransientPipingQualificationCalculation.Input.Builder': ...
            def build(self) -> 'TransientPipingQualificationCalculation.Input': ...
            def geometry(self, double: float, double2: float, double3: float) -> 'TransientPipingQualificationCalculation.Input.Builder': ...
            def pressureLimits(self, double: float, double2: float, double3: float) -> 'TransientPipingQualificationCalculation.Input.Builder': ...
            def resolutionAndBalanceLimits(self, double: float, double2: float) -> 'TransientPipingQualificationCalculation.Input.Builder': ...
            def responseLimits(self, double: float, double2: float, double3: float) -> 'TransientPipingQualificationCalculation.Input.Builder': ...
    class Result(jneqsim.process.engineering.calculation.EngineeringConstraintResult, java.io.Serializable):
        def allConstraintsSatisfied(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    class Sample(java.io.Serializable):
        def __init__(self, double: float, double2: float, double3: float, double4: float, double5: float, double6: float, double7: float, double8: float, double9: float): ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.engineering.piping")``.

    PipingNetworkDesignCalculation: typing.Type[PipingNetworkDesignCalculation]
    PipingRulePack: typing.Type[PipingRulePack]
    TransientPipingQualificationCalculation: typing.Type[TransientPipingQualificationCalculation]
