name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install neqsim pytest
      - name: Run tests with pytest
        run: python -m pytest
  buildforJava8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install neqsim pytest
      - name: Run tests with pytest
        run: python -m pytest 
