
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.io
import java.lang
import java.nio.file
import java.util
import jpype.protocol
import typing



class ModelDependency(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], boolean: bool): ...
    def getModelId(self) -> java.lang.String: ...
    def getRelationship(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...
    def getSourceSystem(self) -> java.lang.String: ...
    def isRequired(self) -> bool: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ModelPackageArtifact(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], long: int, string4: typing.Union[java.lang.String, str]): ...
    def getMediaType(self) -> java.lang.String: ...
    def getPath(self) -> java.lang.String: ...
    def getRole(self) -> java.lang.String: ...
    def getSha256(self) -> java.lang.String: ...
    def getSizeBytes(self) -> int: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ModelPackageIdentity(java.io.Serializable):
    def __init__(self, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], string3: typing.Union[java.lang.String, str], string4: typing.Union[java.lang.String, str], string5: typing.Union[java.lang.String, str], string6: typing.Union[java.lang.String, str], string7: typing.Union[java.lang.String, str], string8: typing.Union[java.lang.String, str]): ...
    def getAssetId(self) -> java.lang.String: ...
    def getFacilityId(self) -> java.lang.String: ...
    def getLifecyclePhase(self) -> java.lang.String: ...
    def getModelId(self) -> java.lang.String: ...
    def getModelType(self) -> java.lang.String: ...
    def getParentRevision(self) -> java.lang.String: ...
    def getResponsibleParty(self) -> java.lang.String: ...
    def getRevision(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class ModelPackageValidator:
    @staticmethod
    def validate(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'ModelPackageValidator.Result': ...
    class Result(java.io.Serializable):
        def getFindings(self) -> java.util.List[java.lang.String]: ...
        def isValid(self) -> bool: ...
        def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...

class NeqSimModelPackage(java.io.Serializable):
    FILE_NAME: typing.ClassVar[java.lang.String] = ...
    SCHEMA_VERSION: typing.ClassVar[java.lang.String] = ...
    SCHEMA_URI: typing.ClassVar[java.lang.String] = ...
    @staticmethod
    def create(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], modelPackageIdentity: ModelPackageIdentity, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], list: java.util.List[ModelDependency], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> 'NeqSimModelPackage': ...
    def getArtifacts(self) -> java.util.List[ModelPackageArtifact]: ...
    def getDependencies(self) -> java.util.List[ModelDependency]: ...
    def getGraphArtifact(self) -> java.lang.String: ...
    def getIdentity(self) -> ModelPackageIdentity: ...
    def getQualificationStatus(self) -> java.lang.String: ...
    def getSoftwareVersions(self) -> java.util.Map[java.lang.String, java.lang.String]: ...
    @staticmethod
    def read(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath]) -> 'NeqSimModelPackage': ...
    def toJson(self) -> java.lang.String: ...
    def toMap(self) -> java.util.Map[java.lang.String, typing.Any]: ...
    @staticmethod
    def write(path: typing.Union[java.nio.file.Path, jpype.protocol.SupportsPath], modelPackageIdentity: ModelPackageIdentity, string: typing.Union[java.lang.String, str], string2: typing.Union[java.lang.String, str], list: java.util.List[ModelDependency], map: typing.Union[java.util.Map[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]], typing.Mapping[typing.Union[java.lang.String, str], typing.Union[java.lang.String, str]]]) -> java.nio.file.Path: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.process.modelpackage")``.

    ModelDependency: typing.Type[ModelDependency]
    ModelPackageArtifact: typing.Type[ModelPackageArtifact]
    ModelPackageIdentity: typing.Type[ModelPackageIdentity]
    ModelPackageValidator: typing.Type[ModelPackageValidator]
    NeqSimModelPackage: typing.Type[NeqSimModelPackage]
